import {createRequire} from 'node:module';import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare,Response:MFResponse}=wr('miniflare'),vapid=require('web-push').generateVAPIDKeys();let calls=0;
const mf=new Miniflare({modules:(await readdir('dist/server',{recursive:true})).filter(p=>p.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:0).map(p=>({type:'ESModule',path:path.resolve('dist/server',p)})),modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],cf:false,bindings:{VAPID_PUBLIC_KEY:vapid.publicKey,VAPID_PRIVATE_KEY:vapid.privateKey,PUSH_SCHEDULER_SECRET:'secret',OPENAI_API_KEY:'test',GDPR_AI_APPROVED:'true'},outboundService:async()=>{calls++;throw Error('Unexpected outbound transfer')}});
try{
 const db=await mf.getD1Database('DB'),bucket=await mf.getR2Bucket('BUCKET');for(const migration of(await readdir('drizzle')).filter(p=>p.endsWith('.sql')).sort())for(const stmt of(await readFile('drizzle/'+migration,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(stmt).run();
 const jpeg=new Uint8Array(await readFile('tests/fixtures/metadata.jpg'));const now=Date.now();for(const id of ['owner','alice','bob','outside']){await db.prepare('INSERT INTO members(id,name,email,status,joined,approved,admin) VALUES(?,?,?,\'approved\',1,1,?)').bind(id,id,'',id==='owner'?1:0).run();await db.prepare('INSERT INTO login_sessions(token,user,expires) VALUES(?,?,?)').bind(crypto.createHash('sha256').update(id).digest('hex'),id,now+86400000).run()}
 await db.prepare("INSERT INTO sessions(token,user,expires) VALUES('64f46a7526a186d2346552453ae478ca51244674f5b21ba150bd483b39f7c812','owner',?)").bind(now+86400000).run();await db.prepare("INSERT INTO groups(id,name,owner,created) VALUES('g','Private','alice',1)").run();for(const id of ['alice','bob'])await db.prepare("INSERT INTO group_members(group_id,user,joined) VALUES('g',?,1)").bind(id).run();
 await db.prepare("INSERT INTO friendships(a,b,requester,status,created) VALUES('alice','bob','alice','accepted',1)").run();
 await db.prepare('INSERT INTO settings(key,value) VALUES (?,?)').bind('admin-agreement:owner',JSON.stringify({version:'2026-10-07.1',accepted:now})).run();
 await db.prepare('INSERT INTO settings(key,value) VALUES (?,?)').bind('owner','owner').run();
 async function raw(user,url,body,pin=true){const headers={cookie:'hunt_login='+user+(user==='owner'&&pin?'; hunt_admin=pin':'')};let payload;if(body instanceof FormData){const encoded=new Request('https://test.invalid',{method:'POST',body});headers['content-type']=encoded.headers.get('content-type');payload=await encoded.arrayBuffer()}else if(body){headers['content-type']='application/json';payload=JSON.stringify(body)}return mf.dispatchFetch('https://test.invalid'+url,{method:body?'POST':'GET',headers,...(body?{body:payload}:{})})}
 async function req(user,url,body,pin=true){const r=await raw(user,url,body,pin);return{status:r.status,data:await r.json()}}
 async function upload(user='alice',room='g',name='image.jpg',bytes=jpeg,id=crypto.randomUUID()){const f=new FormData();f.set('room',room);f.set('id',id);f.set('file',new Blob([bytes]),name);return req(user,'/api/chat/attachments',f)}
 async function send(body='',attachments=[],photo=null,room='g',user='alice',id=crypto.randomUUID()){await db.prepare('DELETE FROM settings WHERE key=?').bind('chat-rate:'+user).run();return req(user,'/api/chat?room='+encodeURIComponent(room),{action:'send',id,room,body,attachments,photo})}
 async function tick(){const r=await mf.dispatchFetch('https://test.invalid/api/push/tick',{method:'POST',headers:{'x-photo-hunt-scheduler-key':'secret'}});assert.equal(r.status,200,await r.clone().text())}
 assert.equal((await upload('outside')).status,403);assert.equal((await upload('alice','g','unsafe.svg',new TextEncoder().encode('<svg/>'))).status,400);
 const up=await upload();assert.equal(up.status,200);const attachment=up.data.attachment;assert(!('key' in attachment));assert.equal((await raw('bob','/api/chat/attachments/'+attachment.id)).status,403,'draft private to uploader');assert.equal((await raw('alice','/api/chat/attachments/'+attachment.id)).status,200);
 assert.equal((await upload('bob','g','image.jpg',jpeg,attachment.id)).status,409);assert.equal((await upload('alice','g','image.jpg',new TextEncoder().encode('changed'),attachment.id)).status,400,'cannot overwrite same UUID with different content');
 assert.equal((await send('',[attachment.id],null,'g','bob')).status,403);const sent=await send('',[attachment.id]);assert.equal(sent.status,200);const id=sent.data.id;assert.equal(calls,0,'delivery never invokes AI');
 assert.equal((await send('',[attachment.id],null,'g','alice',id)).status,200,'media retry idempotent');assert.equal((await send('changed',[attachment.id],null,'g','alice',id)).status,409);assert.equal((await send('',[attachment.id])).status,403,'no attachment reuse in new message');
 assert.equal((await raw('bob','/api/chat/attachments/'+attachment.id)).status,200);assert.equal((await raw('outside','/api/chat/attachments/'+attachment.id)).status,403);assert.equal((await raw('owner','/api/chat/attachments/'+attachment.id)).status,403,'admin cannot browse unflagged private media');
 const view=await req('bob','/api/chat?room=g');assert.equal(view.data.messages[0].attachments[0].id,attachment.id);assert(!JSON.stringify(view.data).includes('chat/'+attachment.id));
 assert.equal(await db.prepare('SELECT message FROM chat_reviews WHERE message=?').bind(id).first(),null,'private message never queued for AI');assert.equal((await req('bob','/api/chat',{action:'report',room:'g',id})).status,200);assert(await db.prepare('SELECT id FROM chat_messages WHERE id=?').bind(id).first(),'AI does not remove message');assert.equal((await req('owner','/api/chat/moderation',null,false)).status,403);assert.equal((await req('bob','/api/chat/moderation')).status,403);
 assert((await req('owner','/api/chat/moderation')).data.items.some(x=>x.id===id));assert.equal((await raw('owner','/api/chat/attachments/'+attachment.id+'?review=1')).status,200,'PIN admin can inspect specifically flagged asset');assert.equal((await req('owner','/api/chat/moderation',{id,status:'dismissed'})).status,200);assert(await db.prepare('SELECT id FROM chat_messages WHERE id=?').bind(id).first());
 const clear=(await send('Hei',[],null,'public')).data.id;assert.equal(await db.prepare('SELECT message FROM chat_reviews WHERE message=?').bind(clear).first(),null);assert(!(await req('owner','/api/chat/moderation')).data.items.some(x=>x.id===clear));
 const pdf=await upload('alice','g','document.pdf',new TextEncoder().encode('%PDF-1.4 test'));assert.equal(pdf.status,400,'complex documents paused');const doc=(await send('Jeg skal drepe deg!',[],null,'public')).data.id;assert.equal((await db.prepare('SELECT status FROM chat_reviews WHERE message=?').bind(doc).first()).status,'flagged');const link=(await send('Se https://example.org/test',[],null,'public')).data.id;assert.equal(await db.prepare('SELECT message FROM chat_reviews WHERE message=?').bind(link).first(),null,'link target is not scanned or fetched');await tick();assert.equal(calls,0,'local moderation never invokes external AI');

 await db.prepare("INSERT INTO seasons(id,name,start,end) VALUES('s','Old',1,2)").run();for(const [cid,end]of[['done',now-1],['active',now+60000]]){await db.prepare('INSERT INTO challenges(id,season,title,start,end,duration,created) VALUES(?,\'s\',?,1,?,60,1)').bind(cid,cid,end).run();await db.prepare('INSERT INTO submissions(id,challenge,user,key,submitted,elapsed) VALUES(?,?,\'alice\',?,1,1)').bind(cid,cid,'photos/'+cid).run();await bucket.put('photos/'+cid,jpeg)}
 assert.equal((await send('',[], 'active')).status,403);const shared=await send('',[],'done','dm:alice:bob');assert.equal(shared.status,200);assert.equal((await raw('bob','/api/chat/photo/'+shared.data.id)).status,200);assert.equal((await raw('outside','/api/chat/photo/'+shared.data.id)).status,403);assert.equal((await send('',[],'done','public','outside')).status,403,'cannot redistribute inaccessible source photo');
 const draft=await upload();const del=await mf.dispatchFetch('https://test.invalid/api/chat/attachments/'+draft.data.attachment.id,{method:'DELETE',headers:{cookie:'hunt_login=alice'}});assert.equal(del.status,200);assert.equal(await db.prepare('SELECT id FROM chat_attachments WHERE id=?').bind(draft.data.attachment.id).first(),null);
 const expired=await upload();await db.prepare('UPDATE chat_attachments SET created=1 WHERE id=?').bind(expired.data.attachment.id).run();await tick();assert.equal(await db.prepare('SELECT id FROM chat_attachments WHERE id=?').bind(expired.data.attachment.id).first(),null,'old unused uploads pruned');
 assert.equal((await req('alice','/api/chat?room=g',{action:'delete',room:'g',id})).status,200);assert.equal(await db.prepare('SELECT message FROM chat_reviews WHERE message=?').bind(id).first(),null);assert.equal(await db.prepare('SELECT id FROM chat_attachments WHERE id=?').bind(attachment.id).first(),null,'message deletion cleans attachments');
 assert.equal((await req('owner','/api/chat/moderation',{id:doc,status:'confirmed'})).status,200);assert(await db.prepare('SELECT id FROM chat_messages WHERE id=?').bind(doc).first(),'confirmation does not delete');
 const bobFile=await upload('bob','dm:alice:bob','note.txt',new TextEncoder().encode('Hei'));assert.equal(bobFile.status,200);const bobMessage=await send('',[bobFile.data.attachment.id],null,'dm:alice:bob','bob');assert.equal(bobMessage.status,200);assert.equal((await req('owner','/api/hunt',{action:'delete-member',id:'alice'})).status,200);assert.equal(await db.prepare('SELECT id FROM chat_attachments WHERE id=?').bind(bobFile.data.attachment.id).first(),null,'deleting participant removes both sides of direct chat media');assert.equal((await db.prepare('SELECT COUNT(*) n FROM chat_reviews').first()).n,0,'deleted rooms clean review data');
 console.log('PASS: private-room reporting boundary and public local word filtering, internal photo sharing, attachment isolation and immutable uploads, duplicate-safe media delivery without AI, local flagging and manual review, admin PIN controls, no automatic deletion, binary/link no automatic inspection and message/account attachment cleanup.');
}finally{await mf.dispose()}
