import {createRequire} from 'node:module';import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare,Response:MFResponse}=wr('miniflare');
let aiMode='good',calls=0;const words=['kopp','sykkel','stein','sko','lampe','hund'];
const mf=new Miniflare({modules:(await readdir('dist/server',{recursive:true})).filter(p=>p.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:0).map(p=>({type:'ESModule',path:path.resolve('dist/server',p)})),modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{ADMIN_PIN:'9752',OPENAI_API_KEY:'fake-test-key'},cf:false,outboundService:async req=>{assert.equal(req.url,'https://api.openai.com/v1/chat/completions');assert.equal(req.headers.get('authorization'),'Bearer fake-test-key');calls++;const payload=await req.json();assert(payload.messages[0].content.includes('Vestvågøy'));assert.equal(payload.store,false);const dates=JSON.parse(payload.messages[1].content).dates;return new MFResponse(JSON.stringify({choices:[{message:{content:JSON.stringify({words:aiMode==='bad'?['to ord']:aiMode==='english'?['cup','bicycle','stone']:words.slice(0,dates.length)})}}]}),{status:aiMode==='quota'?429:200})}});
try{
const db=await mf.getD1Database('DB');for(const migration of(await readdir('drizzle')).filter(p=>p.endsWith('.sql')&&p<'0009').sort())for(const stmt of(await readFile('drizzle/'+migration,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(stmt).run();
const now=Date.now(),headers={};for(const user of ['admin','early','late','pending']){await db.prepare('INSERT INTO members(id,name,email,status,joined,approved,admin) VALUES (?,?,?,?,?,?,?)').bind(user,user,'',user==='pending'?'pending':'approved',now-10000,now-5000,user==='admin'?1:0).run();await db.prepare('INSERT INTO login_sessions(token,user,expires) VALUES (?,?,?)').bind(crypto.createHash('sha256').update(user).digest('hex'),user,now+86400000).run();headers[user]={cookie:'hunt_login='+user+(user==='admin'?'; hunt_admin=admin':''),'content-type':'application/json'};await db.prepare('INSERT INTO push_subscriptions(id,user,endpoint,p256dh,auth,created,updated) VALUES (?,?,?,?,?,?,?)').bind(user,user,'https://fcm.googleapis.com/'+user,'k','a',1,1).run();}
await db.prepare('INSERT INTO sessions(token,user,expires) VALUES (?,?,?)').bind('admin','admin',now+86400000).run();
async function req(user,body,url='/api/hunt'){const h={...headers[user]};let data;if(body instanceof FormData){const encoded=new Response(body);h['content-type']=encoded.headers.get('content-type');data=new Uint8Array(await encoded.arrayBuffer())}else data=body?JSON.stringify(body):undefined;const r=await mf.dispatchFetch('https://test.invalid'+url,{method:body?'POST':'GET',headers:h,...(data?{body:data}:{})});return {status:r.status,data:await r.json()}}


for(const stmt of(await readFile('drizzle/0009_nervous_the_professor.sql','utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(stmt).run();
for(const migration of(await readdir('drizzle')).filter(p=>p.endsWith('.sql')&&p>='0010').sort())for(const stmt of(await readFile('drizzle/'+migration,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(stmt).run();
assert.equal((await db.prepare("SELECT COUNT(*) n FROM group_members WHERE group_id='familien-glum'").first()).n,4);
assert.equal((await db.prepare("SELECT owner FROM groups WHERE id='familien-glum'").first()).owner,'admin');
assert.equal((await db.prepare('SELECT COUNT(*) n FROM friendships').first()).n,6);
assert.equal((await db.prepare("SELECT status FROM members WHERE id='pending'").first()).status,'approved');
const social=(user,body)=>req(user,body,'/api/social');
async function register(name){const r=await mf.dispatchFetch('https://test.invalid/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'register',name,username:name,pin:'123456',installed:true})});assert.equal(r.status,200,await r.clone().text());headers[name]={'content-type':'application/json',cookie:r.headers.get('set-cookie').match(/hunt_login=([^;]+)/)[0]};const u=(await req(name)).data.user;assert.equal(u.status,'approved');return u.id;}
assert.equal((await social('admin',{action:'group-role',group:'familien-glum',user:'early',role:'admin'})).status,200);
assert.equal((await social('early')).data.groups[0].canManage,true);
assert.equal((await social('early',{action:'group-role',group:'familien-glum',user:'late',role:'admin'})).status,403);
assert.equal((await social('early',{action:'remove-group-member',group:'familien-glum',user:'admin'})).status,403);
assert.equal((await social('early',{action:'remove-group-member',group:'familien-glum',user:'late'})).status,200);
assert.equal((await social('early',{action:'invite-group',group:'familien-glum',user:'late'})).status,200);
assert.equal((await social('late')).data.invitations.length,1);
assert.equal((await social('late',{action:'answer-group',group:'familien-glum',accept:true})).status,200,'admin invitation can be accepted');
await social('early',{action:'remove-group-member',group:'familien-glum',user:'late'});
await social('early',{action:'invite-group',group:'familien-glum',user:'late'});
assert.equal((await social('admin',{action:'group-role',group:'familien-glum',user:'early',role:'member'})).status,200);
assert.equal((await social('late',{action:'answer-group',group:'familien-glum',accept:true})).status,403,'demotion revokes pending invitations');
assert.equal((await social('early',{action:'invite-group',group:'familien-glum',user:'late'})).status,403);
await social('admin',{action:'invite-group',group:'familien-glum',user:'late'});
await social('late',{action:'answer-group',group:'familien-glum',accept:true});
const nova=await register('nova'),lars=await register('lars');
assert.equal((await social('nova')).data.groups.length,0);
assert.equal((await social('nova',{action:'friend-request',user:lars})).status,200);
assert.equal((await social('nova',{action:'answer-friend',user:lars,accept:true})).status,403,'cannot accept own outgoing request');
assert.equal((await social('lars',{action:'answer-friend',user:nova,accept:true})).status,200);
const group=(await social('nova',{action:'create-group',name:'Turvenner'})).data.id;
assert.equal((await social('lars',{action:'invite-group',group,user:'early'})).status,403,'owner-only invites');
assert.equal((await social('lars',{action:'answer-group',group,accept:true})).status,403,'no self-join');
assert.equal((await social('nova',{action:'invite-group',group,user:lars})).status,200);
assert.equal((await social('lars',{action:'answer-group',group,accept:true})).status,200);
await db.prepare("INSERT INTO seasons(id,name,start) VALUES('album','Test',1)").run();await db.prepare("INSERT INTO challenges(id,season,title,start,end,duration,created) VALUES('hunt','album','stein',1,2,1,1)").run();
for(const [id,user] of [['p1','early'],['p2',nova],['p3',lars]]){await db.prepare('INSERT INTO submissions(id,challenge,user,key,submitted,elapsed) VALUES(?,?,?,?,?,?)').bind(id,'hunt',user,id,1,1000).run();await (await mf.getR2Bucket('BUCKET')).put(id,'jpeg');}
const ids=async user=>(await req(user)).data.challenges.find(c=>c.id==='hunt').submissions.map(p=>p.id).sort();
assert.deepEqual(await ids('early'),['p1']);assert.deepEqual(await ids('admin'),['p1'],'admin does not bypass group privacy');assert.deepEqual(await ids('nova'),['p2','p3']);
const outsider=(await req('early',undefined,'/api/hunt?profile='+lars));assert.equal(outsider.status,200);assert.equal(outsider.data.canSeePhotos,false);assert.deepEqual(outsider.data.photos,[]);assert.equal(outsider.data.profile.friendCount,1);assert.equal(outsider.data.friendship,null);
assert.equal((await req('nova')).data.user.friendCount,1);
assert.equal((await req('nova',undefined,'/api/hunt?profile='+lars)).data.friendship.status,'accepted');
assert.equal((await mf.dispatchFetch('https://test.invalid/api/photo/p3',{headers:headers.early})).status,403);
for(const action of ['react','comment','report-photo'])assert.equal((await req('early',{action,id:'p3',emoji:'❤️',body:'hi',reason:'test'})).status,403);
assert.equal((await social('admin',{action:'friend-request',user:nova})).status,200);assert.equal((await social('nova',{action:'answer-friend',user:'admin',accept:true})).status,200);
assert.equal((await social('admin',{action:'invite-group',group:'familien-glum',user:nova})).status,200);
assert.equal((await social('nova',{action:'answer-group',group:'familien-glum',accept:true})).status,200);
const feed=(await req('nova')).data;assert.equal(feed.groups.length,2);assert.equal(feed.challenges.find(c=>c.id==='hunt').groupCounts[group],2);assert.equal(feed.challenges.find(c=>c.id==='hunt').groupCounts['familien-glum'],2);assert.deepEqual(feed.groups.find(g=>g.id===group).members.sort(),[nova,lars].sort());
assert.deepEqual(await ids('nova'),['p1','p2','p3'],'union of both groups');assert.deepEqual(await ids('early'),['p1','p2'],'no transitive group sharing');
assert.equal((await mf.dispatchFetch('https://test.invalid/api/photo/p2',{headers:headers.early})).status,200);
assert.equal((await social('early',{action:'invite-group',group:'familien-glum',user:lars})).status,403);
assert.equal((await req('nova',{action:'comment',id:'p3',body:'Good!'})).status,200);
assert.equal((await req('early')).data.comments.length,0,'other-group comments hidden');
// A shared photo has one discussion even when its viewers belong to different groups.
await db.prepare('UPDATE comments SET created=?').bind(now-10000).run();
assert.equal((await req('early',{action:'comment',id:'p2',body:'Shared across groups'})).status,200);
const root=(await req('lars')).data.comments.find(c=>c.body==='Shared across groups');assert(root,'other group sees comments on shared author');
assert.equal((await req('lars',{action:'comment',id:'p2',body:'A reply',parent:root.id})).status,200);
const reply=(await req('early')).data.comments.find(c=>c.body==='A reply');assert.equal(reply.parent_id,root.id);
await db.prepare('UPDATE comments SET created=?').bind(now-10000).run();
assert.equal((await req('early',{action:'comment',id:'p1',body:'Wrong photo',parent:root.id})).status,400);
assert.equal((await req('early',{action:'react',id:'p2',emoji:'👍'})).status,200);
assert.equal((await req('early',{action:'react',id:'p2',emoji:'❤️'})).status,200);
let shared=(await req('lars')).data.reactions.filter(r=>r.submission==='p2');assert.equal(shared.length,1);assert.equal(shared[0].emoji,'❤️');
assert.equal((await req('early',{action:'react',id:'p2',emoji:'❤️'})).status,200);assert.equal((await req('lars')).data.reactions.filter(r=>r.submission==='p2').length,0);
assert.equal((await req('early',{action:'delete-comment',id:root.id})).status,200);
const thread=(await req('lars')).data.comments;assert.equal(thread.find(c=>c.id===root.id).deleted,1);assert.equal(thread.find(c=>c.id===reply.id).body,'A reply');
assert.equal((await social('nova',{action:'leave-group',group:'familien-glum'})).status,200);assert.deepEqual(await ids('early'),['p1']);
// Group membership and friendship independently grant access.
assert.equal((await social('nova',{action:'remove-friend',user:lars})).status,200);
assert.deepEqual(await ids('nova'),['p2','p3'],'group member stays visible without friendship');
assert.deepEqual((await req('nova')).data.friendIds,['admin'],'removed peer absent from friend feed');
await social('nova',{action:'friend-request',user:lars});
await social('lars',{action:'answer-friend',user:nova,accept:true});
assert.equal((await social('lars',{action:'leave-group',group})).status,200);
assert.deepEqual(await ids('nova'),['p2','p3'],'accepted friend visible without shared group');
const friendFeed=(await req('lars')).data;
assert.equal(friendFeed.groups.length,0);
assert(friendFeed.friendIds.includes(nova));
assert.equal(friendFeed.challenges.find(c=>c.id==='hunt').friendCount,1);
assert.equal(friendFeed.challenges.find(c=>c.id==='hunt').groupFeedCount,0);
assert.equal((await mf.dispatchFetch('https://test.invalid/api/photo/p3',{headers:headers.nova})).status,200);
assert.equal((await req('nova',undefined,'/api/hunt?profile='+lars)).data.canSeePhotos,true);
assert.equal((await mf.dispatchFetch('https://test.invalid/api/photo/p3',{headers:headers.admin})).status,403,'no friends-of-friends access');
await db.prepare("INSERT INTO challenges(id,season,title,start,end,duration,created) VALUES('live','album','secret',?,?,1,1)").bind(now-1000,now+3600000).run();
await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed) VALUES('private','live',?,'private',?,500)").bind(lars,now).run();
await (await mf.getR2Bucket('BUCKET')).put('private','jpeg');
assert.deepEqual((await req('nova')).data.challenges.find(c=>c.id==='live').submissions,[],'friend pictures hidden during hunt');
assert.equal((await mf.dispatchFetch('https://test.invalid/api/photo/private',{headers:headers.nova})).status,403);
assert.equal((await req('nova',{action:'comment',id:'private',body:'hidden'})).status,403);
assert(!(await req('nova',undefined,'/api/hunt?profile='+lars)).data.photos.some(p=>p.id==='private'));
await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed) VALUES('my-live','live',?,'my-live',?,600)").bind(nova,now).run();
assert.equal((await mf.dispatchFetch('https://test.invalid/api/photo/private',{headers:headers.nova})).status,200,'own submission opens friend photo');
assert.equal((await req('nova',{action:'report-photo',id:'p3',reason:'Friend review'})).status,200);
assert.equal((await db.prepare('SELECT COUNT(*) n FROM photo_voters WHERE submission=? AND user=?').bind('p3',nova).first()).n,1,'direct friend eligible for review');
await social('nova',{action:'remove-friend',user:lars});
assert.deepEqual(await ids('nova'),['p2'],'removing friend revokes access when no shared group');
assert.equal((await mf.dispatchFetch('https://test.invalid/api/photo/p3',{headers:headers.nova})).status,403);
assert.equal((await req('nova',undefined,'/api/hunt?profile='+lars)).data.canSeePhotos,false);
await social('nova',{action:'friend-request',user:lars});
assert.equal((await mf.dispatchFetch('https://test.invalid/api/photo/p3',{headers:headers.nova})).status,403,'pending friendship grants no access');
await social('lars',{action:'answer-friend',user:nova,accept:true});
assert.equal((await social('nova',{action:'report-user',user:lars,reason:'Test report'})).status,200);
assert.equal((await social('early')).data.reports.length,0);assert.equal((await social('admin')).data.reports.length,1);
assert.equal((await req('early',{action:'member',id:lars,status:'blocked'})).status,403);
assert.equal((await req('admin',{action:'member',id:lars,status:'blocked'})).status,200);assert.equal((await social('lars')).status,401);
assert.deepEqual(await ids('nova'),['p2'],'blocked author disappears');
assert.equal((await social('nova',{action:'username',username:'nova_new'})).status,200);
for(const name of ['nova','nova_new'])assert.equal((await req('nova',{action:'login',name,pin:'123456'},'/api/auth')).status,200);
assert.equal((await social('nova',{action:'username',username:'bad name'})).status,400);
// Inbox is scoped to the recipient and read state persists per account.
await social('early',{action:'friend-request',user:nova});
await social('admin',{action:'invite-group',group:'familien-glum',user:nova});
await db.prepare('UPDATE comments SET created=?').bind(now-10000).run();
assert.equal((await req('admin',{action:'comment',id:'p2',body:'Inbox comment'})).status,200);
assert.equal((await req('admin',{action:'react',id:'p2',emoji:'👍'})).status,200);
const notices=(await req('nova',undefined,'/api/notifications')).data;
for(const kind of ['friend','group','comment','reaction'])assert(notices.items.some(item=>item.kind===kind),kind+' notification received');
assert(notices.unread>0);
assert(!(await req('early',undefined,'/api/notifications')).data.items.some(item=>item.title==='admin kommenterte bildet ditt'),'cannot read another recipient inbox');
assert.equal((await req('nova',{ids:notices.items.map(item=>item.id)},'/api/notifications')).status,200);
assert.equal((await req('nova',undefined,'/api/notifications')).data.unread,0,'read state persists');
assert.equal((await req('nova',{ids:'invalid'},'/api/notifications')).status,400);
await social('nova',{action:'answer-friend',user:'early',accept:true});
assert(!(await req('nova',undefined,'/api/notifications')).data.items.some(item=>item.kind==='friend'),'answered request disappears');
assert.equal((await mf.dispatchFetch('https://test.invalid/api/notifications')).status,401);
assert.equal((await req('nova',{action:'profile-settings',bio:'Liker naturbilder',featuredBadge:'',showFriendCount:false})).status,200);
assert.equal((await req('nova')).data.user.settings.bio,'Liker naturbilder');
assert.equal((await req('early',undefined,'/api/hunt?profile='+nova)).data.profile.friendCount,null,'hidden count stays hidden server-side');
assert.equal((await req('nova',{action:'profile-settings',bio:'a'.repeat(161)})).status,400);
assert.equal((await req('nova',{action:'profile-settings',bio:'Test',featuredBadge:'win-streak-10'})).status,400,'unearned badge rejected');
assert.equal((await req('nova',{action:'profile-settings',bio:'Liker naturbilder',featuredBadge:'first-photo',showFriendCount:false})).status,200);
assert.equal((await req('nova',{action:'appearance',theme:'dark'})).status,200);
assert.equal((await req('nova')).data.user.settings.theme,'dark','theme persists on account');
assert.equal((await req('nova',{action:'appearance',theme:'invalid'})).status,400);
assert.equal((await req('nova',{action:'profile-settings',bio:'Ny bio',featuredBadge:'first-photo',showFriendCount:false})).status,200);
assert.equal((await req('nova')).data.user.settings.theme,'dark','profile edits preserve theme');
const bugForm=new FormData();bugForm.set('description','Filterknappen virker ikke');bugForm.set('page','Bilder');bugForm.set('photo',new Blob([new Uint8Array([255,216,255,...new Array(100).fill(0)])],{type:'image/jpeg'}),'screen.jpg');
assert.equal((await req('nova',bugForm,'/api/bugs')).status,200);
assert.equal((await req('nova',undefined,'/api/bugs')).status,403,'bug inbox is admin only');
assert.equal((await mf.dispatchFetch('https://test.invalid/api/bugs')).status,401);
const bugList=(await req('admin',undefined,'/api/bugs')).data.reports;assert.equal(bugList.length,1);assert.equal(bugList[0].username,'nova_new');assert.equal(bugList[0].description,'Filterknappen virker ikke');
const bugUrl='https://test.invalid/api/bugs/'+bugList[0].id;
assert.equal((await mf.dispatchFetch(bugUrl,{headers:headers.nova})).status,403,'attached image is private');
assert.equal((await mf.dispatchFetch(bugUrl,{headers:headers.admin})).status,200);
assert.equal((await req('nova',bugForm,'/api/bugs')).status,429,'bug rate limit');
assert.equal((await mf.dispatchFetch('https://test.invalid/api/bugs',{method:'PATCH',headers:headers.admin,body:JSON.stringify({id:bugList[0].id,resolved:true})})).status,200);
assert.equal((await req('admin',undefined,'/api/bugs')).data.reports[0].resolved,true);
console.log('PASS: groups and private feeds, durable profile preferences, unearned badge rejection, bug upload, admin-only reports/images, rate limiting and resolved state.');
}finally{await mf.dispose()}
