import {createRequire} from 'node:module';import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare,Response:MFResponse}=wr('miniflare');let bank=[],aiMode='good';
const mf=new Miniflare({modules:(await readdir('dist/server',{recursive:true})).filter(p=>p.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:0).map(p=>({type:'ESModule',path:path.resolve('dist/server',p)})),modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{ADMIN_PIN:'9752',OPENAI_API_KEY:'fake'},cf:false,outboundService:async req=>{const b=await req.json();if(b.response_format.json_schema.name==='safe_norwegian_word'){assert.equal(b.store,false);assert(b.messages[0].content.includes('Ved tvil'));const word=JSON.parse(b.messages[1].content).word;if(aiMode==='offline')return new MFResponse('{}',{status:503});if(aiMode==='malformed')return new MFResponse(JSON.stringify({choices:[{message:{content:'{}'}}]}));const ok=['dørmatte','skohylle','bordduk'].includes(word);return new MFResponse(JSON.stringify({choices:[{message:{content:JSON.stringify({norwegian:word!=='cup',familyFriendly:word!=='faen',safe:word!=='kniv',concreteLocal:ok,reason:ok?'Trygt norsk motiv.':'Ikke egnet for familiejakten.'})}}]}))}bank=b.response_format.json_schema.schema.properties.words.items.enum;return new MFResponse(JSON.stringify({choices:[{message:{content:JSON.stringify({words:['dørmatte','stein']})}}]}))}});
try{
const db=await mf.getD1Database('DB');for(const f of (await readdir('drizzle')).filter(p=>p.endsWith('.sql')).sort())for(const s of(await readFile('drizzle/'+f,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(s).run();
const now=Date.now(),h={};for(const user of ['admin','alice','bob','outsider']){await db.prepare('INSERT INTO members(id,name,email,status,joined,approved,admin) VALUES(?,?,?,?,?,?,?)').bind(user,user,user+'@test.invalid','approved',1,1,user==='admin'?1:0).run();await db.prepare('INSERT INTO login_sessions(token,user,expires) VALUES(?,?,?)').bind(crypto.createHash('sha256').update(user).digest('hex'),user,now+86400000).run();h[user]={cookie:'hunt_login='+user+(user==='admin'?'; hunt_admin=admin':''),'content-type':'application/json'};}
await db.prepare("INSERT INTO sessions(token,user,expires) VALUES('admin','admin',?)").bind(now+86400000).run();await db.prepare("INSERT INTO groups(id,name,owner,created) VALUES('g','Familien','alice',1)").run();for(const u of ['alice','bob'])await db.prepare("INSERT INTO group_members(group_id,user,joined) VALUES('g',?,1)").bind(u).run();
async function req(user,body,url='/api/hunt'){const r=await mf.dispatchFetch('https://test.invalid'+url,{method:body?'POST':'GET',headers:h[user]||{},...(body?{body:JSON.stringify(body)}:{})});let data;try{data=await r.json()}catch{}return {status:r.status,data}}
assert.equal((await req(null,null,'/api/extras?view=favorites')).status,401);
await db.prepare("INSERT INTO seasons(id,name,start) VALUES('s','Testsesong',?)").bind(now-100000).run();
for(const [id,slot,start,end] of [['h1',1,now-90000,now-50000],['h2',2,now-50000,now-1000]])await db.prepare('INSERT INTO challenges(id,season,title,start,end,duration,created,daily,day,slot) VALUES(?,?,?,?,?,?,?,1,?,?)').bind(id,'s','stein',start,end,end-start,start,'2026-10-02',slot).run();
for(const [id,user,hunt,elapsed,submitted] of [['a1','alice','h1',2000,now-70000],['b1','bob','h1',1000,now-60000],['a2','alice','h2',500,now-20000],['b2','bob','h2',2000,now-15000],['o2','outsider','h2',1,now-14000]]){await db.prepare('INSERT INTO submissions(id,challenge,user,key,submitted,elapsed,caption) VALUES(?,?,?,?,?,?,?)').bind(id,hunt,user,id,submitted,elapsed,'IDENTITY '+user).run();await(await mf.getR2Bucket('BUCKET')).put(id,'jpeg');}
let feed=(await req('alice')).data;assert(feed.summaries.length===2);let summary=feed.summaries.find(x=>x.id==='h2');assert.equal(summary.winner.id,'a2');assert.equal(summary.points,10);assert.equal(summary.before,2);assert.equal(summary.after,1);assert.equal(summary.change,1);
const before=JSON.stringify(feed.leaderboard);
let polls=(await req('alice',null,'/api/extras?view=favorites')).data.polls;assert.equal(polls.length,1);const poll=polls[0];assert.equal(poll.candidates.length,4);assert.equal(poll.closes-poll.opens,86400000);for(const c of poll.candidates)assert.deepEqual(Object.keys(c).sort(),['own','token']);assert(!JSON.stringify(poll).includes('IDENTITY'));assert(!JSON.stringify(poll).includes('bob'));
const own=poll.candidates.find(c=>c.own),other=poll.candidates.find(c=>!c.own);assert.equal((await req('alice',{action:'vote-favorite',token:own.token})).status,400);assert.equal((await req('outsider',{action:'vote-favorite',token:other.token})).status,403);assert.equal((await req('admin',{action:'vote-favorite',token:other.token})).status,403);assert.equal((await mf.dispatchFetch('https://test.invalid/api/favorite/'+other.token,{headers:h.outsider})).status,403);assert.equal((await mf.dispatchFetch('https://test.invalid/api/favorite/'+other.token,{headers:h.alice})).status,200);
assert.equal((await req('alice',{action:'vote-favorite',token:other.token})).status,200);assert.equal((await req('alice',{action:'vote-favorite',token:other.token})).status,409);assert.equal((await req('alice',null,'/api/extras?view=favorites')).data.polls[0].mine,other.token);assert.equal(JSON.stringify((await req('alice')).data.leaderboard),before);
assert.equal((await req('bob',{action:'caption',id:'a1',caption:'hacked'})).status,403);assert.equal((await req('alice',{action:'caption',id:'a1',caption:'Min nye tekst'})).status,200);assert.equal((await req('alice',{action:'caption',id:'a1',caption:'x'.repeat(121)})).status,400);assert.equal((await db.prepare("SELECT elapsed FROM submissions WHERE id='a1'").first()).elapsed,2000);assert.equal((await req('alice',null,'/api/hunt?profile=alice')).data.photos.find(p=>p.id==='a1').caption,'Min nye tekst');
assert.equal((await req('alice',{action:'suggest-word',word:'dørmatte'})).status,200);let w=(await req('admin',null,'/api/extras?view=words&admin=1')).data.words[0];assert.equal(w.status,'approved');assert.equal(w.ai_status,'approved');assert.equal((await req('bob',null,'/api/extras?view=words')).data.words.length,0);assert.equal((await req('alice',{action:'review-word',id:w.id,status:'approved'})).status,403);assert.equal((await req('alice',null,'/api/extras?view=words&admin=1')).status,403);assert.equal((await req('admin',{action:'review-word',id:w.id,status:'approved'})).status,200);assert.equal((await req('alice',null,'/api/extras?view=words')).data.words[0].status,'received');assert(!JSON.stringify((await req('alice',null,'/api/extras?view=words')).data).includes('dørmatte'));assert.equal((await req('bob',{action:'suggest-word',word:'disse fem ordene er ugyldige'})).status,400);
// The AI must explicitly pass every criterion; failures never enter the bank.
for(const word of ['cup','faen','kniv']){await db.prepare("DELETE FROM word_suggestions WHERE user='bob'").run();const rejected=await req('bob',{action:'suggest-word',word});assert.deepEqual(rejected.data,{ok:true});if(word!=='kniv')assert.equal((await db.prepare("SELECT status FROM word_suggestions WHERE user='bob'").first()).status,'rejected',word);}
for(const mode of ['offline','malformed']){aiMode=mode;await db.prepare("DELETE FROM word_suggestions WHERE user='bob'").run();assert.equal((await req('bob',{action:'suggest-word',word:mode==='offline'?'skohylle':'bordduk'})).data.ok,true);assert.equal((await db.prepare("SELECT status,ai_status FROM word_suggestions WHERE user='bob'").first()).ai_status,'pending');}aiMode='good';
await db.prepare("UPDATE word_suggestions SET created=1 WHERE user='bob'").run();const pending=await db.prepare("SELECT id FROM word_suggestions WHERE user='bob'").first();assert.equal((await req('bob',{action:'assess-word',id:pending.id})).status,403);assert.equal((await req('admin',{action:'assess-word',id:pending.id})).data.status,'approved');
assert.equal((await req('alice',{action:'suggest-feature',title:'Mørkere kamera',body:'En bedre kameraknapp.'})).status,200);assert.equal((await req('alice',{action:'suggest-feature',title:'Spam',body:'Spam'})).status,429);const feature=(await req('alice',null,'/api/extras?view=features')).data.suggestions[0];assert.equal((await req('bob',null,'/api/extras?view=features')).data.suggestions.length,0);assert.equal((await req('bob',null,'/api/extras?view=features&admin=1')).status,403);assert.equal((await req('alice',{action:'review-feature',id:feature.id,status:'done'})).status,403);assert.equal((await req('admin',{action:'review-feature',id:feature.id,status:'planned'})).status,200);assert.equal((await req('alice',null,'/api/extras?view=features')).data.suggestions[0].status,'planned');assert.equal((await req('admin',{action:'review-feature',id:feature.id,status:'bad'})).status,400);
const tomorrow=new Date(now+2*86400000).toISOString().slice(0,10);assert.equal((await req('admin',{action:'album',name:'Fremtid',first:tomorrow,last:tomorrow})).status,200);assert(bank.includes('dørmatte'));const future=await db.prepare("SELECT title FROM challenges WHERE start>? AND title='dørmatte'").bind(now).first();assert(future);assert(!JSON.stringify((await req('alice',null,'/api/extras?view=words')).data).includes(tomorrow));
await db.prepare("UPDATE seasons SET end=? WHERE id='s'").bind(now-1).run();await db.prepare("INSERT INTO reactions(id,submission,user,emoji) VALUES('r','a1','bob','❤️')").run();const season=(await req('alice',null,'/api/extras?view=seasons')).data.summaries.find(s=>s.id==='s');assert.equal(season.wins,1);assert.equal(season.longest,2);assert.equal(season.bestPlace,1);assert.equal(season.fastest.id,'a2');assert.equal(season.popular.id,'a1');assert.equal(season.popular.reactions,1);
assert.equal((await req('bob',{action:'vote-favorite',token:own.token})).status,200);
await db.prepare('UPDATE favorite_polls SET closes=? WHERE id=?').bind(now-1,poll.id).run();assert.equal((await req('bob',{action:'vote-favorite',token:own.token})).status,409);let closed=(await req('alice',null,'/api/extras?view=favorites')).data.polls[0];assert(closed.closed);assert.equal(closed.candidates.filter(c=>c.winner).length,2,'ties have joint winners');const winner=closed.candidates.find(c=>c.winner&&c.token===other.token);assert.equal(winner.token,other.token);assert.equal(winner.name,'bob');assert.equal(winner.votes,1);assert.equal(winner.caption,'IDENTITY bob');
// Existing membership is checked on every image read and vote, including after kåring.
await db.prepare("DELETE FROM group_members WHERE group_id='g' AND user='bob'").run();assert.equal((await mf.dispatchFetch('https://test.invalid/api/favorite/'+other.token,{headers:h.alice})).status,403);assert(!(await req('alice',null,'/api/extras?view=favorites')).data.polls[0].candidates.some(c=>c.token===other.token));assert.equal((await req('bob',null,'/api/extras?view=favorites')).data.polls.length,0);
// Both hunts must close before a poll is generated.
await db.prepare("INSERT INTO challenges(id,season,title,start,end,duration,created,daily,day,slot) VALUES('live','s','kopp',?,?,10000,?,1,'2026-10-03',2)").bind(now-1000,now+9000,now-1000).run();await db.prepare("INSERT INTO challenges(id,season,title,start,end,duration,created,daily,day,slot) VALUES('done','s','kopp',?,?,10000,?,1,'2026-10-03',1)").bind(now-11000,now-1000,now-11000).run();assert(!(await req('alice',null,'/api/extras?view=favorites')).data.polls.some(p=>p.day==='2026-10-03'));
console.log('PASS: summaries/rank movement, vote locking, exact 24h window, anonymous payload/image authorization, separate scores, caption ownership/time, moderated future words and private season statistics.');
}finally{await mf.dispose()}
