import {createRequire} from 'node:module';import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare}=wr('miniflare');
const mf=new Miniflare({modules:(await readdir('dist/server',{recursive:true})).filter(p=>p.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:0).map(p=>({type:'ESModule',path:path.resolve('dist/server',p)})),modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],cf:false});
try{
const db=await mf.getD1Database('DB');for(const migration of(await readdir('drizzle')).filter(p=>p.endsWith('.sql')).sort())for(const stmt of(await readFile('drizzle/'+migration,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(stmt).run();
const now=Date.now();for(const[id,status,isAdmin]of[['owner','approved',1],['alice','approved',0],['bob','approved',0],['outsider','approved',0],['pending','pending',0],['blocked','blocked',0]]){await db.prepare('INSERT INTO members(id,name,email,status,joined,approved,admin) VALUES(?,?,?,?,1,1,?)').bind(id,id,'',status,isAdmin).run();await db.prepare('INSERT INTO login_sessions(token,user,expires) VALUES(?,?,?)').bind(crypto.createHash('sha256').update(id).digest('hex'),id,now+86400000).run()}
await db.prepare("INSERT INTO sessions(token,user,expires) VALUES('pin','owner',?)").bind(now+86400000).run();await db.prepare("INSERT INTO groups(id,name,owner,created) VALUES('group','Private Group','alice',1)").run();for(const[id,role]of[['alice','member'],['bob','member']])await db.prepare("INSERT INTO group_members(group_id,user,role,joined) VALUES('group',?,?,1)").bind(id,role).run();
await db.prepare("INSERT INTO groups(id,name,owner,created) VALUES('foreign','Other private group','outsider',1)").run();await db.prepare("INSERT INTO group_members(group_id,user,joined) VALUES('foreign','outsider',1)").run();
await db.prepare("INSERT INTO seasons(id,name,start) VALUES('season','Current',?),('old','Old',?)").bind(now-3600000,now-7200000).run();
await db.prepare("INSERT INTO challenges(id,season,title,start,end,duration,created,daily) VALUES('hunt','season','Motiv',?,?,60000,?,1),('old-hunt','old','Old',?,?,60000,?,1)").bind(now-120000,now-60000,now-120000,now-7200000,now-7000000,now-7200000).run();
for(const [user,elapsed]of[['outsider',100],['alice',200],['bob',300],['blocked',50]])await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed) VALUES(?,'hunt',?,?,?,?)").bind('photo-'+user,user,'private/'+user,now-80000,elapsed).run();
await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed) VALUES('old-photo','old-hunt','bob','old-private',?,100)").bind(now-7100000).run();
async function req(user,body,query=''){const r=await mf.dispatchFetch('https://test.invalid/api/hunt'+query,{method:body?'POST':'GET',headers:{...(user?{cookie:'hunt_login='+user}:{}),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()}}
let view=await req('alice');assert.equal(view.status,200);assert.equal(view.data.scoreboardGroup,'all');assert.deepEqual(view.data.leaderboard.filter(x=>x.points).map(x=>[x.id,x.points]),[['outsider',10],['alice',7],['bob',5]],'global ranking includes everyone, excludes blocked');
assert.deepEqual(view.data.groupLeaderboards.group.map(x=>[x.id,x.points]),[['alice',10],['bob',7]],'group scores recalculate within group');assert(!view.data.groupLeaderboards.foreign,'private group scores unavailable');
assert.deepEqual(view.data.challenges.find(x=>x.id==='hunt').submissions.map(x=>x.user).sort(),['alice','bob'],'global scoreboard does not expose outsider photo');assert(!(await req('outsider')).data.groupLeaderboards.group);assert.equal((await req('owner')).data.groups.length,0,'admin account does not gain private group access');
assert.equal((await req('alice',{action:'leaderboard-filter',group:'foreign'})).status,403);assert.equal((await req('blocked',{action:'leaderboard-filter',group:'all'})).status,403);assert.equal((await req(null,{action:'leaderboard-filter',group:'all'})).status,401);
assert.equal((await req('alice',{action:'leaderboard-filter',group:'group'})).status,200);assert.equal((await req('alice')).data.scoreboardGroup,'group','filter persists on account');assert.equal((await req('bob')).data.scoreboardGroup,'all','filter is personal');
let old=await req('alice',undefined,'?season=old');assert.equal(old.data.scoreboardGroup,'group');assert.equal(old.data.groupLeaderboards.group[0].id,'bob');assert.equal(old.data.groupLeaderboards.group[0].points,10,'old album has own group score');
await db.prepare("DELETE FROM group_members WHERE group_id='group' AND user='alice'").run();view=await req('alice');assert.equal(view.data.scoreboardGroup,'all','revoked group filter falls back');assert(!view.data.groupLeaderboards.group);assert.equal((await req('alice',{action:'leaderboard-filter',group:'group'})).status,403);
assert.equal((await req('alice',{action:'leaderboard-filter',group:'all'})).status,200);assert.equal((await db.prepare("SELECT value FROM settings WHERE key='leaderboard_filter:alice'").first()).value,'all');
console.log('PASS: app-wide rankings, per-group scoring, saved personal filters, album switching, blocked accounts, revoked groups and unchanged photo/group privacy.');
}finally{await mf.dispose()}
