import {createRequire} from 'node:module';import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare}=wr('miniflare');
const mf=new Miniflare({modules:(await readdir('dist/server',{recursive:true})).filter(p=>p.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:0).map(p=>({type:'ESModule',path:path.resolve('dist/server',p)})),modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],cf:false});
try{
const db=await mf.getD1Database('DB'),r2=await mf.getR2Bucket('BUCKET');for(const migration of(await readdir('drizzle')).filter(p=>p.endsWith('.sql')).sort())for(const stmt of(await readFile('drizzle/'+migration,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(stmt).run();
const now=Date.now();for(const [id,status,admin]of[['owner','approved',1],['player','approved',0],['blocked','blocked',0]]){await db.prepare('INSERT INTO members(id,name,email,status,joined,approved,admin) VALUES(?,?,?,?,1,1,?)').bind(id,id,'',status,admin).run();await db.prepare('INSERT INTO login_sessions(token,user,expires) VALUES(?,?,?)').bind(crypto.createHash('sha256').update(id).digest('hex'),id,now+86400000).run()}
await db.prepare("INSERT INTO sessions(token,user,expires) VALUES('admin','owner',?)").bind(now+86400000).run();await db.prepare("INSERT INTO seasons(id,name,start) VALUES('s','Test',1)").run();
for(const[id,title,start,end]of[['active','mikroskop',now-60000,now+7200000],['future','hemmelig',now+3600000,now+7200000],['ended','ferdig',now-3600000,now-60000]])await db.prepare("INSERT INTO challenges(id,season,title,start,end,duration,created,daily) VALUES(?,'s',?,?,?,3600000,1,1)").bind(id,title,start,end).run();
await db.prepare("INSERT INTO starts(challenge,user,started) VALUES('active','owner',?)").bind(now-50000).run();await db.prepare("INSERT INTO captures(token,user,challenge,expires,issued) VALUES('old','owner','active',?,?)").bind(now+86400000,now-40000).run();await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed) VALUES('old','active','owner','photos/old.jpg',?,10000)").bind(now-30000).run();await r2.put('photos/old.jpg','old-photo');
await db.prepare("INSERT INTO comments(id,submission,user,body,created) VALUES('comment','old','player','test',1)").run();await db.prepare("INSERT INTO reactions(id,submission,user,emoji) VALUES('reaction','old','player','❤️')").run();await db.prepare("INSERT INTO settings(key,value) VALUES('push_disabled:player','1')").run();
async function req(user,body,url='/api/hunt'){const response=await mf.dispatchFetch('https://test.invalid'+url,{method:body?'POST':'GET',headers:{cookie:'hunt_login='+user+(user==='owner'?'; hunt_admin=admin':''),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});return{status:response.status,data:await response.json()}}
const change=(word,id='active',revision=0)=>({action:'replace-word',id,word,revision});assert.equal((await req('player',change('enkel'))).status,403);assert.equal((await req('owner',change('ferdig'))).status,400);assert.equal((await req('owner',change('mikroskop'))).status,400);assert.equal((await req('owner',change('enkel','active',5))).status,409);assert.equal((await db.prepare('SELECT COUNT(*) n FROM submissions').first()).n,1);
let result=await req('owner',change('enkel'));assert.equal(result.status,200,JSON.stringify(result));assert.equal(result.data.removed,1);const c=await db.prepare("SELECT * FROM challenges WHERE id='active'").first();assert.equal(c.title,'enkel');assert.equal(c.revision,1);assert.equal(c.end,now+7200000,'deadline unchanged');
for(const table of ['starts','captures','submissions','comments','reactions'])assert.equal((await db.prepare('SELECT COUNT(*) n FROM '+table).first()).n,0,table+' reset');assert.equal(await r2.get('photos/old.jpg'),null);assert.equal((await db.prepare('SELECT COUNT(*) n FROM hunt_changes').first()).n,2,'all approved players notified');
const inbox=await req('player',undefined,'/api/notifications');assert.equal(inbox.status,200);assert.equal(inbox.data.items[0].kind,'word-change');assert(inbox.data.items[0].detail.includes('vanskelighetsgraden'));assert(!JSON.stringify(inbox.data).includes('enkel'));assert(!JSON.stringify(inbox.data).includes('mikroskop'));assert.equal((await req('blocked',undefined,'/api/notifications')).status,403);
assert.equal((await req('owner',{action:'taken',token:'old'})).status,400,'old capture invalidated');assert.equal((await req('owner',{action:'start-daily',id:'active'})).status,200);let lease=await req('owner',{action:'camera',id:'active'});assert.equal(lease.status,200);assert.equal(lease.data.revision,1);
assert.equal((await req('owner',change('nytt','future'))).status,200);assert.equal((await db.prepare('SELECT COUNT(*) n FROM hunt_changes').first()).n,2,'future words stay silent');assert.equal((await req('owner',change('annet','ended'))).status,400);assert.equal((await req('owner',change('annet','active',0))).status,409);
// Admin proposes a secret replacement; only approved participants vote once.
const open=(word)=>({action:'open-difficulty-poll',id:'active',word,revision:1});assert.equal((await req('player',open('lampe'))).status,403);assert.equal((await req('owner',open('lampe'))).status,200);let poll=await db.prepare("SELECT * FROM difficulty_polls WHERE status='open'").first();assert.equal(poll.deadline-poll.created,3600000);assert.equal((await db.prepare("SELECT COUNT(*) n FROM hunt_changes WHERE kind='difficulty-poll' AND poll=?").bind(poll.id).first()).n,1);assert(!(await req('player',undefined,'/api/notifications')).data.items.some(n=>n.kind==='difficulty-poll'));assert.equal((await req('player')).data.difficultyPolls.length,0);assert.equal((await req('player',{action:'vote-difficulty',id:poll.id,choice:'replace'})).status,409);await db.prepare("INSERT INTO push_subscriptions(id,user,endpoint,p256dh,auth,created,updated) VALUES('player-device','player','https://fcm.googleapis.com/player','key','auth',1,1)").run();assert.equal((await req('player',{action:'start-daily',id:'active'})).status,200);assert((await req('player',undefined,'/api/notifications')).data.items.some(n=>n.kind==='difficulty-poll'));assert.equal((await db.prepare("SELECT COUNT(*) n FROM hunt_changes WHERE kind='difficulty-poll' AND poll=?").bind(poll.id).first()).n,2);assert.equal((await req('owner',open('stein'))).status,409);
let view=await req('player');assert.equal(view.data.difficultyPolls[0].id,poll.id);assert(!JSON.stringify(view.data.difficultyPolls).includes('lampe'),'replacement never exposed');
const vote=(choice)=>({action:'vote-difficulty',id:poll.id,choice});assert.equal((await req('player',vote('replace'))).status,200);assert.equal((await req('player',vote('keep'))).status,409);assert.equal((await req('blocked',vote('replace'))).status,403);assert.equal((await req('owner',vote('keep'))).status,200);
await db.prepare('UPDATE difficulty_polls SET deadline=? WHERE id=?').bind(now-1,poll.id).run();await req('owner');assert.equal((await db.prepare('SELECT status FROM difficulty_polls WHERE id=?').bind(poll.id).first()).status,'kept','tie keeps word');assert.equal((await db.prepare("SELECT revision FROM challenges WHERE id='active'").first()).revision,1);
assert.equal((await req('owner',open('lampe'))).status,200);poll=await db.prepare("SELECT * FROM difficulty_polls WHERE status='open'").first();assert.equal((await req('player',vote('replace'))).status,200);await db.prepare('UPDATE difficulty_polls SET deadline=? WHERE id=?').bind(now-1,poll.id).run();assert.equal((await req('owner',vote('keep'))).status,409,'late vote rejected after settlement');assert.equal((await db.prepare('SELECT status FROM difficulty_polls WHERE id=?').bind(poll.id).first()).status,'replaced');assert.equal((await db.prepare("SELECT title FROM challenges WHERE id='active'").first()).title,'lampe');assert.equal((await db.prepare("SELECT COUNT(*) n FROM starts WHERE challenge='active'").first()).n,0);
console.log('PASS: authorized word replacement, duplicate/stale/ended rejection, atomic image/comment/time reset, R2 cleanup, neutral bell notices with push off, blocked privacy, fresh lease and silent future replacement.');
}finally{await mf.dispose()}
