import {seedStaffAcceptance} from './helpers/staff.mjs';
import {createRequire} from 'node:module';import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare}=wr('miniflare'),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const mf=new Miniflare({modules:(await readdir('dist/server',{recursive:true})).filter(p=>p.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:0).map(p=>({type:'ESModule',path:path.resolve('dist/server',p)})),modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],cf:false});
try{const db=await mf.getD1Database('DB'),now=Date.now();for(const file of(await readdir('drizzle')).filter(x=>x.endsWith('.sql')).sort())for(const sql of(await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(sql).run();
for(const [id,admin,signed] of [['staff',1,true],['unsigned',1,false],['player',0,false],['photographer',0,false],['outside',0,false]]){await db.prepare("INSERT INTO members(id,name,email,status,joined,approved,admin) VALUES(?,?,?,'approved',1,1,?)").bind(id,id,'',admin).run();await db.prepare('INSERT INTO login_sessions(token,user,expires) VALUES(?,?,?)').bind(hash(id),id,now+86400000).run();if(admin)await db.prepare('INSERT INTO sessions(token,user,expires) VALUES(?,?,?)').bind(hash('admin-'+id),id,now+86400000).run();if(signed)await db.prepare('INSERT INTO settings(key,value) VALUES(?,?)').bind('admin-agreement:'+id,JSON.stringify({version:'2026-10-07.1',accepted:now})).run();if(signed)await seedStaffAcceptance(db,id,now)}
await db.prepare("INSERT INTO settings(key,value) VALUES('owner','staff')").run();
const req=(who,url,body)=>mf.dispatchFetch('https://test.invalid'+url,{method:body?'POST':'GET',headers:{cookie:'hunt_login='+who+'; hunt_admin=admin-'+who,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
await db.prepare("INSERT INTO chat_messages(id,room,user,body,created) VALUES('msg','public','photographer','Test',?)").bind(now-1000).run();await req('player','/api/chat',{action:'read',room:'public',id:'msg'});
for(const who of ['player','photographer','unsigned']){const chat=await(await req(who,'/api/chat?room=public')).json();assert(!Object.hasOwn(chat.messages[0],'readBy'));assert(!Object.hasOwn(chat.publicRoom.lastMessage,'readBy'));const summary=await(await req(who,'/api/chat?summary=1')).json();assert(!Object.hasOwn(summary.publicRoom.lastMessage,'readBy'))}
assert((await(await req('staff','/api/chat?room=public')).json()).messages[0].readBy.some(r=>r.id==='player'));
await db.prepare("INSERT INTO groups(id,name,owner,created) VALUES('g','Group','staff',1)").run();for(const who of ['staff','player','photographer'])await db.prepare("INSERT INTO group_members(group_id,user,joined) VALUES('g',?,1)").bind(who).run();await db.prepare("INSERT INTO seasons(id,name,start) VALUES('s','Synthetic',1)").run();await db.prepare("INSERT INTO challenges(id,season,title,details,start,end,duration,created,daily) VALUES('h','s','krus','Ta bilde av et drikkekrus.',?,?,3600000,1,1)").bind(now-1000,now+3600000).run();for(const [id,user] of [['p','photographer'],['own','player']])await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed,valid) VALUES(?,'h',?,?,?,1000,1)").bind(id,user,'photos/'+id,now).run();
await (await mf.getR2Bucket('BUCKET')).put('photos/p','synthetic image');
await db.prepare("INSERT INTO comments(id,submission,user,body,created) VALUES('hint','p','player','A secret motif hint',?)").bind(now).run();
await db.prepare("INSERT INTO reactions(id,submission,user,emoji) VALUES('reaction','p','player','♥')").run();
for(const who of ['staff','unsigned']){
 const feed=await(await req(who,'/api/hunt?season=s')).json(),hunt=feed.challenges.find(c=>c.id==='h');assert.equal(hunt.reveal,false);assert.equal(hunt.title,'Dagens hemmelige ord');assert.deepEqual(hunt.submissions,[]);assert(!feed.comments.some(c=>c.submission==='p'));assert(!feed.reactions.some(r=>r.submission==='p'));
 assert.equal((await req(who,'/api/photo/p')).status,403);const profile=await(await req(who,'/api/hunt?profile=photographer')).json();assert(!profile.photos.some(p=>p.id==='p'));assert(!profile.comments.some(c=>c.submission==='p'));
}
await db.prepare("INSERT INTO starts(challenge,user,started) VALUES('h','staff',?)").bind(now).run();assert.equal((await req('staff','/api/photo/p')).status,403,'revealing the word alone must not reveal other photos');
await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed,valid) VALUES('staff-own','h','staff','photos/staff',?,1000,1)").bind(now).run();assert.equal((await req('staff','/api/photo/p')).status,200);assert((await(await req('staff','/api/hunt?season=s')).json()).challenges.find(c=>c.id==='h').submissions.some(s=>s.id==='p'));assert((await(await req('staff','/api/hunt?profile=photographer')).json()).photos.some(p=>p.id==='p'));await db.prepare("DELETE FROM submissions WHERE id='staff-own'").run();
await db.prepare("INSERT INTO game_hunts(challenge,bonus) VALUES('h','Motivet har noe rødt') ON CONFLICT(challenge) DO UPDATE SET bonus=excluded.bonus").run();const unchangedPhoto=await db.prepare("SELECT * FROM submissions WHERE id='own'").first();
assert.equal((await req('staff','/api/privacy',{action:'bonus-request',id:'own'})).status,403,'even admin cannot opt in another player');
assert.equal((await req('player','/api/privacy',{action:'bonus-request',id:'missing'})).status,403);
for(let i=0;i<2;i++){const r=await req('player','/api/privacy',{action:'bonus-request',id:'own'});assert.equal(r.status,200);assert.equal((await r.json()).bonus.status,'manual')}
assert.deepEqual(await db.prepare("SELECT * FROM submissions WHERE id='own'").first(),unchangedPhoto,'post-delivery opt-in preserves the photo and original elapsed time');assert.equal((await db.prepare("SELECT COUNT(*) n FROM bonus_reviews WHERE submission='own'").first()).n,1);const opt=JSON.parse((await db.prepare("SELECT value FROM settings WHERE key='bonus-opt:own'").first()).value);assert.equal(opt.user,'player');assert.equal(opt.purpose,'bonus');assert(opt.created>=now);assert(opt.version);
assert.equal((await req('player','/api/privacy',{action:'bonus-withdraw',id:'own'})).status,200);assert.equal(await db.prepare("SELECT * FROM bonus_reviews WHERE submission='own'").first(),null);await db.prepare("UPDATE submissions SET valid=0 WHERE id='own'").run();assert.equal((await req('player','/api/privacy',{action:'bonus-request',id:'own'})).status,403);await db.prepare("UPDATE submissions SET valid=1 WHERE id='own'").run();
assert.equal((await req('player','/api/photo-reports',{id:'p',reason:' '})).status,400);assert.equal((await req('player','/api/photo-reports',{id:'own',reason:'Own'})).status,403);assert.equal((await req('outside','/api/photo-reports',{id:'p',reason:'Outside'})).status,403);
await db.prepare("INSERT INTO photo_reports(submission,reporter,reason,created,deadline,status,threshold) VALUES('p','staff','Existing vote',?,?,'open',3)").bind(now,now+3600000).run();assert.equal((await req('player','/api/photo-reports',{id:'p',reason:'Bildet viser ikke et krus.'})).status,200);assert.equal((await req('player','/api/photo-reports',{id:'p',reason:'Duplicate'})).status,409);
assert.equal((await req('player','/api/photo-reports')).status,403);assert.equal((await req('unsigned','/api/photo-reports')).status,403);const lockedQueue=await(await req('staff','/api/photo-reports')).json();assert.equal(lockedQueue.reports.length,0,'admin fairness gate hides active report context');assert.equal(lockedQueue.lockedReports.length,1,'locked report remains visible as a receipt');assert.equal(lockedQueue.total,1,'direct and voting records do not duplicate the same photo');assert(!JSON.stringify(lockedQueue.lockedReports).includes('krus'));assert(!JSON.stringify(lockedQueue.lockedReports).includes('reportReason'));await db.prepare("UPDATE challenges SET end=? WHERE id='h'").bind(now-1).run();let reports=(await(await req('staff','/api/photo-reports')).json()).reports;assert.equal(reports.length,1);assert.equal(reports[0].title,'krus');assert.equal(reports[0].details,'Ta bilde av et drikkekrus.');assert.equal(reports[0].reportReason,'Bildet viser ikke et krus.');
assert.equal((await req('player','/api/privacy',{action:'bonus-request',id:'own'})).status,200,'can opt in after hunt end');assert.equal((await req('staff','/api/hunt',{action:'review-bonus',id:'own',status:'approved',reason:'Bonuskravet er oppfylt.'})).status,200);assert.equal((await(await req('player','/api/privacy',{action:'bonus-request',id:'own'})).json()).bonus.status,'approved','duplicate opt-in cannot reset an admin decision');assert.deepEqual(await db.prepare("SELECT * FROM submissions WHERE id='own'").first(),unchangedPhoto);
const verdict={id:'p',valid:false,category:'word',reason:'Motivet mangler krus.',expectedValid:true,expectedNote:''};assert.equal((await req('staff','/api/admin-submissions',verdict)).status,200);assert.equal((await db.prepare("SELECT status FROM photo_admin_reports WHERE submission='p'").first()).status,'resolved');assert.equal((await(await req('staff','/api/photo-reports')).json()).reports.length,0);assert.equal((await db.prepare("SELECT elapsed FROM submissions WHERE id='p'").first()).elapsed,1000);assert.equal((await req('staff','/api/admin-submissions',verdict)).status,409);
assert.equal((await req('staff','/api/admin-submissions',{id:'p',valid:true,category:'restore',reason:'Ny vurdering viser riktig motiv.',expectedValid:false,expectedNote:'Passer ikke ordet: Motivet mangler krus.'})).status,200);assert.equal((await db.prepare("SELECT valid FROM submissions WHERE id='p'").first()).valid,1);
assert.equal((await req('outside','/api/photo-reports?context=p')).status,403);const context=await(await req('player','/api/photo-reports?context=p')).json();assert.equal(context.title,'krus');assert.equal(context.details,'Ta bilde av et drikkekrus.');
await db.prepare("INSERT INTO challenges(id,season,title,details,start,end,duration,created,daily) SELECT 'legacy-h',season,title,details,start,end,duration,created,daily FROM challenges WHERE id='h'").run();await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed,valid) VALUES('legacy-p','legacy-h','photographer','legacy.jpg',?,1000,1)").bind(now).run();await db.prepare("INSERT INTO photo_reports(submission,reporter,reason,created,deadline,status,threshold) VALUES('legacy-p','player','Legacy client report',?,?,'valid',3)").bind(now,now).run();
const legacyQueue=(await(await req('staff','/api/photo-reports')).json()).reports;assert.equal(legacyQueue.length,1,'legacy vote reports are available without a direct-admin record');assert.equal(legacyQueue[0].source,'vote');assert.equal(legacyQueue[0].reportReason,'Legacy client report');assert.equal(legacyQueue[0].title,'krus');assert.equal((await req('staff','/api/admin-submissions',{id:'legacy-p',valid:true,category:'restore',reason:'Bildet passer.',expectedValid:true,expectedNote:''})).status,200);assert.equal((await(await req('staff','/api/photo-reports')).json()).reports.length,0,'admin decision clears legacy queue');
await db.prepare("INSERT INTO chat_messages(id,room,user,body,created) VALUES('group-msg','g','photographer','Private group message',?)").bind(now-500).run();await req('player','/api/chat',{action:'read',room:'g',id:'group-msg'});assert((await(await req('photographer','/api/chat?room=g')).json()).messages[0].readBy.some(r=>r.id==='player'),'private group receipts remain available');
await db.prepare("INSERT INTO groups(id,name,owner,created) VALUES('g2','Overlapping group','staff',1)").run();for(const who of ['staff','player','unsigned'])await db.prepare("INSERT INTO group_members(group_id,user,joined) VALUES('g2',?,1)").bind(who).run();
let boards=await(await req('staff','/api/hunt?season=s')).json();assert.deepEqual(boards.myGroupsLeaderboard.map(m=>m.id).sort(),['photographer','player','staff','unsigned']);assert.equal(new Set(boards.myGroupsLeaderboard.map(m=>m.id)).size,4);assert.equal(boards.myGroupsLeaderboard.find(m=>m.id==='player').points,12,'overlapping groups do not multiply normal or bonus points');assert(!boards.myGroupsLeaderboard.some(m=>m.id==='outside'));
for(const group of ['my-groups','lightning','g','all']){assert.equal((await req('staff','/api/hunt',{action:'leaderboard-filter',group})).status,200);assert.equal((await(await req('staff','/api/hunt?season=s')).json()).scoreboardGroup,group)}assert.equal((await req('outside','/api/hunt',{action:'leaderboard-filter',group:'g'})).status,403);assert.deepEqual((await(await req('outside','/api/hunt?season=s')).json()).myGroupsLeaderboard,[]);
await db.prepare("INSERT INTO challenges(id,season,title,details,start,end,duration,created,daily) VALUES('lightning:test','s','stein','Lynjakt',?,?,1000,1,0)").bind(now-3000,now-1000).run();await db.prepare("INSERT INTO game_hunts(challenge,lightning) VALUES('lightning:test',1)").run();for(const [id,user,elapsed] of [['light-fast','staff',1000],['light-slow','unsigned',2000]])await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed,valid) VALUES(?,'lightning:test',?,?,?, ?,1)").bind(id,user,'photos/'+id,now-1500,elapsed).run();boards=await(await req('staff','/api/hunt?season=s')).json();assert.equal(boards.lightningBoard.find(m=>m.id==='staff').points,3);assert.equal(boards.lightningBoard.find(m=>m.id==='unsigned').points,1);assert(!boards.lightningBoard.some(m=>m.id==='player'),'normal hunt scores do not enter lightning board');
console.log('PASS: admin privacy and hunt gates, photo reports and decisions, post-delivery bonus requests and withdrawals, preserved photo/time, idempotent requests and decisions, union group ranking without duplicates, persisted special filters, private group denial and separate lightning points.');
}finally{await mf.dispose()}
