import {seedStaffAcceptance} from './helpers/staff.mjs';
import {createRequire} from 'node:module';import {readFile,readdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare,Response:MFResponse}=wr('miniflare');let bank=[],aiMode='good';
const mf=new Miniflare({modules:(await readdir('dist/server',{recursive:true})).filter(p=>p.endsWith('.js')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:0).map(p=>({type:'ESModule',path:path.resolve('dist/server',p)})),modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],bindings:{ADMIN_PIN:'9752',OPENAI_API_KEY:'fake'},cf:false,outboundService:async req=>{const b=await req.json();if(b.response_format.json_schema.name==='safe_norwegian_word'){assert.equal(b.store,false);assert(b.messages[0].content.includes('Ved tvil'));const word=JSON.parse(b.messages[1].content).word;if(aiMode==='offline')return new MFResponse('{}',{status:503});if(aiMode==='malformed')return new MFResponse(JSON.stringify({choices:[{message:{content:'{}'}}]}));assert(b.messages[0].content.includes('laptop'));assert(b.messages[0].content.includes('gult hus'));const ok=aiMode!=='reject'&&['dørmatte','skohylle','bordduk','gult hus','laptop'].includes(word);return new MFResponse(JSON.stringify({choices:[{message:{content:JSON.stringify({norwegian:word!=='cup',familyFriendly:word!=='faen',safe:word!=='kniv',concreteLocal:ok,reason:ok?'Trygt norsk motiv.':'Ikke egnet for familiejakten.'})}}]}))}bank=b.response_format.json_schema.schema.properties.words.items.enum;return new MFResponse(JSON.stringify({choices:[{message:{content:JSON.stringify({words:['dørmatte','stein']})}}]}))}});
try{
const db=await mf.getD1Database('DB');for(const f of (await readdir('drizzle')).filter(p=>p.endsWith('.sql')).sort())for(const s of(await readFile('drizzle/'+f,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(s).run();
const now=Date.now(),headers={};for(const user of ['admin','alice','bob']){await db.prepare('INSERT INTO members(id,name,email,status,joined,approved,admin) VALUES(?,?,?,?,?,?,?)').bind(user,user,'','approved',1,1,user==='admin'?1:0).run();await db.prepare('INSERT INTO login_sessions(token,user,expires) VALUES(?,?,?)').bind(crypto.createHash('sha256').update(user).digest('hex'),user,now+86400000).run();headers[user]={cookie:'hunt_login='+user+(user==='admin'?'; hunt_admin=admin':''),'content-type':'application/json'}}
await db.prepare("INSERT INTO sessions(token,user,expires) VALUES('8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918','admin',?)").bind(now+86400000).run();
await seedStaffAcceptance(db,'admin',now);await db.prepare("INSERT OR REPLACE INTO settings(key,value) VALUES('owner',?)").bind('admin').run();
await db.prepare("INSERT OR IGNORE INTO rules_acceptances(user_id,rules_version,accepted_at) SELECT id,'2026-10-07.1',1 FROM members").run();
async function req(user,body,url='/api/hunt'){const r=await mf.dispatchFetch('https://test.invalid'+url,{method:body?'POST':'GET',headers:headers[user],...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()}}
await db.prepare("INSERT INTO seasons(id,name,start) VALUES('s','Test',1)").run();
for(let i=0;i<5;i++){const start=now+(i+1)*86400000;await db.prepare('INSERT INTO challenges(id,season,title,start,end,duration,created,daily,day,slot) VALUES(?,?,?,?,?,?,?,1,?,1)').bind('h'+i,'s',i===3?'gulvmatte':'kopp'+i,start,start+1000,1000,now,'2026-10-'+(10+i)).run()}
await db.prepare("INSERT INTO starts(challenge,user,started) VALUES('h0','alice',?)").bind(now).run();
for(const [id,word,ai] of [['w1','bilsete','approved'],['w2','stekepanne','approved'],['w3','gulvmatte','approved'],['w4','usikkert','pending']])await db.prepare('INSERT INTO word_suggestions(id,user,word,status,created,ai_status,ai_reason) VALUES(?,?,?,?,?,?,?)').bind(id,'alice',word,'approved',now,ai,'PRIVATE '+word).run();
const before=await db.prepare('SELECT id,title FROM challenges ORDER BY id').all();await req('alice');const after=(await db.prepare('SELECT id,title FROM challenges ORDER BY id').all()).results;
assert.equal(after.find(c=>c.id==='h0').title,'kopp0','existing start prevents replacement');assert.equal(after.filter(c=>c.title==='bilsete').length,1);assert.equal(after.filter(c=>c.title==='stekepanne').length,1);assert.equal(after.filter(c=>c.title==='gulvmatte').length,1,'already scheduled word not repeated');assert(!after.some(c=>c.title==='usikkert'));
await req('alice');assert.deepEqual((await db.prepare('SELECT id,title FROM challenges ORDER BY id').all()).results,after,'repeated reads are idempotent');
const publicWords=(await req('alice',null,'/api/extras?view=words')).data;assert.equal(publicWords.words.length,4);assert(publicWords.words.every(w=>Object.keys(w).sort().join(',')==='created,id,status'));assert(!JSON.stringify(publicWords).includes('approved'));assert(!JSON.stringify(publicWords).includes('PRIVATE'));assert(!JSON.stringify(publicWords).includes('bilsete'));
const adminWords=(await req('admin',null,'/api/extras?view=words&admin=1')).data;assert(adminWords.words.some(w=>w.word==='bilsete'));
for(const word of ['BILSETE',' gulvmatte ','kopp']){await db.prepare("UPDATE word_suggestions SET created=1 WHERE user='bob'").run();const r=await req('bob',{action:'suggest-word',word});assert.equal(r.status,200);assert.deepEqual(r.data,{ok:true,created:true});assert.equal((await db.prepare("SELECT COUNT(*) n FROM word_suggestions WHERE user='bob' AND word=?").bind(word.trim().toLowerCase()).first()).n,1,'each player keeps a private receipt, including words suggested by others')}
await db.prepare("UPDATE word_suggestions SET created=1 WHERE user='bob'").run();const submitted=await req('bob',{action:'suggest-word',word:'dørmatte'});assert.deepEqual(submitted.data,{ok:true,created:true});const receipt=(await req('bob',null,'/api/extras?view=words')).data.words[0];assert.equal(receipt.status,'received');assert(!('word' in receipt));assert(!('ai_reason' in receipt));await req('bob');const later=(await db.prepare('SELECT id,title FROM challenges').all()).results;assert.equal(later.filter(c=>c.title==='bilsete').length,1,'new suggestions preserve previous replacements');assert.equal(later.filter(c=>c.title==='stekepanne').length,1);
// Short phrases, common loanwords and an explicit administrator override.
for(const word of ['Gult   hus','laptop']){await db.prepare('UPDATE word_suggestions SET created=1').run();assert.equal((await req('bob',{action:'suggest-word',word})).status,200);const normalized=word.toLowerCase().replace(/\s+/g,' ');const row=await db.prepare('SELECT * FROM word_suggestions WHERE word=?').bind(normalized).first();assert.equal(row.status,'approved');assert.equal(row.ai_status,'approved')}
await db.prepare('UPDATE word_suggestions SET created=1').run();const total=(await db.prepare('SELECT COUNT(*) n FROM word_suggestions').first()).n;assert.equal((await req('alice',{action:'suggest-word',word:' GULT  HUS '})).status,200);assert.equal((await db.prepare('SELECT COUNT(*) n FROM word_suggestions').first()).n,total+1,'another player keeps their own normalized phrase receipt');
assert.equal((await req('bob',{action:'suggest-word',word:'dette har mer enn fire ord'})).status,400);
aiMode='reject';await db.prepare('UPDATE word_suggestions SET created=1').run();await req('bob',{action:'suggest-word',word:'gamingstol'});let declined=await db.prepare("SELECT * FROM word_suggestions WHERE word='gamingstol'").first();assert.equal(declined.status,'rejected');
assert.equal((await req('bob',{action:'review-word',id:declined.id,status:'approved'})).status,403,'only admin can override');
let review=await req('admin',{action:'review-word',id:declined.id,status:'approved'});assert.equal(review.data.manual,true);declined=await db.prepare("SELECT * FROM word_suggestions WHERE word='gamingstol'").first();assert.equal(declined.status,'admin-approved');assert.equal(declined.ai_status,'rejected','AI verdict remains separately visible');
await req('admin',{action:'review-word',id:declined.id,status:'assess'});assert.equal((await db.prepare('SELECT status FROM word_suggestions WHERE id=?').bind(declined.id).first()).status,'admin-approved','AI cannot revoke manual approval');
aiMode='offline';await req('admin',{action:'review-word',id:declined.id,status:'assess'});assert.equal((await db.prepare('SELECT status FROM word_suggestions WHERE id=?').bind(declined.id).first()).status,'admin-approved','unavailable AI cannot revoke manual approval');aiMode='good';
for(let i=5;i<9;i++)await db.prepare('INSERT INTO challenges(id,season,title,start,end,duration,created,daily,day,slot) VALUES(?,?,?,?,?,?,?,1,?,1)').bind('h'+i,'s','reserved'+i,now+i*86400000,now+i*86400000+1000,1000,now,'2026-10-'+(10+i)).run();
await req('alice');for(const title of ['gult hus','laptop','gamingstol'])assert.equal((await db.prepare('SELECT COUNT(*) n FROM challenges WHERE title=?').bind(title).first()).n,1,'AI/manual approvals enter future hunts once');
const hidden=JSON.stringify((await req('bob',null,'/api/extras?view=words')).data);for(const secret of ['gamingstol','gult hus','laptop','admin-approved','ai_reason'])assert(!hidden.includes(secret),'ordinary members never see words or verdicts');
await req('admin',{action:'review-word',id:declined.id,status:'rejected'});assert.equal((await db.prepare('SELECT status FROM word_suggestions WHERE id=?').bind(declined.id).first()).status,'rejected');
console.log('PASS: phrases/loanwords, normalized private duplicates, AI/manual approvals, admin-only override, manual approval survives AI rejection/outage, secret and idempotent future scheduling.');
}finally{await mf.dispose()}
