import {seedStaffAcceptance} from './helpers/staff.mjs';
import {createRequire} from 'node:module';
import {readFile,readdir} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler/package.json')),{Miniflare}=wr('miniflare'),hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const root=path.resolve('dist/server'),modules=(await readdir(root,{recursive:true})).filter(p=>p.endsWith('.js')).map(p=>({type:'ESModule',path:path.join(root,p)}));
modules.unshift({type:'ESModule',path:path.join(root,'window-clock.js'),contents:"import handler from './index.js';let now=0;Date.now=()=>now;export default {fetch(req,env,ctx){now=Number(new URL(req.url).searchParams.get('clock'));return handler.fetch(req,env,ctx)}}"});
const mf=new Miniflare({modules,modulesRoot:root,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],cf:false,outboundService:async()=>{throw Error('Unexpected outbound request')}});
try{
 const db=await mf.getD1Database('DB'),bucket=await mf.getR2Bucket('BUCKET'),jpeg=await readFile('tests/fixtures/metadata.jpg');let now=Date.parse('2026-10-09T15:30:00Z');
 for(const file of(await readdir('drizzle')).filter(x=>x.endsWith('.sql')).sort())for(const sql of(await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint').map(x=>x.trim()).filter(Boolean))await db.prepare(sql).run();
 for(const [id,admin,role] of [['owner',1,null],['admin',1,null],['judge',0,'judge'],['head',0,'head_judge'],['player',0,null],['other',0,null]]){
  await db.prepare("INSERT INTO members(id,name,email,status,joined,approved,admin) VALUES(?,?,'','approved',1,1,?)").bind(id,id,admin).run();
  await db.prepare('INSERT INTO login_sessions(token,user,expires) VALUES(?,?,?)').bind(hash(id),id,now+86400000).run();await db.prepare('INSERT INTO sessions(token,user,expires) VALUES(?,?,?)').bind(hash('admin-'+id),id,now+86400000).run();if(role)await db.prepare('INSERT INTO staff_roles(user,role,updated,actor) VALUES(?,?,1,?)').bind(id,role,'owner').run();if(admin||role)await seedStaffAcceptance(db,id,now);
 }
 await db.prepare("INSERT INTO settings(key,value) VALUES('owner','owner')").run();await db.prepare("INSERT INTO seasons(id,name,start) VALUES('s','Synthetic',1)").run();
 for(const [id,start,end] of [['ended',now-100000,now-1000],['future',now+100000,now+200000]])await db.prepare('INSERT INTO challenges(id,season,title,details,start,end,duration,created,daily) VALUES(?,?,?,?,?,?,?,?,0)').bind(id,'s','Synthetic yellow house','Test',start,end,end-start,1).run();
 await db.prepare("INSERT INTO submissions(id,challenge,user,key,submitted,elapsed,valid) VALUES('old','ended','player','photos/old',?,12345,1)").bind(now-2000).run();await bucket.put('photos/old',jpeg);
 const req=async(who,url,body,headers={})=>{let data=body?JSON.stringify(body):undefined,contentType=body?'application/json':undefined;if(body instanceof FormData){const encoded=new Response(body);contentType=encoded.headers.get('content-type');data=new Uint8Array(await encoded.arrayBuffer())}const r=await mf.dispatchFetch('https://test.invalid'+url+(url.includes('?')?'&':'?')+'clock='+now,{method:body?'POST':'GET',headers:{cookie:'hunt_login='+who+'; hunt_admin=admin-'+who,...(contentType?{'Content-Type':contentType}:{}),...headers},body:data});return {status:r.status,data:await r.json()}};
 const open=who=>req(who,'/api/admin-submissions',{action:'open-delivery',challenge:'ended',user:'player'});
 const camera=async()=>{const r=await req('player','/api/hunt',{action:'camera',id:'ended'});assert.equal(r.status,200,JSON.stringify(r));return r.data};
 const photoForm=(cap,bad=false)=>{const f=new FormData();f.set('challenge','ended');f.set('token',cap.token);f.set('taken',String(now));f.set('photo',new Blob([bad?new Uint8Array(1):jpeg],{type:'image/jpeg'}),'photo.jpg');return f};
 const current=()=>db.prepare("SELECT * FROM submissions WHERE challenge='ended' AND user='player'").first();
 for(const who of ['admin','judge','head','player','other'])assert.equal((await open(who)).status,403,'owner-only reopening');assert.equal((await req('owner','/api/admin-submissions',{action:'open-delivery',challenge:'future',user:'player'})).status,400,'future word cannot be opened');assert.equal((await req('owner','/api/admin-submissions',{action:'open-delivery',challenge:'ended',user:'player'},{origin:'https://evil.invalid'})).status,403);
 assert.equal((await req('player','/api/hunt',{action:'camera',id:'ended'})).status,400);
 const granted=await open('owner');assert.equal(granted.status,200,JSON.stringify(granted));assert.equal(granted.data.expires,now+600000);assert.equal((await current()).id,'old');assert(await bucket.get('photos/old'));
 const own=(await req('player','/api/hunt?season=s')).data.challenges.find(c=>c.id==='ended');assert.equal(own.reopen.expires,granted.data.expires);assert.equal(own.end,now-1000,'global deadline unchanged');assert.equal(own.own.id,'old');assert.equal(own.available,true);
 assert.equal((await req('other','/api/hunt?season=s')).data.challenges.find(c=>c.id==='ended').reopen,null,'only selected participant sees permission');assert.equal((await req('other','/api/hunt',{action:'camera',id:'ended'})).status,400);
 const cap=await camera();assert.equal(cap.end,granted.data.expires);assert.equal((await req('other','/api/hunt',photoForm(cap))).status,400,'camera bound to participant');assert.equal((await req('player','/api/hunt',photoForm(cap,true))).status,400);assert.equal((await current()).id,'old');assert(await bucket.get('photos/old'));
 now=granted.data.expires;assert.equal((await req('player','/api/hunt',photoForm(cap))).status,409,'strict ten minute expiry');assert.equal((await current()).id,'old');assert(await bucket.get('photos/old'));
 const again=await open('owner');assert.equal(again.status,200);assert.equal((await req('player','/api/hunt',photoForm(cap))).status,409,'previous window cannot be reused');
 const a=await camera(),b=await camera();now+=1000;const results=await Promise.all([a,b].map(c=>req('player','/api/hunt',photoForm(c))));assert.deepEqual(results.map(r=>r.status).sort(),[200,409],JSON.stringify(results));
 const saved=await current();assert([a.token,b.token].includes(saved.id));assert.equal(saved.elapsed,now-(Date.parse('2026-10-09T15:30:00Z')-100000));assert.equal(await bucket.get('photos/old'),null);assert(await bucket.get(saved.key));assert.equal((await bucket.list()).objects.length,1,'only winning object survives');
 assert.equal((await db.prepare("SELECT COUNT(*) n FROM submissions WHERE challenge='ended' AND user='player'").first()).n,1);assert.equal((await req('player','/api/hunt?season=s')).data.challenges.find(c=>c.id==='ended').reopen,null,'one successful delivery consumes grant');
 const winner=[a,b].find(c=>c.token===saved.id);now+=600001;const retry=await req('player','/api/hunt',photoForm(winner));assert.equal(retry.status,200,'lost success response can be retried after expiry');assert.equal(retry.data.elapsed,saved.elapsed);assert.equal((await req('player','/api/hunt',{action:'camera',id:'ended'})).status,400,'no additional delivery');
 const correction={action:'correct-time',id:saved.id,seconds:23.583,reason:'Documented original time',expectedElapsed:saved.elapsed,expectedValid:true,expectedNote:''};for(const who of ['admin','judge','head','player'])assert.equal((await req(who,'/api/admin-submissions',correction)).status,403);assert.equal((await req('owner','/api/admin-submissions',correction)).status,200);assert.equal((await current()).elapsed,23583);assert.equal((await req('owner','/api/admin-submissions',correction)).status,409,'stale correction blocked');assert.equal((await current()).valid,1);
 assert.equal((await req('owner','/api/admin-submissions',{...correction,seconds:NaN})).status,400);
 // A closed daily hunt still preserves the player's original opening time.
 const morningStart=Date.parse('2026-10-09T04:00:00Z'),morningEnd=Date.parse('2026-10-09T15:00:00Z'),originalStart=morningEnd-300000;
 await db.prepare("INSERT INTO challenges(id,season,title,details,start,end,duration,created,daily,day,slot) VALUES('daily','s','Synthetic house','Test',?,?,39600000,1,1,'2026-10-09',1)").bind(morningStart,morningEnd).run();await db.prepare("INSERT INTO starts(challenge,user,started) VALUES('daily','player',?)").bind(originalStart).run();
 assert.equal((await req('owner','/api/admin-submissions',{action:'open-delivery',challenge:'daily',user:'player'})).status,200);const dailyCap=(await req('player','/api/hunt',{action:'camera',id:'daily'})).data;assert.equal(dailyCap.started,originalStart);now+=1000;assert.equal((await req('player','/api/hunt',{action:'taken',token:dailyCap.token})).status,200);
 const dailyForm=photoForm(dailyCap);dailyForm.set('challenge','daily');const dailyUpload=await req('player','/api/hunt',dailyForm);assert.equal(dailyUpload.status,200,JSON.stringify(dailyUpload));assert.equal(dailyUpload.data.elapsed,now-originalStart);assert.equal((await db.prepare("SELECT started FROM starts WHERE challenge='daily' AND user='player'").first()).started,originalStart);
 // A participant with no earlier delivery may also use the individual window.
 assert.equal((await req('owner','/api/admin-submissions',{action:'open-delivery',challenge:'ended',user:'other'})).status,200);const firstCamera=await req('other','/api/hunt',{action:'camera',id:'ended'});assert.equal(firstCamera.status,200);const firstDelivery=await req('other','/api/hunt',photoForm(firstCamera.data));assert.equal(firstDelivery.status,200,JSON.stringify(firstDelivery));
 console.log('PASS: owner-only 10-minute delivery; participant isolation; future secrecy; unchanged global deadline; original retained on failure/expiry; window-bound camera; atomic concurrent replacement; object cleanup; idempotent retry; one-time permission; precise owner time correction with stale-write protection.');
}finally{await mf.dispose()}
