import {roleFor} from '@/lib/staff';
import {removePushDevices} from '@/lib/push-cleanup';
import {hasAdminPassword,verifyAdminPassword} from '@/lib/admin-auth';
import {username} from '@/lib/groups';
import {env} from 'cloudflare:workers';
import {cookies} from 'next/headers';
import {currentUser,loginToken,digest,loginName,pinHash,validatePin,limit,session,owner} from '@/lib/auth';
import {admin,siteOwner,one,all,run,db,origin,wrap,json,fail,str} from '@/lib/server';
export const dynamic='force-dynamic';
export const POST=wrap(async(req:Request)=>{origin(req);const b:any=await req.json();const now=Date.now();
if(b.action==='logout'){const u=await currentUser();const jar=await cookies();if(u&&typeof (b.endpoint||b.token)==='string')await removePushDevices(u.userId,b.endpoint||b.token);const token=await loginToken();if(token)await run('DELETE FROM login_sessions WHERE token=?',await digest(token));const a=jar.get('hunt_admin')?.value;if(a)await run('DELETE FROM sessions WHERE token=?',await digest(a));const h=new Headers({'Cache-Control':'no-store','Content-Type':'application/json'});for(const c of ['hunt_login','hunt_admin'])h.append('Set-Cookie',`${c}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`);return new Response('{"ok":true}',{headers:h})}
if(b.action==='admin-password'){const u=await admin(req),salt=crypto.randomUUID();if(typeof b.password!=='string'||b.password.length<12||b.password.length>128)fail('Velg et personlig administratorpassord med 12–128 tegn.');await db().batch([db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('admin-credential:'+u.userId,JSON.stringify({salt,hash:await pinHash(b.password,salt),updated:now})),db().prepare('DELETE FROM sessions WHERE user=?').bind(u.userId),db().prepare('DELETE FROM login_sessions WHERE user=?').bind(u.userId)]);return session(u.userId,true,b.client==='native')}
if(b.action==='pin'){await limit(req,'admin',12);const id=await owner();if(await verifyAdminPassword(id,b.password||b.pin,b.code))return session(id,true,b.client==='native');if(!(env as any).ADMIN_PIN||b.pin!==String((env as any).ADMIN_PIN))fail('Feil PIN.',403);return session(await owner(),true,b.client==='native')}
if(b.action==='set-pin'){await siteOwner(req);const m=await one('SELECT * FROM members WHERE id=? AND admin=0',b.id);if(!m)fail('Fant ikke medlemmet.');const existing=await one('SELECT login FROM local_accounts WHERE user=?',m.id);const login=existing?.login||loginName(b.name||m.name);const collision=await one('SELECT user FROM local_accounts WHERE login=? AND user<>?',login,m.id);if(collision)fail('Navnet er i bruk. Velg et annet innloggingsnavn.');const salt=crypto.randomUUID(),hash=await pinHash(validatePin(b.pin),salt);await db().batch([db().prepare('INSERT INTO local_accounts(user,login,salt,hash) VALUES (?,?,?,?) ON CONFLICT(user) DO UPDATE SET salt=excluded.salt,hash=excluded.hash').bind(m.id,login,salt,hash),db().prepare('DELETE FROM login_sessions WHERE user=?').bind(m.id),db().prepare('DELETE FROM push_subscriptions WHERE user=?').bind(m.id)]);return json({ok:true,login})}
if(!['register','login'].includes(b.action))fail('Ukjent handling.');const login=b.action==='register'?username(b.username):loginName(b.name);await limit(req,'name:'+login);await limit(req,'ip:'+(req.headers.get('cf-connecting-ip')||'shared'),60);if(b.action==='login'){const selected=(await one("SELECT value FROM settings WHERE key='owner'"))?.value||(await one('SELECT id FROM members WHERE admin=1 ORDER BY joined LIMIT 1'))?.id;const administrator=selected&&await one('SELECT name,username FROM members WHERE id=? AND admin=1',selected);if(administrator&&[administrator.name,administrator.username].some(v=>typeof v==='string'&&v.normalize('NFKC').toLocaleLowerCase('nb-NO')===login)&&await hasAdminPassword(selected)){await limit(req,'admin',12);await verifyAdminPassword(selected,b.password||b.pin,b.code);return session(selected,true,b.client==='native');}}
if(b.action==='login'){const candidate=await one('SELECT a.user FROM local_accounts a JOIN members m ON m.id=a.user WHERE (a.login=? OR m.username=?) AND m.status=?',login,login,'approved');if(candidate&&await roleFor(candidate.user)!=='player'&&await hasAdminPassword(candidate.user)){await verifyAdminPassword(candidate.user,b.password||b.pin,b.code);return session(candidate.user,true,b.client==='native');}}
if(b.action==='login'&&typeof b.pin==='string'&&/^\d{4}$/.test(b.pin)){
 await limit(req,'admin',12);
 const configured=(env as any).ADMIN_PIN;
 const selected=(await one("SELECT value FROM settings WHERE key='owner'"))?.value||(await one('SELECT id FROM members WHERE admin=1 ORDER BY joined LIMIT 1'))?.id||'administrator';
 if(await hasAdminPassword(selected))fail('Bruk ditt personlige administratorpassord.',403);
 const administrator=await one('SELECT m.name,m.username,a.login FROM members m LEFT JOIN local_accounts a ON a.user=m.id WHERE m.id=? AND m.admin=1',selected);
 const names=administrator?[administrator.name,administrator.username,administrator.login]:['Andreas'];
 if(!configured||!/^\d{4}$/.test(String(configured))||b.pin!==String(configured)||!names.some(value=>typeof value==='string'&&value.normalize('NFKC').toLocaleLowerCase('nb-NO')===login))fail('Feil navn eller PIN. Glemt PIN? Be Andreas om en ny.',403);
 return session(await owner(),true,b.client==='native');
}
const pin=validatePin(b.pin);
if(b.action==='register'){if(b.ageConfirmed!==true||b.privacyVersion!=='2026-10-06.1')fail('Bekreft at du er minst 13 år og har lest personvernerklæringen.');if(b.installed!==true)fail('Legg appen på hjemskjermen og åpne den derfra før du registrerer deg.');const reserved=await one('SELECT id FROM members WHERE username=?',login);if(reserved||await one('SELECT user FROM local_accounts WHERE login=?',login))fail('Navnet er allerede i bruk. Logg inn, eller be Andreas om hjelp.');const id=crypto.randomUUID(),salt=crypto.randomUUID(),hash=await pinHash(pin,salt);try{await db().batch([db().prepare('INSERT INTO members(id,name,username,email,status,joined,approved,admin) VALUES (?,?,?,?,?,?,?,0)').bind(id,str(b.name,40),login,'','approved',now,now),db().prepare('INSERT INTO local_accounts(user,login,salt,hash) VALUES (?,?,?,?)').bind(id,login,salt,hash)])}catch{fail('Navnet er allerede i bruk. Prøv å logge inn.')}await run('INSERT INTO settings(key,value) VALUES (?,?)','age:'+id,JSON.stringify({minimumAge:13,confirmed:now,privacyVersion:'2026-10-06.1'}));return session(id,false,b.client==='native')}
const account=await one('SELECT a.*,m.admin,m.status FROM local_accounts a JOIN members m ON m.id=a.user WHERE a.login=? OR m.username=?',login,login);const hash=await pinHash(pin,account?.salt||'missing-account');let diff=0;const expected=account?.hash||'0'.repeat(64);for(let i=0;i<64;i++)diff|=hash.charCodeAt(i)^expected.charCodeAt(i);if(!account||diff)fail('Feil navn eller PIN. Glemt PIN? Be Andreas om en ny.',403);return session(account.user,!!account.admin&&account.status==='approved',b.client==='native');
});
