'use client';
import {useEffect,useState} from 'react';
import SignaturePad from './signature-pad';
import {validSignature,type SignatureData} from '@/lib/signature';
type Agreement={text:string;version:string;role:string};
export default function AdminAgreement({onAccepted}:{onAccepted:()=>unknown}){
 const [data,setData]=useState<Agreement|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[signature,setSignature]=useState<SignatureData>([]);
 useEffect(()=>{let active=true;fetch('/api/admin-access',{cache:'no-store'}).then(async r=>{const j=await r.json() as Agreement&{error?:string};if(!r.ok)throw Error(j.error);if(active){setData(j);setError('')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[retry]);
 return <section className="content admin-onboarding"><div className="panel"><span className="eyebrow">FOTO JAKT · TRYGG SAKSBEHANDLING</span><h1>Taushetserklæring</h1><p>Dommer, hoveddommer, administrator og eier signerer før innsyn. Bruk din personlige konto. Erklæringen og underskriften din er ikke offentlige.</p>{error&&<p role="alert" className="error">{error}</p>}{!data?<button className="button" onClick={()=>setRetry(n=>n+1)}>Hent erklæringen</button>:<><div className="agreement-text" tabIndex={0} aria-label="Fullstendig taushetserklæring">{data.text}</div><p className="muted">Versjon {data.version}. Signaturen dokumenterer aksept fra kontoen din og er ikke BankID-verifisert. Tidligere signeringer beholdes, normalt til 90 dager etter at rollen fjernes.</p><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/admin-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'accept',version:data.version,accepted:f.get('accepted')==='on',name:f.get('name'),signature})});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error);await onAccepted()}catch(e){setError(e instanceof Error?e.message:'Signeringen kunne ikke lagres.')}finally{setBusy(false)}}}><label className="field">Fullt navn<input name="name" autoComplete="name" minLength={3} maxLength={100} required disabled={busy}/></label><SignaturePad key={data.version} onChange={setSignature} disabled={busy}/><label className="settings-check"><input name="accepted" type="checkbox" required disabled={busy}/>Jeg har lest og godkjenner hele taushetserklæringen.</label><button className="primary" disabled={busy||!validSignature(signature)}>{busy?'Lagrer underskriften …':'Signer og godta'}</button></form></>}</div></section>;
}
