'use client';
import {useEffect,useState} from 'react';
export default function AdminAccess(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[record,setRecord]=useState<any>(null);
 async function load(){try{const r=await fetch('/api/admin-access',{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j);setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function role(m:any){if(!window.confirm(m.admin?`Fjerne adminadgang for ${m.name}? Aktive innlogginger avsluttes.`:`Gi ${m.name} adminrolle? Personen må logge inn på nytt og godkjenne taushetserklæringen før saksinnsyn.`))return;setBusy(true);setRecord(null);try{const r=await fetch('/api/admin-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'role',id:m.id,enabled:!m.admin})}),j:any=await r.json();if(!r.ok)throw Error(j.error);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function view(id:string){setBusy(true);try{const r=await fetch('/api/admin-access?agreement='+encodeURIComponent(id),{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);setRecord(j.agreement)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const members=(data?.members||[]).filter((m:any)=>(m.name+' '+(m.username||'')).toLocaleLowerCase('nb-NO').includes(query.toLocaleLowerCase('nb-NO')));
 return <section className="panel"><div className="section-title"><div><h2>Adminroller</h2><p>Bare eieren kan gi eller fjerne tilgang. Alle godkjente administratorer kan behandle saker.</p></div><button className="button" disabled={busy} onClick={load}>Oppdater</button></div><p className="muted">Ny tildeling avslutter gamle innlogginger. Administratoren logger inn med sin egen konto på forsiden og åpner /admin for første godkjenning. Eierrollen kan ikke fjernes her.</p>{error&&<p role="alert" className="error">{error}</p>}<label className="field">Finn bruker<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Navn eller brukernavn"/></label>{!data?<p role="status">Henter roller …</p>:members.map((m:any)=><div className="row" key={m.id}><div className="grow"><strong>{m.name}</strong><p>@{m.username||'eier'} · {m.admin?m.agreementAccepted?'Admin - erklæring godkjent':'Admin - venter på erklæring':m.status==='approved'?'Aktiv bruker':'Ikke aktiv'}</p></div><div className="actions">{m.agreementAccepted===1&&<button className="button" disabled={busy} onClick={()=>view(m.id)}>Vis erklæring</button>}<button className="button" disabled={busy||m.id===data.ownerId||(!m.admin&&m.status!=='approved')} onClick={()=>role(m)}>{m.admin?'Fjern admin':'Gi admin'}</button></div></div>)}{data&&!members.length&&<p>Ingen brukere matcher søket.</p>}{record&&<aside className="panel agreement-record"><h3>Registrert taushetserklæring</h3><p>{record.name}<br/>{record.email}<br/>{record.address}</p><p>Elektronisk underskrift: {record.signature}<br/>Godkjent: {new Date(record.accepted).toLocaleString('nb-NO')} · versjon {record.version}</p><div className="agreement-text">{record.text}</div><button className="button" onClick={()=>setRecord(null)}>Lukk opplysningene</button></aside>}</section>
}
