'use client';
import {Checkbox} from '@/components/ui/checkbox';
import {dailyReminders} from '@/lib/push-events';
import {useState,useEffect,useCallback} from 'react';
import {Bell,BellRing,Download,CheckCircle2,Smartphone,Share2,WifiOff,Clock,CalendarClock} from 'lucide-react';
export function useAppExperience(enabled:boolean){
 const [checked,setChecked]=useState(false),[notificationChecked,setNotificationChecked]=useState(false),[installed,setInstalled]=useState(false),[ios,setIos]=useState(false),[installPrompt,setInstallPrompt]=useState<any>(null),[permission,setPermission]=useState('default'),[registered,setRegistered]=useState(false),[config,setConfig]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[online,setOnline]=useState(true);
 const sync=useCallback(async()=>{setNotificationChecked(false);if('Notification'in window)setPermission(Notification.permission);if(!enabled){setRegistered(false);setNotificationChecked(true);return}try{const r=await fetch('/api/push',{cache:'no-store'});if(!r.ok){setRegistered(false);return;}const c=await r.json();setConfig(c);if('Notification'in window)setPermission(Notification.permission);if('serviceWorker'in navigator&&'PushManager'in window){const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();if(sub&&'Notification'in window&&Notification.permission==='granted'){const saved=await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'subscribe',subscription:sub.toJSON(),installed:matchMedia('(display-mode: standalone)').matches||!!(navigator as any).standalone})});setRegistered(saved.ok)}else {setRegistered(false);if(sub)await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'unsubscribe',endpoint:sub.endpoint})})}}}catch{setRegistered(false)}finally{setNotificationChecked(true)}},[enabled]);
 useEffect(()=>{const media=matchMedia('(display-mode: standalone)');const detect=()=>{setInstalled(media.matches||!!(navigator as any).standalone);setChecked(true)};detect();setIos(/iPhone|iPad|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1));setOnline(navigator.onLine);if('Notification'in window)setPermission(Notification.permission);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).catch(()=>{});
 const prompt=(e:any)=>{e.preventDefault();setInstallPrompt(e)};const done=()=>{detect();setInstallPrompt(null)};const network=()=>setOnline(navigator.onLine);const visible=()=>{if(document.visibilityState==='visible'){detect();sync()}};
 window.addEventListener('beforeinstallprompt',prompt);window.addEventListener('appinstalled',done);window.addEventListener('online',network);window.addEventListener('offline',network);document.addEventListener('visibilitychange',visible);media.addEventListener('change',detect);sync();const timer=setInterval(()=>{if(document.visibilityState==='visible')sync()},30000);
 return()=>{clearInterval(timer);window.removeEventListener('beforeinstallprompt',prompt);window.removeEventListener('appinstalled',done);window.removeEventListener('online',network);window.removeEventListener('offline',network);document.removeEventListener('visibilitychange',visible);media.removeEventListener('change',detect)}},[sync]);
 async function subscribe(){setError('');setMessage('');if(!installed){setError('Legg Foto Jakt på hjemskjermen først, og åpne appen fra ikonet.');return}if(!('Notification'in window)||!('PushManager'in window)||!('serviceWorker'in navigator)){setError('Denne nettleseren støtter ikke pushvarsler. Prøv den installerte appen eller en oppdatert Safari eller Chrome.');return}if(!config?.publicKey){setError('Varslingstjenesten er ikke klar. Prøv igjen om litt.');return}setBusy(true);try{
 // Request permission immediately in the user's tap handler (required by iOS).
 const result=await Notification.requestPermission();setPermission(result);if(result!=='granted'){setError(result==='denied'?'Varsler er blokkert. Tillat dem i telefonens innstillinger for Foto Jakt.':'Du må velge «Tillat» for å motta varsler.');return}
 const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub){const raw=atob(config.publicKey.replace(/-/g,'+').replace(/_/g,'/'));const key=Uint8Array.from(raw,c=>c.charCodeAt(0));sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key})}
 const r=await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'subscribe',subscription:sub.toJSON(),installed:matchMedia('(display-mode: standalone)').matches||!!(navigator as any).standalone})});const j:any=await r.json();if(!r.ok)throw Error(j.error);setRegistered(true);setConfig((c:any)=>({...c,...j}));setMessage('Varsler er aktivert på denne enheten. Du kan lukke appen.');
 }catch(e:any){setError(e.message||'Kunne ikke aktivere varsler. Prøv igjen.')}finally{setBusy(false)}}
 async function test(){setBusy(true);setError('');setMessage('');try{const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();const r=await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'test',endpoint:sub?.endpoint})});const j:any=await r.json();if(!r.ok)throw Error(j.error);setMessage('Testvarselet er sendt. Se etter det på telefonen.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function notifications(enabled:boolean){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'notifications',enabled})});const j:any=await r.json();if(!r.ok)throw Error(j.error);setConfig((c:any)=>({...c,notificationsEnabled:j.notificationsEnabled}));setMessage(enabled?'Varsler er slått på.':'Alle varsler er slått av på alle enhetene dine. Du kan fortsatt spille som vanlig.');if(!enabled&&'serviceWorker' in navigator){const reg=await navigator.serviceWorker.getRegistration();for(const n of await reg?.getNotifications()||[])n.close()}}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function preference(kind:'comments'|'reactions'|'replies',enabled:boolean){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preferences',kind,enabled})});const j:any=await r.json();if(!r.ok)throw Error(j.error);setConfig((c:any)=>({...c,preferences:j.preferences}));setMessage('Varslingsvalget er lagret på kontoen din.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function install(){if(!installPrompt)return;await installPrompt.prompt();const result=await installPrompt.userChoice;if(result.outcome==='accepted')setInstallPrompt(null)}
 return {checked,notificationChecked,installed,ios,installPrompt,install,permission,registered,config,busy,error,message,subscribe,test,online,sync,preference,notifications};
}
export function InstallGuide({app}:{app:ReturnType<typeof useAppExperience>}){return (<section className="app-setup-step"><div className="setup-step-icon"><Smartphone/></div><div><h3>1. Legg appen på hjemskjermen</h3>{app.installed?<p className="setup-success"><CheckCircle2 size={17}/> Du bruker appen fra hjemskjermen.</p>:<><p>Åpne Foto Jakt med eget ikon og uten nettleserlinjen.</p>{app.installPrompt?<button className="primary" onClick={app.install}><Download size={18}/> Installer Foto Jakt</button>:app.ios?<ol className="install-steps"><li>Åpne denne siden i Safari.</li><li>Trykk på <Share2 size={15}/> <strong>Del</strong>.</li><li>Velg <strong>Legg til på Hjem-skjerm</strong>. La «Åpne som nettapp» være på hvis valget vises, og trykk <strong>Legg til</strong>.</li><li>Åpne Foto Jakt fra det nye ikonet.</li></ol>:<ol className="install-steps"><li>På Android: åpne lenken i Chrome.</li><li>Trykk på menyen ⋮ og velg <strong>Installer app</strong> eller <strong>Legg til på startskjermen → Installer</strong>.</li><li>Åpne Foto Jakt fra det nye ikonet. Et vanlig bokmerke i nettleseren er ikke nok.</li></ol>}</>}</div></section>)}
export function AppSettings({app}:{app:ReturnType<typeof useAppExperience>}){return <div className="app-settings">{!app.notificationChecked?<div className="notification-status-skeleton" aria-label="Sjekker varslingsstatus"><div className="skeleton-line wide"/><div className="skeleton-line"/><div className="skeleton-card"/></div>:
 <InstallGuide app={app}/>
 <section className="app-setup-step"><div className="setup-step-icon"><BellRing/></div><div><h3>Varsler – helt valgfritt</h3><p>Spill med eller uten varsler. Valget gjelder alle enhetene dine.</p><label className="flex items-center gap-3 py-3"><Checkbox checked={app.config?.notificationsEnabled!==false} disabled={app.busy||!app.config} onCheckedChange={v=>app.notifications(v===true)}/><span>Tillat varsler fra Foto Jakt</span></label>{app.config?.notificationsEnabled===false&&<p className="muted">Alle varsler er av, også kommentarer og reaksjoner.</p>}<details><summary className="profile-settings cursor-pointer py-3">Se tidspunkter og enhetsoppsett</summary><ul className="notification-list">{dailyReminders.map(r=><li key={r.hour}><CheckCircle2 size={16}/><span><strong>{String(r.hour).padStart(2,'0')}.00</strong> – {r.message}</span></li>)}</ul><p className="muted">Norsk tid. Når du har levert bildet til en jakt, stopper påminnelsene for den jakten på alle enhetene dine.</p>{app.config?.notificationsEnabled===false?<p>Slå på valget over hvis du ønsker varsler igjen.</p>:app.registered&&app.permission==='granted'?<><p className="setup-success"><CheckCircle2 size={17}/> Varsler er på for denne enheten</p><button className="button" disabled={app.busy} onClick={app.test}><Bell size={17}/> {app.busy?'Sender …':'Send et testvarsel'}</button></>:<button className="primary" disabled={app.busy||!app.installed||!app.config?.configured} onClick={app.subscribe}><BellRing size={18}/>{app.busy?'Aktiverer …':'Slå på pushvarsler'}</button>}<p className="muted">Hvis varsler er blokkert: På iPhone åpner du Innstillinger → Varslinger → Foto Jakt. På Android åpner du app- eller nettstedsinnstillingene for Foto Jakt og tillater varsler. Kom tilbake og trykk «Sjekk oppsett på nytt».</p><button className="button" onClick={app.sync} disabled={app.busy}>Sjekk oppsett på nytt</button><p className="muted">Varsler krever tillatelse på telefonen hvis du ønsker å bruke dem. Lydløs modus og Fokus kan dempe dem.</p>{app.config?.notificationsEnabled!==false&&app.config&&!app.config.schedulerOnline&&<p className="push-warning">Den automatiske varslingstjenesten svarer ikke akkurat nå. Nedtellingen i appen virker fortsatt.</p>}</details></div></section>
 <section className="app-setup-step"><div className="setup-step-icon"><Bell/></div><div><h3>Pushvarsler om aktivitet</h3><p>Alt vises i bjellen. Velg hva som også skal sende en notifikasjon til telefonen. Gjelder alle enhetene dine.</p>{([['comments','Kommentarer på mine bilder'],['reactions','Reaksjoner på mine bilder'],['replies','Svar på mine kommentarer']] as const).map(([kind,label])=><label key={kind} className="flex items-center gap-3 py-3"><Checkbox checked={!!app.config?.preferences?.[kind]} disabled={app.busy||!app.config||app.config.notificationsEnabled===false} onCheckedChange={v=>app.preference(kind,v===true)}/><span>{label}</span></label>)}<p className="muted">Push sendes bare for valgene du slår på. Varslene i bjellen vises uansett. Bryteren «Tillat varsler fra Foto Jakt» over slår av alle pushvarsler.{!app.registered?' Aktiver pushvarsler på denne enheten for å motta dem.':''}</p></div></section>
 {app.error&&<p className="error" role="alert">{app.error}</p>}{app.message&&<p className="setup-success" role="status">{app.message}</p>}}</div>}
export function NextHunt({upcoming,now}:{upcoming:any,now:number}){const remaining=Math.max(0,upcoming.start-now);const allSeconds=Math.floor(remaining/1000);const units=[[Math.floor(allSeconds/86400),'dager'],[Math.floor(allSeconds/3600)%24,'timer'],[Math.floor(allSeconds/60)%60,'min'],[allSeconds%60,'sek']];return <section className="next-hunt"><div className="next-hunt-heading"><span className="badge"><CalendarClock size={15}/> NESTE FOTOJAKT</span><span className="muted">{upcoming.daily?'Frist '+new Date(upcoming.end).toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZone:'Europe/Oslo'}):Math.round(upcoming.duration/60000)+' min på å levere'}</span></div><h2>{remaining>0?'Gjør deg klar!':'Jakten starter nå!'}</h2><p>To jakter hver dag: 07.00–15.00 og 15.00–00.00. Ordet vises først når du starter din egen klokke.</p><div className="countdown" role="timer" aria-label="Tid til neste fotojakt">{units.filter((_,i)=>i>0||allSeconds>=86400).map(([n,label])=><div key={label}><strong>{String(n).padStart(2,'0')}</strong><span>{label}</span></div>)}</div><div className="next-hunt-date"><Clock size={17}/><time dateTime={new Date(upcoming.start).toISOString()}>{new Date(upcoming.start).toLocaleString('nb-NO',{weekday:'long',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Oslo'})}</time></div><p className="muted">Har du slått på varsler? Du får beskjed kl. 07.00 og 15.00 når nye ord er klare.</p></section>}
export function OfflineBanner(){return <div className="offline-banner" role="status"><WifiOff size={18}/> Du er uten nett. En klargjort jakt kan fortsatt fotograferes. Bilder og tider lagres på enheten og leveres når forbindelsen er tilbake. Åpne appen igjen hvis den har vært lukket.</div>}
