'use client';
import {useState,useEffect} from 'react';
import {Bug} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
export default function BugReport({page,compact=false}:{page:string,compact?:boolean}){
 const [open,setOpen]=useState(false),[description,setDescription]=useState(''),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const form=new FormData();form.set('description',description);form.set('page',page);if(file){if(file.size>20*1024*1024)throw Error('Velg et bilde under 20 MB.');const img=new Image();img.src=preview;await img.decode();const ratio=Math.min(1,1400/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*ratio);canvas.height=Math.round(img.height*ratio);canvas.getContext('2d')!.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.8));if(!blob||blob.size>2000000)throw Error('Bildet er for stort. Velg et mindre bilde.');form.set('photo',blob,'bug.jpg');}const r=await fetch('/api/bugs',{method:'POST',body:form}),j:any=await r.json();if(!r.ok)throw Error(j.error);setOpen(false);setDescription('');setFile(null);toast.success('Takk! Bugrapporten er sendt til Andreas.')}catch(e:any){setError(e.message||'Kunne ikke sende rapporten. Prøv igjen.')}finally{setBusy(false)}}
 return <><button className={compact?"menu-bug-link":"profile-admin-link"} onClick={()=>setOpen(true)}><Bug size={16}/>Rapporter en bug</button><Dialog open={open} onOpenChange={v=>!busy&&setOpen(v)}><DialogContent className="!max-w-lg max-h-[90dvh] overflow-y-auto"><DialogTitle>Rapporter en bug</DialogTitle><DialogDescription>Fortell hva som skjedde og hva du forventet. Bare Andreas kan se rapporten og bildet.</DialogDescription><form onSubmit={submit}><label className="field">Hva er problemet?<textarea required maxLength={1500} rows={5} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Hva trykket du på? Hva skjedde?"/></label><label className="field">Bilde eller skjermbilde (valgfritt)<input type="file" accept="image/*" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{preview&&<><img className="bug-preview" src={preview} alt="Bilde vedlagt bugrapporten"/><button type="button" className="button" disabled={busy} onClick={()=>setFile(null)}>Fjern bilde</button></>}<p className="muted">Unngå PIN-koder og annen privat informasjon i bildet.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy||!description.trim()}>{busy?'Sender …':'Send rapport'}</button></form></DialogContent></Dialog></>;
}
export function BugReports(){const [reports,setReports]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);async function load(){try{const r=await fetch('/api/bugs',{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);setReports(j.reports);setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);async function resolve(report:any){setBusy(true);try{const r=await fetch('/api/bugs',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:report.id,resolved:!report.resolved})}),j:any=await r.json();if(!r.ok)throw Error(j.error);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <div className="panel bug-reports"><h2>Bugrapporter</h2>{error&&<p className="error">{error}<button className="button" onClick={load}>Prøv igjen</button></p>}{loading?<p>Laster rapporter …</p>:!reports.length?<p className="muted">Ingen bugrapporter ennå.</p>:reports.map(r=><article className="bug-report-card" key={r.id}><strong>{r.username?'@'+r.username:r.name} · {r.resolved?'Behandlet':'Ny rapport'}</strong><p className="muted">{new Date(r.created).toLocaleString('nb-NO',{timeZone:'Europe/Oslo'})} · {r.page}</p><p className="profile-bio">{r.description}</p>{r.imageKey&&<a href={'/api/bugs/'+encodeURIComponent(r.id)} target="_blank" rel="noreferrer"><img className="bug-preview" src={'/api/bugs/'+encodeURIComponent(r.id)} alt="Vedlagt skjermbilde – åpne i stor visning" loading="lazy"/></a>}<button className="button" disabled={busy} onClick={()=>resolve(r)}>{r.resolved?'Marker som åpen':'Marker som behandlet'}</button></article>)}</div>}
