'use client';
import {useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const icons=['','⚡','🎯','📢','✨','🎉','📸','ℹ️'];
export default function ChatUpdate({open,onClose,onPublished}:{open:boolean,onClose:()=>void,onPublished:()=>void}){
 const [title,setTitle]=useState(''),[body,setBody]=useState(''),[icon,setIcon]=useState('⚡'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const pending=useRef<{id:string,updateTitle:string,updateIcon:string,body:string}|null>(null);
 async function publish(e:React.FormEvent){e.preventDefault();if(busy||!title.trim()||!body.trim())return;setBusy(true);setError('');const values={updateTitle:title.trim(),updateIcon:icon,body:body.trim()};if(!pending.current||pending.current.updateTitle!==values.updateTitle||pending.current.updateIcon!==icon||pending.current.body!==values.body)pending.current={id:crypto.randomUUID(),...values};try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'update',room:'public',...pending.current}),signal:AbortSignal.timeout(15000)}),j:any=await r.json();if(!r.ok)throw Error(j.error);pending.current=null;setTitle('');setBody('');setIcon('⚡');onPublished();onClose()}catch(e:any){setError(e.name==='TimeoutError'||e.name==='TypeError'?'Ustabil forbindelse. Utkastet er beholdt. Trykk Publiser for å prøve igjen.':e.message)}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={v=>{if(!v&&!busy){setError('');onClose()}}}><DialogContent className="chat-update-dialog" showCloseButton={!busy} onEscapeKeyDown={e=>{if(busy)e.preventDefault()}} onPointerDownOutside={e=>e.preventDefault()}><DialogTitle>Ny oppdatering</DialogTitle><DialogDescription>Publiser en tydelig beskjed til alle i felleschatten.</DialogDescription><form onSubmit={publish} className="chat-update-form"><label htmlFor="update-title">Overskrift</label><input id="update-title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} required disabled={busy} placeholder="Nytt i Foto Jakt!"/><label htmlFor="update-body">Informasjonsmelding</label><textarea id="update-body" value={body} onChange={e=>setBody(e.target.value)} maxLength={1500} rows={5} required disabled={busy} placeholder="Hva er nytt?"/><label htmlFor="update-icon">Ikon / emoji (valgfritt)</label><select id="update-icon" value={icon} onChange={e=>setIcon(e.target.value)} disabled={busy}>{icons.map(i=><option key={i} value={i}>{i||'Ingen ikon'}</option>)}</select>{(title.trim()||body.trim())&&<div className="chat-update-preview"><small>Forhåndsvisning · Oppdatering</small><h3>{icon&&<span aria-hidden="true">{icon} </span>}{title||'Overskrift'}</h3><p>{body||'Informasjonsmelding'}</p></div>}{error&&<p className="error" role="alert">{error}</p>}<div className="chat-update-buttons"><button className="button" type="button" disabled={busy} onClick={onClose}>Avbryt</button><button className="primary" disabled={busy||!title.trim()||!body.trim()}>{busy?'Publiserer …':'Publiser'}</button></div></form></DialogContent></Dialog>
}
