'use client';
import {useState,useEffect} from 'react';
export default function ChatWordBank(){
 const [text,setText]=useState(''),[version,setVersion]=useState(''),[canEdit,setCanEdit]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 async function load(){const r=await fetch('/api/chat/moderation/words',{cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);setText(j.words.join('\n'));setVersion(j.version);setCanEdit(j.canEdit);setReady(true)}
 useEffect(()=>{load().catch(e=>setStatus(e.message))},[]);
 async function save(e:any){e.preventDefault();setBusy(true);setStatus('');try{const r=await fetch('/api/chat/moderation/words',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({words:text.split('\n').map(x=>x.trim()).filter(Boolean),expected:version})}),j:any=await r.json();if(!r.ok)throw Error(j.error);setVersion(j.version);setText(j.words.join('\n'));setStatus('Ordlisten er lagret. Gjelder nye meldinger i felleschatten.')}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 return <details className="panel mt-5"><summary>Ord og fraser til chatkontroll</summary><p>Treff flagges til admin; det er ikke en automatisk avgjørelse om regelbrudd. Én frase per linje, maks 200. Hele ord matches, uavhengig av store bokstaver og vanlig tegnsetting. Tom liste slår av automatisk flagging. Bilder og vedlegg leses ikke.</p>{status&&<p role="status">{status}</p>}{!ready?<p>Laster ordliste …</p>:<form onSubmit={save}><label className="field">Ord og fraser<textarea rows={10} value={text} disabled={!canEdit||busy} onChange={e=>setText(e.target.value)}/></label>{canEdit?<div className="actions"><button className="primary" disabled={busy}>{busy?'Lagrer …':'Lagre ordliste'}</button><button type="button" className="button" disabled={busy} onClick={()=>load().catch(e=>setStatus(e.message))}>Hent gjeldende liste</button></div>:<p className="muted">Bare eieren kan endre ordlisten.</p>}</form>}</details>
}
