'use client';
import {useState,useEffect,useCallback} from 'react';
import {ChatMedia,ChatLinks} from './chat-content';
export default function ChatAdmin(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[reviewed,setReviewed]=useState(false);
 const refresh=useCallback(async(signal?:AbortSignal)=>{try{const r=await fetch('/api/chat/moderation'+(reviewed?'?reviewed=1':''),{cache:'no-store',signal}),j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j);setError('')}catch(e:any){if(e.name!=='AbortError')setError(e.message)}},[reviewed]);
 useEffect(()=>{const a=new AbortController();setData(null);refresh(a.signal);const timer=setInterval(()=>refresh(a.signal),15000);return()=>{a.abort();clearInterval(timer)}},[refresh]);
 async function review(id:string,status:string){setBusy(id);try{const r=await fetch('/api/chat/moderation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})}),j:any=await r.json();if(!r.ok)throw Error(j.error);await refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 return <section className="panel chat-admin"><h2>Chat til vurdering</h2><p>AI flagger mulig rasisme, trusler og annet bekymringsfullt innhold. Usikkerhet, AI-feil og filer eller lenker som ikke kan leses fullt ut vises også her. Meldinger blir stående i chatten. Bare du avgjør oppfølging.</p><div className="actions"><button className="button" onClick={()=>setReviewed(!reviewed)}>{reviewed?'Vis vurderingskø':'Vis vurderte'}</button><button className="button" onClick={()=>refresh()}>Oppdater</button></div>{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p>Laster rapporter …</p>}{!!data?.pending&&<p className="muted">{data.pending} meldinger venter på AI-kontroll i bakgrunnen.</p>}{data&&!data.items.length&&<p>Ingen meldinger i dette utvalget.</p>}{data?.items.map((m:any)=><article className="chat-review-card" key={m.id}><strong>{m.name} · {m.roomName}</strong><small>{new Date(m.created).toLocaleString('nb-NO',{timeZone:'Europe/Oslo'})} · {m.status==='flagged'?'Flagget av AI':m.status==='manual'?'Manuell vurdering':m.status==='confirmed'?'Bekymring bekreftet':'Vurdert som OK'}</small><p className="chat-review-reason">{m.reason}</p><p className="chat-review-body">{m.body}</p><ChatMedia message={m} review/><ChatLinks body={m.body}/>{!reviewed&&<div className="actions"><button className="button" disabled={!!busy} onClick={()=>review(m.id,'dismissed')}>Vurdert som OK</button><button className="button" disabled={!!busy} onClick={()=>review(m.id,'confirmed')}>Bekreft bekymring</button></div>}</article>)}</section>;
}
