'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {MessageCircle,Users,Send,Trash2,ChevronUp,ArrowDown,ArrowLeft,ChevronRight,Reply,SmilePlus,X} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
type Message={id:string,user:string,body:string,created:number,name:string,avatarVersion?:number,replyTo?:string,reply?:{id:string,body:string,name:string},reactions:{emoji:string,count:number,mine:number}[]};
const emojis=['❤️','👍','😂','😮','😢','🎉'];
export default function Discussion({user,onProfile,onGroups}:{user:any,onProfile:(person:any)=>void,onGroups:()=>void}){
 const [room,setRoom]=useState('public'),[opened,setOpened]=useState(false),[before,setBefore]=useState(''),[data,setData]=useState<any>(null),[groups,setGroups]=useState<any[]>([]),[error,setError]=useState(''),[drafts,setDrafts]=useState<Record<string,string>>({}),[replies,setReplies]=useState<Record<string,Message|null>>({}),[sending,setSending]=useState(false),[deleting,setDeleting]=useState(''),[picker,setPicker]=useState(''),[reacting,setReacting]=useState(''),[viewport,setViewport]=useState<{height:number,top:number}|null>(null);
 const requestSeq=useRef(0),list=useRef<HTMLDivElement>(null),textarea=useRef<HTMLTextAreaElement>(null),nearBottom=useRef(true),pending=useRef<{room:string,body:string,id:string,replyTo:string|null}|null>(null);
 const refresh=useCallback(async(signal?:AbortSignal)=>{const seq=++requestSeq.current;try{const r=await fetch('/api/chat?room='+encodeURIComponent(room)+(before?'&before='+encodeURIComponent(before):''),{cache:'no-store',signal});const j:any=await r.json();if(seq!==requestSeq.current)return;if(!r.ok){if(r.status===403){setData(null);setGroups([]);setOpened(false);setRoom('public');setBefore('')}throw Error(j.error)}setData(j);setGroups(j.groups);setError('')}catch(e:any){if(e.name!=='AbortError'&&seq===requestSeq.current)setError(e.message)}},[room,before]);
 useEffect(()=>{const controller=new AbortController();setData(null);nearBottom.current=true;refresh(controller.signal);const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh(controller.signal)},3000);const wake=()=>{if(document.visibilityState==='visible')refresh(controller.signal)};document.addEventListener('visibilitychange',wake);window.addEventListener('online',wake);return()=>{controller.abort();++requestSeq.current;clearInterval(timer);document.removeEventListener('visibilitychange',wake);window.removeEventListener('online',wake)}},[refresh]);
 useEffect(()=>{if(!opened)return;const v=window.visualViewport;const resize=()=>setViewport(v?{height:v.height,top:v.offsetTop}:null);resize();v?.addEventListener('resize',resize);v?.addEventListener('scroll',resize);return()=>{v?.removeEventListener('resize',resize);v?.removeEventListener('scroll',resize)}},[opened]);
 const body=drafts[room]||'',reply=replies[room];
 useEffect(()=>{const el=textarea.current;if(el){el.style.height='48px';el.style.height=Math.min(128,Math.max(48,el.scrollHeight))+'px'}},[body,opened]);
 useEffect(()=>{if(opened&&!before&&nearBottom.current&&list.current)list.current.scrollTop=list.current.scrollHeight},[data?.messages?.at(-1)?.id,before,opened,viewport?.height]);
 function choose(value:string){++requestSeq.current;setData(null);setBefore('');setRoom(value);setPicker('');setError('');setOpened(true);nearBottom.current=true;if(value===room)refresh()}
 function close(){if(sending||deleting)return;setOpened(false);setPicker('');setBefore('');setRoom('public');setError('')}
 async function send(e:React.FormEvent){e.preventDefault();const text=body.trim();if(!text||sending)return;const target=room,replyTo=reply?.id||null;setSending(true);setError('');if(!pending.current||pending.current.room!==target||pending.current.body!==text||pending.current.replyTo!==replyTo)pending.current={room:target,body:text,id:crypto.randomUUID(),replyTo};try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'send',...pending.current}),signal:AbortSignal.timeout(15000)});const j:any=await r.json();if(!r.ok)throw Error(j.error);pending.current=null;setDrafts(old=>({...old,[target]:old[target]?.trim()===text?'':old[target]}));setReplies(old=>({...old,[target]:null}));nearBottom.current=true;if(before)setBefore('');else await refresh();textarea.current?.focus()}catch(e:any){setError(e.name==='TimeoutError'||e.name==='TypeError'?'Tilkoblingen er ustabil. Teksten er beholdt. Trykk Send for å prøve igjen.':e.message)}finally{setSending(false)}}
 async function action(payload:any){const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,room}),signal:AbortSignal.timeout(15000)});const j:any=await r.json();if(!r.ok)throw Error(j.error);await refresh()}
 async function remove(message:Message){if(!window.confirm('Slette denne meldingen?'))return;setDeleting(message.id);try{await action({action:'delete',id:message.id});toast.success('Meldingen er slettet')}catch(e:any){setError(e.message)}finally{setDeleting('')}}
 async function react(m:Message,emoji:string){if(reacting)return;setReacting(m.id);try{await action({action:'react',id:m.id,emoji:m.reactions.some(r=>r.emoji===emoji&&r.mine)?null:emoji});setPicker('')}catch(e:any){setError(e.message)}finally{setReacting('')}}
 function answer(m:Message){setReplies(old=>({...old,[room]:m}));setPicker('');textarea.current?.focus()}
 const roomName=data?.name||(room==='public'?'Felles chat':groups.find(g=>g.id===room)?.name||'Gruppechat');
 const notice=error&&<div className="error chat-error" role="alert">{error}<button className="button" onClick={()=>refresh()}>Prøv igjen</button></div>;
 return <section className="discussion"><p className="chat-overview-hint">Velg en samtale</p>{!opened&&notice}<div className="chat-room-list"><button className="chat-room-card" onClick={()=>choose('public')}><span className="chat-room-icon"><MessageCircle size={24}/></span><span><strong>Felles chat</strong><small>Alle deltakere · åpen samtale</small></span><ChevronRight size={20}/></button>{groups.map(g=><button key={g.id} className="chat-room-card" onClick={()=>choose(g.id)}><span className="chat-room-icon"><Users size={24}/></span><span><strong>{g.name}</strong><small>Gruppechat · bare for medlemmer</small></span><ChevronRight size={20}/></button>)}</div>{!data&&!error&&<p className="muted">Laster samtaler …</p>}{data&&!groups.length&&<div className="chat-group-help"><Users size={22}/><p>Gruppechattene dine vises her.</p><button className="button" onClick={onGroups}>Åpne Venner og grupper</button></div>}
 <Dialog open={opened} onOpenChange={value=>{if(!value)close()}}><DialogContent fullScreen showCloseButton={false} className="chat-screen" style={viewport?{height:viewport.height,top:viewport.top}:undefined} aria-describedby={undefined} onOpenAutoFocus={e=>e.preventDefault()}><div className="chat-screen-heading"><button className="chat-back" onClick={close} disabled={sending||!!deleting} aria-label="Tilbake til samtaler"><ArrowLeft size={22}/></button><span className="chat-room-icon">{room==='public'?<MessageCircle size={22}/>:<Users size={22}/>}</span><div><DialogTitle className="chat-title">{roomName}</DialogTitle><p>{room==='public'?'Alle deltakere':'Privat gruppechat'}</p></div></div>{notice}
 <div className="chat-messages" ref={list} role="log" aria-label="Chatmeldinger" aria-live="polite" aria-relevant="additions" onScroll={()=>{const el=list.current;if(el)nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<100}}>{!data?<p className="muted">Laster chat …</p>:<>{before&&<button className="button chat-history" disabled={sending||!!deleting} onClick={()=>setBefore('')}><ArrowDown size={16}/>Til nyeste meldinger</button>}{data.hasMore&&<button className="button chat-history" disabled={sending||!!deleting} onClick={()=>setBefore(data.nextBefore)}><ChevronUp size={16}/>Vis eldre meldinger</button>}{!data.messages.length&&<div className="chat-empty"><MessageCircle size={36}/><strong>Start samtalen</strong><p>Skriv den første meldingen.</p></div>}{data.messages.map((m:Message)=><article key={m.id} className={'chat-message '+(m.user===user.id?'chat-message-mine':'')}><button className="chat-avatar" aria-label={'Åpne profilen til '+m.name} onClick={()=>onProfile({id:m.user,name:m.name})}><img key={m.avatarVersion||0} src={'/api/avatar/'+encodeURIComponent(m.user)+'?v='+(m.avatarVersion||0)} alt="" onError={e=>{e.currentTarget.style.display='none'}}/><span>{m.name.slice(0,1)}</span></button><div className="chat-message-content"><div className="chat-bubble"><div className="chat-meta"><button onClick={()=>onProfile({id:m.user,name:m.name})}>{m.user===user.id?'Du':m.name}</button><time dateTime={new Date(m.created).toISOString()}>{new Date(m.created).toLocaleString('nb-NO',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Oslo'})}</time></div>{m.replyTo&&<div className="chat-quote"><strong>{m.reply?.name||'Tidligere melding'}</strong><span>{m.reply?.body||'Meldingen er ikke lenger tilgjengelig.'}</span></div>}<p>{m.body}</p></div>{m.reactions.length>0&&<div className="chat-reactions">{m.reactions.map(r=><button key={r.emoji} className={r.mine?'chosen':''} disabled={!!reacting} aria-pressed={!!r.mine} aria-label={r.emoji+' '+r.count+' reaksjoner'} onClick={()=>react(m,r.emoji)}>{r.emoji}<span>{r.count}</span></button>)}</div>}<div className="chat-message-actions"><button onClick={()=>answer(m)} aria-label={'Svar på meldingen til '+m.name}><Reply size={15}/>Svar</button><button aria-label="Reager på melding" aria-expanded={picker===m.id} onClick={()=>setPicker(picker===m.id?'':m.id)}><SmilePlus size={16}/></button>{(m.user===user.id||data.canModerate)&&<button aria-label="Slett melding" disabled={!!deleting} onClick={()=>remove(m)}><Trash2 size={14}/></button>}</div>{picker===m.id&&<div className="chat-reaction-picker" role="group" aria-label="Velg reaksjon">{emojis.map(emoji=><button key={emoji} aria-label={'Reager med '+emoji} disabled={!!reacting} onClick={()=>react(m,emoji)}>{emoji}</button>)}</div>}</div></article>)}</>}</div>
 <div className="chat-composer-wrap">{reply&&<div className="chat-reply-draft"><Reply size={17}/><div><strong>Svarer {reply.user===user.id?'deg selv':reply.name}</strong><span>{reply.body}</span></div><button aria-label="Avbryt svar" disabled={sending} onClick={()=>setReplies(old=>({...old,[room]:null}))}><X size={18}/></button></div>}<form className="chat-compose" onSubmit={send}><label className="sr-only" htmlFor="chat-message">Skriv melding</label><textarea ref={textarea} id="chat-message" value={body} onChange={e=>setDrafts(old=>({...old,[room]:e.target.value}))} maxLength={1500} rows={1} placeholder="Skriv en melding …" disabled={sending||!!deleting||!data} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><button className="primary" disabled={sending||!!deleting||!data||!body.trim()} aria-label={sending?'Sender melding':'Send melding'}><Send size={20}/></button></form><p className="chat-compose-hint">{body.length>1200?body.length+'/1500 · ':''}Ikke røp jaktord før jakten er ferdig.</p></div></DialogContent></Dialog></section>
}
