'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
export function TitleLabel({data,id,title}:any){const text=title??data?.titles?.[id];return text?<small className="player-title">{text}</small>:null}
export function GameNotices({game,busy,act,user}:any){
 const [open,setOpen]=useState<any>(null),seen=useRef(new Set<string>());
 useEffect(()=>{if(!open){const notice=game?.notices?.find((n:any)=>!seen.current.has(user+':'+n.id));if(notice)setOpen(notice)}},[game,open,user]);
 useEffect(()=>{for(const b of game?.bonus||[]){const key='bonus:'+user+':'+b.submission+':'+b.status;if(b.status==='approved'&&!seen.current.has(key)){seen.current.add(key);let known=false;try{known=localStorage.getItem(key)==='1';localStorage.setItem(key,'1')}catch{}if(!known)toast.success('✨ Bonusoppdrag godkjent! +2 poeng')}}},[game,user]);
 const close=async()=>{if(!open)return;if(await act({action:'game-seen',id:open.id},'')){seen.current.add(user+':'+open.id);setOpen(null)}};
 return <Dialog open={!!open} onOpenChange={v=>{if(!v&&!busy)close()}}><DialogContent className="!max-w-md"><DialogTitle>{open?.title||'Ny bragd'}</DialogTitle><DialogDescription>{open?.description}</DialogDescription><button className="primary" disabled={busy} onClick={close}>Rått! 🎉</button></DialogContent></Dialog>
}
export function GameProfile({game,data,busy,act}:any){if(!game)return null;return <section className="panel game-profile"><h3>👑 Dine titler</h3><label className="field">Aktiv tittel<select value={game.active||''} disabled={busy} onChange={e=>act({action:'active-title',id:e.target.value},'Tittelen er oppdatert')}><option value="">Ingen tittel</option>{game.titles.filter((t:any)=>t.earned).map((t:any)=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><p className="muted">Vises på profilen, i kommentarer og poengtavlen.</p><details><summary>Se alle titlene</summary><div className="earned-badges">{game.titles.map((t:any)=><div className={'earned-badge '+(!t.earned?'achievement-locked':'')} key={t.id}><div><strong>{t.earned?'':'🔒 '}{t.title}</strong><small>{t.description}</small></div></div>)}</div></details><h3>🔒 Hemmelige achievements</h3><div className="earned-badges">{game.secrets.map((s:any)=><div className={'earned-badge '+(!s.earned?'achievement-locked':'')} key={s.id}><span className="medal-icon">{s.earned?'🏆':'🔒'}</span><div><strong>{s.title}</strong>{s.earned&&<small>{s.description}</small>}</div></div>)}</div></section>}
export function BonusStatus({challenge,game,onChange}:any){const [enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false);useEffect(()=>{setEnabled(sessionStorage.getItem('bonus-choice:'+challenge.id)==='true')},[challenge.id]);const b=game?.bonus?.find((x:any)=>x.submission===challenge.own?.id);if(!challenge.bonus)return null;async function action(action:string){setBusy(true);try{const r=await fetch('/api/privacy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id:challenge.own.id})}),j:any=await r.json();if(!r.ok)throw Error(j.error);await onChange?.();toast.success(action==='bonus-request'?'Bildet er sendt til bonusvurdering':action==='bonus-appeal'?'Ny manuell vurdering er bestilt':'Bonusvalget er trukket tilbake')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}return <div className="bonus-mission"><strong>🎯 Frivillig bonus · +2 poeng</strong><p>{challenge.bonus}</p>{!challenge.own?<><label className="settings-check"><input type="checkbox" checked={enabled} onChange={e=>{setEnabled(e.target.checked);sessionStorage.setItem('bonus-choice:'+challenge.id,String(e.target.checked))}}/>Send bildet til manuell bonusvurdering</label><small>En administrator med godkjent taushetserklæring vurderer bonuskravet. Bildet sendes ikke til AI. Nei påvirker ikke vanlig levering eller tid. Unngå sensitive opplysninger. <a href="/personvern">Personvern</a></small></>:<><small role="status">{!b?'Ingen bonusvurdering er valgt.':b.status==='pending'?'Venter på manuell bonusvurdering.':b.status==='approved'?'Bonus godkjent! +2 poeng':b.status==='manual'?'Venter på manuell vurdering.':'Bonus avslått.'} {b?.reason}</small>{!b&&challenge.own.valid&&<><button className="button mt-2" disabled={busy} onClick={()=>action('bonus-request')}>{busy?'Sender …':'Send bildet til bonusvurdering'}</button><small>Det leverte bildet vurderes manuelt av admin. Bildet og tiden din beholdes.</small></>}{!challenge.own.valid&&!b&&<small>Bildet må være gyldig for å sendes til bonusvurdering.</small>}{b&&<div className="actions">{['approved','rejected'].includes(b.status)&&<button className="button" disabled={busy} onClick={()=>action('bonus-appeal')}>Be om ny vurdering</button>}<button className="button" disabled={busy} onClick={()=>action('bonus-withdraw')}>Trekk tilbake bonusvurdering</button></div>}</>}</div>}

export function LightningPanel({data,clock}:any){return <>{(data.lightningWarning||[]).map((w:any)=><section className="panel lightning-panel" key={w.id}><h3>⚡ Lynjakt om {Math.max(1,Math.ceil((w.start-clock)/60000))} minutter!</h3><p>20 minutter fra felles start. Ordet kommer når jakten åpner. Push er frivillig.</p></section>)}</>}
function BonusReviewCard({b,busy,act}:any){const [reason,setReason]=useState('');return <article className="bonus-review"><strong>{b.name} · {b.title}</strong><p>{b.bonus}</p><img src={'/api/photo/'+encodeURIComponent(b.submission)+'?review=bonus'} alt={'Bonusbilde fra '+b.name} loading="lazy"/><p className="muted">{b.reason}</p><label className="field">Begrunnelse<textarea required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Forklar hvorfor bonuskravet er oppfylt eller ikke."/></label><div className="actions"><button className="primary" disabled={busy||!reason.trim()} onClick={()=>act({action:'review-bonus',id:b.submission,status:'approved',reason},'Bonus godkjent: +2 poeng')}>Godkjenn +2</button><button className="button" disabled={busy||!reason.trim()} onClick={()=>act({action:'review-bonus',id:b.submission,status:'rejected',reason},'Bonus avslått')}>Avslå bonus</button></div></article>}
export function BonusAdmin({data,busy,act}:any){return <section className="panel"><h3>🎯 Bonusoppdrag til vurdering</h3><p className="muted">Alle frivillig innsendte bonusoppdrag og klager vurderes manuelt av administratorer med godkjent taushetserklæring. Bildene sendes ikke til AI. Vurder kun bonuskravet; vanlig levering og tid påvirkes ikke.</p>{(data.bonusQueue||[]).map((b:any)=><BonusReviewCard key={b.submission} b={b} busy={busy} act={act}/>)}{!data.bonusQueue?.length&&<p>Ingen bonusbilder venter på manuell vurdering.</p>}</section>}
