'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
export function TitleLabel({data,id,title}:any){const text=title??data?.titles?.[id];return text?<small className="player-title">{text}</small>:null}
export function GameNotices({game,busy,act,user}:any){
 const [open,setOpen]=useState<any>(null),seen=useRef(new Set<string>());
 useEffect(()=>{if(!open){const notice=game?.notices?.find((n:any)=>!seen.current.has(user+':'+n.id));if(notice)setOpen(notice)}},[game,open,user]);
 useEffect(()=>{for(const b of game?.bonus||[]){const key='bonus:'+user+':'+b.submission+':'+b.status;if(b.status==='approved'&&!seen.current.has(key)){seen.current.add(key);let known=false;try{known=localStorage.getItem(key)==='1';localStorage.setItem(key,'1')}catch{}if(!known)toast.success('✨ Bonusoppdrag godkjent! +2 poeng')}}},[game,user]);
 const close=async()=>{if(!open)return;if(await act({action:'game-seen',id:open.id},'')){seen.current.add(user+':'+open.id);setOpen(null)}};
 return <Dialog open={!!open} onOpenChange={v=>{if(!v&&!busy)close()}}><DialogContent className="!max-w-md"><DialogTitle>{open?.title||'Ny bragd'}</DialogTitle><DialogDescription>{open?.description}</DialogDescription><button className="primary" disabled={busy} onClick={close}>Rått! 🎉</button></DialogContent></Dialog>
}
export function GameProfile({game,data,busy,act}:any){if(!game)return null;return <section className="panel game-profile"><h3>👑 Dine titler</h3><label className="field">Aktiv tittel<select value={game.active||''} disabled={busy} onChange={e=>act({action:'active-title',id:e.target.value},'Tittelen er oppdatert')}><option value="">Ingen tittel</option>{game.titles.filter((t:any)=>t.earned).map((t:any)=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><p className="muted">Vises på profilen, i kommentarer og poengtavlen.</p><details><summary>Se alle titlene</summary><div className="earned-badges">{game.titles.map((t:any)=><div className={'earned-badge '+(!t.earned?'achievement-locked':'')} key={t.id}><div><strong>{t.earned?'':'🔒 '}{t.title}</strong><small>{t.description}</small></div></div>)}</div></details><h3>🔒 Hemmelige achievements</h3><div className="earned-badges">{game.secrets.map((s:any)=><div className={'earned-badge '+(!s.earned?'achievement-locked':'')} key={s.id}><span className="medal-icon">{s.earned?'🏆':'🔒'}</span><div><strong>{s.title}</strong>{s.earned&&<small>{s.description}</small>}</div></div>)}</div></section>}
export function BonusStatus({challenge,game}:any){const b=game?.bonus?.find((x:any)=>x.submission===challenge.own?.id);if(!challenge.bonus)return null;return <div className="bonus-mission"><strong>🎯 Frivillig bonus · +2 poeng</strong><p>{challenge.bonus}</p>{challenge.own?<small role="status">{!b||b.status==='pending'?'⏳ Bildet er levert. Bonusen vurderes i bakgrunnen.':b.status==='approved'?'✨ Bonusoppdrag godkjent! +2 poeng':b.status==='manual'?'🔎 Bonusen venter på manuell vurdering.':'Bonuskravet ble ikke godkjent.'}{b?.reason&&' '+b.reason}</small>:<small>Lever som vanlig. AI vurderer bare bonusen etter innsending.</small>}</div>}
export function LightningPanel({data,clock,onProfile,onResult}:any){const warnings=data.lightningWarning||[],hunts=(data.challenges||[]).filter((c:any)=>c.lightning&&c.end<=clock),board=data.lightningBoard||[];return <>{warnings.map((w:any)=><section className="panel lightning-panel" key={w.id}><h3>⚡ Lynjakt om {Math.max(1,Math.ceil((w.start-clock)/60000))} minutter!</h3><p>20 minutter fra felles start. Ordet kommer når jakten åpner. Push er frivillig.</p></section>)}{(board.length>0||hunts.length>0)&&<details className="panel lightning-panel"><summary>⚡ Lynjakt · egen toppliste</summary><p className="muted">1 bonuspoeng per gyldig bilde, 3 til vinneren. Poengene teller også i sesongen. Lynjakt bryter aldri den vanlige jaktrekken.</p><ol className="scoreboard-list">{board.map((m:any,i:number)=><li className="row" key={m.id}><span>{i+1}</span><button className="grow text-left" onClick={()=>onProfile({id:m.id,name:m.name})}>{m.name}<TitleLabel data={data} id={m.id}/></button><strong>{m.points} p</strong></li>)}</ol>{hunts.slice(0,4).map((c:any)=><button className="row w-full text-left" key={c.id} onClick={()=>onResult(c.id)}>{c.title} · {new Date(c.start).toLocaleDateString('nb-NO',{timeZone:'Europe/Oslo'})} · Se resultat</button>)}</details>}</>}
export function BonusAdmin({data,busy,act}:any){return <section className="panel"><h3>🎯 Bonusoppdrag til vurdering</h3><p className="muted">AI-usikkerhet og feil havner her. Vurder kun bonuskravet; vanlig levering og tid påvirkes ikke.</p>{(data.bonusQueue||[]).map((b:any)=><article className="bonus-review" key={b.submission}><strong>{b.name} · {b.title}</strong><p>{b.bonus}</p><img src={'/api/photo/'+encodeURIComponent(b.submission)} alt={'Bonusbilde fra '+b.name} loading="lazy"/><p className="muted">{b.reason}</p><div className="actions"><button className="primary" disabled={busy} onClick={()=>act({action:'review-bonus',id:b.submission,status:'approved'},'Bonus godkjent: +2 poeng')}>Godkjenn +2</button><button className="button" disabled={busy} onClick={()=>act({action:'review-bonus',id:b.submission,status:'rejected'},'Bonus avslått')}>Avslå bonus</button></div></article>)}{!data.bonusQueue?.length&&<p>Ingen bonusbilder venter på manuell vurdering.</p>}</section>}
