'use client';
import {useCallback,useEffect,useState} from 'react';
import StableImage from './stable-image';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {ROLE_NAMES,type StaffRole} from '@/lib/staff-labels';
type Case={submission:string;kind:'bonus'|'photo';title:string;details:string;caption:string;bonus?:string;reportReason?:string;voteReason?:string;expectedValid?:number;expectedNote?:string;decision?:string;reason?:string};
type Decision={id:string;submission:string;kind:'bonus'|'photo';title:string;status:string;reason:string;created:number;current:number};
type Appeal={id:string;submission:string;kind:'bonus'|'photo';title:string;details:string;bonus?:string;reason:string;decisionReason:string;conflict:number};
type Queue={decisions:Case[];bonus:Case[];photos:Case[];history:Decision[];appeals:Appeal[];canAppeal:boolean;role:StaffRole};
export function JudgeWorkspace(){
 const [data,setData]=useState<Queue|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('bonus');
 const load=useCallback(async()=>{try{const r=await fetch('/api/judging',{cache:'no-store'}),j=await r.json() as Queue&{error?:string};if(!r.ok)throw Error(j.error);setData(j);setError('')}catch(e){setData(null);setError(e instanceof Error?e.message:'Sakene kunne ikke hentes.')}},[]);
 useEffect(()=>{const start=setTimeout(()=>void load(),0);const t=setInterval(()=>{if(document.visibilityState==='visible')load()},15000);return()=>{clearTimeout(start);clearInterval(t)}},[load]);
 async function act(body:unknown){if(busy)return;setBusy(true);try{const r=await fetch('/api/judging',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error);await load()}catch(e){setError(e instanceof Error?e.message:'Avgjørelsen kunne ikke lagres.')}finally{setBusy(false)}}
 return <section className="judge-workspace"><div className="section-title"><div><span className="eyebrow">{data?ROLE_NAMES[data.role]:'SAKSBEHANDLING'}</span><h2>Dommerpanel</h2><p className="muted">Vurder kravet, dokumenter avgjørelsen og overlat inhabile saker til en kollega. Aktive jaktbilder åpnes etter egen innlevering eller jaktens slutt.</p></div><button className="button" disabled={busy} onClick={load}>Oppdater</button></div>{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p role="status">Henter vurderingssaker …</p>}{data&&<Tabs value={tab} onValueChange={setTab}><TabsList className="admin-nav" aria-label="Dommermeny"><TabsTrigger value="bonus">Bonusbilder · {data.bonus.length}</TabsTrigger><TabsTrigger value="photos">Rapporterte bilder · {data.photos.length}</TabsTrigger><TabsTrigger value="history">Mine vurderinger</TabsTrigger>{data.canAppeal&&<TabsTrigger value="decisions">Omgjør avgjørelser</TabsTrigger>}{['owner','head_judge','administrator'].includes(data.role)&&<TabsTrigger value="appeals">Klager · {data.appeals.length}</TabsTrigger>}</TabsList><TabsContent value="bonus">{data.bonus.map(c=><CaseCard key={c.submission} item={c} busy={busy} act={act} canOverride={data.canAppeal}/>)}{!data.bonus.length&&<p className="panel">Ingen bonusbilder er tilgjengelige for deg akkurat nå.</p>}</TabsContent><TabsContent value="photos">{data.photos.map(c=><CaseCard key={c.submission} item={c} busy={busy} act={act} canOverride={data.canAppeal}/>)}{!data.photos.length&&<p className="panel">Ingen rapporterte bilder er tilgjengelige for deg akkurat nå.</p>}</TabsContent><TabsContent value="decisions">{data.decisions.map(c=><CaseCard key={c.decision} item={c} busy={busy} act={act} canOverride/>)}{!data.decisions.length&&<p className="panel">Ingen tilgjengelige avgjørelser å omgjøre.</p>}</TabsContent><TabsContent value="history"><div className="panel"><h3>Egne tidligere vurderinger</h3>{!data.history.length&&<p>Du har ikke vurdert noen bilder ennå.</p>}{data.history.map(d=><div className="row" key={d.id}><div><strong>{d.title} · {d.kind==='bonus'?'Bonus':'Bildesak'} · {d.status==='approved'?'Godkjent':'Avslått'}</strong><p>{d.reason}</p><small>{new Date(d.created).toLocaleString('nb-NO')} · {d.current?'Gjeldende avgjørelse':'Omgjort'}</small></div></div>)}</div></TabsContent><TabsContent value="appeals">{!data.appeals.length&&<p className="panel">Ingen klager venter på behandling.</p>}{data.appeals.map(a=><AppealCard key={a.id} appeal={a} busy={busy} act={act} canResolve={data.canAppeal&&!a.conflict}/>)}</TabsContent></Tabs>}</section>;
}
function CaseCard({item:c,busy,act,canOverride}:{item:Case;busy:boolean;act:(b:unknown)=>Promise<void>;canOverride:boolean}){
 const [reason,setReason]=useState(''),[photoReady,setPhotoReady]=useState(false);return <article className="panel judge-case"><span className="eyebrow">{c.kind==='bonus'?'FRIVILLIG BONUS · 2 POENG':'RAPPORTERT JAKTBILDE'}</span><h3>{c.title}</h3><p>{c.details}</p>{c.bonus&&<p><strong>Bonuskrav:</strong> {c.bonus}</p>}<StableImage className="judge-photo" onLoad={()=>setPhotoReady(true)} onError={()=>setPhotoReady(false)} src={'/api/photo/'+encodeURIComponent(c.submission)+'?review=case'} alt="Jaktbilde til vurdering" loading="lazy"/>{c.caption&&<p>{c.caption}</p>}{c.decision&&<p><strong>Tidligere begrunnelse:</strong> {c.reason}</p>}{(c.reportReason||c.voteReason)&&<p><strong>Rapport:</strong> {c.reportReason||c.voteReason}</p>}<label className="field">Begrunnelse (obligatorisk ved avslag eller omgjøring)<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500}/></label>{c.decision&&!canOverride?<p className="muted">Bildet har en tidligere avgjørelse. Hoveddommer må behandle saken.</p>:<div className="actions">{['approved','rejected'].map(status=><button key={status} className={status==='approved'?'primary':'button'} disabled={busy||!photoReady||((status==='rejected'||!!c.decision)&&!reason.trim())} onClick={()=>act({id:c.submission,kind:c.kind,status,reason,expectedValid:!!c.expectedValid,expectedNote:c.expectedNote,override:!!c.decision,decision:c.decision})}>{status==='approved'?'Godkjenn':'Avslå'}</button>)}</div>}</article>;
}
function AppealCard({appeal:a,busy,act,canResolve}:{appeal:Appeal;busy:boolean;act:(b:unknown)=>Promise<void>;canResolve:boolean}){
 const [reason,setReason]=useState(''),[photoReady,setPhotoReady]=useState(false);return <article className="panel judge-case"><span className="eyebrow">KLAGE · {a.kind==='bonus'?'BONUS':'BILDESAK'}</span><h3>{a.title}</h3>{a.conflict?<p className="muted">Du er inhabil. En annen hoveddommer eller eier må behandle klagen.</p>:<><p>{a.details}</p>{a.bonus&&<p>Bonuskrav: {a.bonus}</p>}<StableImage className="judge-photo" onLoad={()=>setPhotoReady(true)} onError={()=>setPhotoReady(false)} src={'/api/photo/'+encodeURIComponent(a.submission)+'?review=case'} alt="Bilde i klagesak" loading="lazy"/><p><strong>Opprinnelig begrunnelse:</strong> {a.decisionReason}</p><p><strong>Spillerens klage:</strong> {a.reason}</p>{canResolve?<><label className="field">Begrunnelse for klageavgjørelsen<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="actions"><button className="primary" disabled={busy||!photoReady||!reason.trim()} onClick={()=>act({action:'resolve-appeal',id:a.id,approve:true,reason})}>Ta klagen til følge</button><button className="button" disabled={busy||!photoReady||!reason.trim()} onClick={()=>act({action:'resolve-appeal',id:a.id,approve:false,reason})}>Avslå klagen</button></div></>:<p className="muted">Hoveddommer eller eier avgjør klagen.</p>}</>}</article>;
}
export default function JudgeDashboard({onLock}:{onLock:()=>unknown}){return <div className="content admin-content"><div className="topline"><div><span className="eyebrow">FOTO JAKT · DOMMERTEAM</span><h1>Administrasjon</h1><p>Bilder, avgjørelser og klager samlet på ett sted.</p></div><button className="button" onClick={onLock}>Lås administrasjonen</button></div><JudgeWorkspace/></div>;}
