'use client';
import {useCallback,useEffect,useState} from 'react';
import {Bell,UserPlus,Users,MessageCircle,Heart,Settings2} from 'lucide-react';
import {toast} from 'sonner';
import {LoadingBlock} from './loading-states';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';

type Notice={id:string,kind:string,title:string,detail:string,unread:boolean,hunt?:string,season?:string,room?:string,message?:string,user?:string,group?:string};
export default function NotificationInbox({userId,onSocial,onHunt,onWordChange,onChat,onSettings}:{userId:string,onSocial:()=>void,onHunt:(hunt:string,season:string)=>void,onWordChange:()=>void,onChat:(room:string,message?:string)=>void,onSettings:()=>void}){
 const [open,setOpen]=useState(false),[data,setData]=useState<{items:Notice[],unread:number}|null>(null),[error,setError]=useState(''),[answering,setAnswering]=useState('');
 const refresh=useCallback(async(signal?:AbortSignal)=>{
  try{const response=await fetch('/api/notifications',{cache:'no-store',signal});const value:any=await response.json();if(!response.ok)throw Error(value.error||'Kunne ikke hente varsler.');setData(value);setError('')}
  catch(e:any){if(e.name!=='AbortError')setError(e.message)}
 },[userId]);
 useEffect(()=>{const controller=new AbortController();setData(null);refresh(controller.signal);const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh(controller.signal)},15000);const wake=()=>{if(document.visibilityState==='visible')refresh(controller.signal)};window.addEventListener('social-updated',wake);window.addEventListener('chat-read',wake);window.addEventListener('chat-updated',wake);navigator.serviceWorker?.addEventListener('message',wake);document.addEventListener('visibilitychange',wake);return()=>{controller.abort();clearInterval(timer);window.removeEventListener('social-updated',wake);window.removeEventListener('chat-read',wake);window.removeEventListener('chat-updated',wake);navigator.serviceWorker?.removeEventListener('message',wake);document.removeEventListener('visibilitychange',wake)}},[refresh]);
 async function markRead(selectedIds?:string[]){
  if(!data)return;
  const ids=selectedIds||data.items.map(item=>item.id);
  try{const r=await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});if(!r.ok)throw Error('Kunne ikke markere varsler som lest.');setData(current=>current?{items:current.items.map(item=>ids.includes(item.id)?{...item,unread:false}:item),unread:current.items.filter(item=>item.unread&&!ids.includes(item.id)).length}:current);setError('')}catch(e:any){setError(e.message)}
 }
 async function answer(item:Notice,accept:boolean){
  if(answering)return;setAnswering(item.id);setError('');
  try{const response=await fetch('/api/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item.kind==='friend'?{action:'answer-friend',user:item.user,accept}:{action:'answer-group',group:item.group,accept})});const result:any=await response.json();if(!response.ok)throw Error(result.error||'Kunne ikke svare.');toast.success(accept?(item.kind==='friend'?'Venneforespørselen er godtatt':'Du er med i gruppen'):'Forespørselen er avslått');await refresh();window.dispatchEvent(new Event('social-updated'))}catch(e:any){await refresh();setError(e.message)}finally{setAnswering('')}
 }
 function choose(item:Notice){void markRead([item.id]);setOpen(false);if(item.kind==='chat'&&item.room)onChat(item.room,item.message);else if((item.kind==='word-change'||item.kind==='difficulty-poll'))onWordChange();else if(item.hunt&&item.season)onHunt(item.hunt,item.season);else onSocial()}
 return <><button className="button header-inbox" aria-label={`Varsler${data?.unread?', '+data.unread+' uleste':''}`} onClick={()=>{setOpen(true);refresh()}}><Bell size={20}/>{!!data?.unread&&<span className="inbox-count">{data.unread>99?'99+':data.unread}</span>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="notification-inbox !max-w-lg max-h-[85dvh] overflow-y-auto"><div className="inbox-heading"><DialogTitle>Varsler</DialogTitle><button className="button inbox-settings" onClick={()=>{setOpen(false);onSettings()}} aria-label="Varslingsinnstillinger"><Settings2 size={18}/><span>Innstillinger</span></button></div><DialogDescription>Invitasjoner, meldinger og aktivitet – også når pushvarsler er av.</DialogDescription>{error&&<p className="error" role="alert">{error}<button className="button" onClick={()=>refresh()}>Prøv igjen</button></p>}{!data&&!error&&<LoadingBlock rows={4} label="Laster varsler"/>}{data&&<>{data.unread>0&&<button className="button" onClick={()=>markRead()}>Marker alle som lest</button>}{!data.items.length&&<p className="muted">Ingen varsler ennå. Nye invitasjoner og aktiviteter vises her.</p>}<div className="inbox-list">{data.items.map(item=>{const Icon=item.kind==='friend'?UserPlus:item.kind==='group'?Users:(item.kind==='comment'||item.kind==='reply'||item.kind==='chat')?MessageCircle:(item.kind==='word-change'||item.kind==='difficulty-poll')?Bell:Heart;return <div key={item.id} className={'inbox-notice'+(item.unread?' unread':'')}><button className={'inbox-item'+(item.unread?' unread':'')} onClick={()=>choose(item)}><Icon size={20}/><span><strong>{item.title}</strong><small>{item.detail}</small></span>{item.unread&&<span className="inbox-unread" aria-label="Ulest"/>}</button>{((item.kind==='friend'&&item.user)||(item.kind==='group'&&item.group))&&<div className="inbox-answer"><button className="primary" disabled={!!answering} aria-label={'Godta: '+item.title} onClick={()=>answer(item,true)}>{answering===item.id?'Lagrer …':'Godta'}</button><button className="button" disabled={!!answering} aria-label={'Avslå: '+item.title} onClick={()=>answer(item,false)}>Avslå</button></div>}</div>})}</div></>}</DialogContent></Dialog></>;
}
