'use client';
import {useState} from 'react';
type Participant={id:string;name:string;username?:string};
type Window={user:string;expires:number};
export function OwnerDeliveryTools({challenge,participants,windows,onChange}:{challenge:string;participants:Participant[];windows:Window[];onChange:()=>void}){
 const [user,setUser]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 async function open(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setSaved('');try{const r=await fetch('/api/admin-submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'open-delivery',challenge,user})}),j=await r.json() as {error?:string;expires:number};if(!r.ok)throw Error(j.error);setSaved('Ekstra levering er åpnet til '+new Date(j.expires).toLocaleTimeString('nb-NO',{timeZone:'Europe/Oslo',hour:'2-digit',minute:'2-digit',second:'2-digit'})+'.');onChange()}catch(e){setError(e instanceof Error?e.message:'Kunne ikke åpne levering.')}finally{setBusy(false)}}
 return <div className="panel"><h3>Åpne ekstra levering</h3><p>Gi én deltaker 10 minutter til å ta og levere et nytt bilde i den valgte jakten, også etter jaktens slutt. Gammelt bilde beholdes til ny levering lykkes. Ny levering erstatter bildet og tilhørende vurderinger, kommentarer og reaksjoner. Starttiden beholdes; korriger resultatet etterpå ved behov.</p><form onSubmit={open}><label className="field">Deltaker<select required value={user} onChange={e=>setUser(e.target.value)}><option value="">Velg deltaker</option>{participants.map(m=><option key={m.id} value={m.id}>{m.name}{m.username?' (@'+m.username+')':''}</option>)}</select></label><button className="primary" disabled={busy||!user}>{busy?'Åpner …':'Åpne for 10 minutter'}</button></form>{windows.map(w=><p key={w.user} className="muted">{participants.find(m=>m.id===w.user)?.name}: ekstra levering til {new Date(w.expires).toLocaleTimeString('nb-NO',{timeZone:'Europe/Oslo'})}</p>)}{saved&&<p role="status">{saved}</p>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
export function OwnerTimeCorrection({photo,onChange}:{photo:{id:string;elapsed:number;valid:number;note:string};onChange:()=>void}){
 const [open,setOpen]=useState(false),[seconds,setSeconds]=useState(String(photo.elapsed/1000)),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/admin-submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'correct-time',id:photo.id,seconds:Number(seconds.replace(',','.')),reason,expectedElapsed:photo.elapsed,expectedValid:!!photo.valid,expectedNote:photo.note||''})}),j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error);setOpen(false);onChange()}catch(e){setError(e instanceof Error?e.message:'Tiden kunne ikke lagres.')}finally{setBusy(false)}}
 return <div>{open?<form onSubmit={save}><label className="field">Jakttid i sekunder<input required inputMode="decimal" value={seconds} onChange={e=>setSeconds(e.target.value)} placeholder="23,583"/></label><label className="field">Begrunnelse for tidskorrigering<textarea required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="muted">Poeng og plassering oppdateres. Korrigeringen loggføres. Bildets gyldighet beholdes.</p><div className="actions"><button className="primary" disabled={busy||!reason.trim()}>{busy?'Lagrer …':'Lagre korrigert tid'}</button><button type="button" className="button" disabled={busy} onClick={()=>setOpen(false)}>Avbryt</button></div></form>:<button className="button" onClick={()=>{setSeconds(String(photo.elapsed/1000));setOpen(true)}}>Rediger tid</button>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
