'use client';
import {useEffect,useState,useRef} from 'react';
import {CloudUpload} from 'lucide-react';
import {toast} from 'sonner';
import {clearAttempt,listPhotos,savePhoto,deliverPhoto,notifyOutbox,prepareCamera,deletePhoto,deleteLease,type SavedPhoto} from '@/lib/photo-outbox';
export default function PhotoOutbox({user,challenges,refresh,onPending}:{user:string;challenges:any[];refresh:()=>Promise<any>;onPending:(photos:SavedPhoto[])=>void}){
 const [photos,setPhotos]=useState<SavedPhoto[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const running=useRef(false),refreshRef=useRef(refresh),pendingRef=useRef(onPending);refreshRef.current=refresh;pendingRef.current=onPending;
 useEffect(()=>{let alive=true;async function update(){try{const rows=await listPhotos(user);if(alive){setPhotos(rows);pendingRef.current(rows)}}catch{if(alive)setError('Lokal bildelagring er ikke tilgjengelig på denne enheten.')}}async function sync(){if(running.current||!navigator.onLine)return;running.current=true;try{const rows=await listPhotos(user);for(const p of rows.filter(p=>p.ready&&!p.blocked)){if(await deliverPhoto(p)){toast.success('Det lagrede bildet er levert. Den opprinnelige tiden er beholdt.');await refreshRef.current()}}}catch{}finally{running.current=false;await update()}}const change=()=>{update();sync()};change();window.addEventListener('online',change);window.addEventListener('photo-outbox',change);document.addEventListener('visibilitychange',change);const interval=setInterval(change,15000);return()=>{alive=false;clearInterval(interval);window.removeEventListener('online',change);window.removeEventListener('photo-outbox',change);document.removeEventListener('visibilitychange',change)}},[user]);
 useEffect(()=>{for(const photo of photos){const c=challenges.find(c=>c.id===photo.challenge);if(c?.daily&&!c.started&&!c.own)clearAttempt(user,c.id).catch(()=>{});}},[challenges,photos,user]);
 const active=challenges.filter(c=>!c.own&&c.eligible&&(!c.daily||c.started)&&c.start<=Date.now()&&c.end>Date.now()).map(c=>c.id+':'+(c.revision||0)).join(',');
 useEffect(()=>{for(const item of active.split(',').filter(Boolean)){const [id,revision]=item.split(':');prepareCamera(user,id,false,challenges.find(c=>c.id===id)?.started||challenges.find(c=>c.id===id)?.start,Number(revision)).catch(()=>{})}},[user,active]);
 useEffect(()=>{let alive=true;(async()=>{for(const p of await listPhotos(user)){const c=challenges.find(c=>c.id===p.challenge);if(alive&&c&&(c.revision||0)!==(p.revision||0)){await deletePhoto(p.id);await deleteLease(p.id);notifyOutbox();window.dispatchEvent(new Event('hunt-word-changed'))}}})().catch(()=>{});return()=>{alive=false}},[user,challenges]);
 async function send(p:SavedPhoto){setBusy(true);try{await savePhoto({...p,ready:true,blocked:false,error:undefined});notifyOutbox()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <>{error&&<p className="error" role="alert">{error}</p>}{photos.map(p=><section key={p.id} className="panel mt-3" aria-live="polite"><div className="flex gap-3 items-start"><CloudUpload size={22}/><div className="grow"><strong>{p.blocked?'Levering trenger oppfølging':p.ready?'Bildet venter på levering':'Bildet er lagret på enheten'}</strong><p className="muted">{p.title} · {(p.elapsed/1000).toFixed(3)} sekunder</p><p className="muted">{p.error||(p.ready?'Bildet og tiden er bevart. Vi prøver igjen når forbindelsen er tilbake. Hold appen åpen, eller åpne den igjen når du har nett.':'Trykk Lever bildet for å bekrefte innsendingen.')}</p><div className="actions"><button className="button" disabled={busy} onClick={()=>send(p)}>{p.ready?'Prøv igjen':'Lever bildet'}</button><button className="button" onClick={()=>{const url=URL.createObjectURL(p.photo),a=document.createElement('a');a.href=url;a.download='foto-jakt.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Lagre kopi</button></div></div></div></section>)}</>;
}
