'use client';
import {useEffect,useState,useRef} from 'react';
import {CloudUpload} from 'lucide-react';
import {toast} from 'sonner';
import {clearAttempt,listPhotos,savePhoto,deliverPhoto,notifyOutbox,prepareCamera,deletePhoto,deleteLease,type SavedPhoto} from '@/lib/photo-outbox';
type OutboxChallenge={id:string;own?:{id:string}|null;eligible:boolean;daily?:number|boolean;started?:number|null;start:number;end:number;revision?:number};
export default function PhotoOutbox({user,challenges,refresh,onPending,onReady,now}:{now:number;user:string;challenges:OutboxChallenge[];refresh:()=>Promise<unknown>;onPending:(photos:SavedPhoto[])=>void;onReady?:()=>void}){
 const [photos,setPhotos]=useState<SavedPhoto[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const nowRef=useRef(now);useEffect(()=>{nowRef.current=now},[now]);const running=useRef(false),refreshRef=useRef(refresh),pendingRef=useRef(onPending),readyRef=useRef(onReady);useEffect(()=>{refreshRef.current=refresh;pendingRef.current=onPending;readyRef.current=onReady},[refresh,onPending,onReady]);
 useEffect(()=>{let alive=true;async function update(){try{const rows=await listPhotos(user,nowRef.current);if(alive){setPhotos(rows);pendingRef.current(rows)}}catch{if(alive)setError('Lokal bildelagring er ikke tilgjengelig på denne enheten.')}finally{if(alive)readyRef.current?.()}}async function sync(){if(running.current||!navigator.onLine)return;running.current=true;try{const rows=await listPhotos(user,nowRef.current);for(const p of rows.filter(p=>p.ready&&!p.blocked)){if(await deliverPhoto(p)){toast.success('Det lagrede bildet er levert. Den opprinnelige tiden er beholdt.');await refreshRef.current()}}}catch{}finally{running.current=false;await update()}}const change=()=>{update();sync()};change();window.addEventListener('online',change);window.addEventListener('photo-outbox',change);document.addEventListener('visibilitychange',change);const interval=setInterval(change,15000);return()=>{alive=false;clearInterval(interval);window.removeEventListener('online',change);window.removeEventListener('photo-outbox',change);document.removeEventListener('visibilitychange',change)}},[user]);
 useEffect(()=>{for(const photo of photos){const c=challenges.find(c=>c.id===photo.challenge);if(c?.daily&&!c.started&&!c.own)clearAttempt(user,c.id).catch(()=>{});}},[challenges,photos,user]);
 const active=challenges.filter(c=>!c.own&&c.eligible&&(!c.daily||c.started)&&c.start<=now&&c.end>now).map(c=>[c.id,c.revision||0,c.started||c.start,c.end]);
 const activeKey=JSON.stringify(active);
 useEffect(()=>{for(const [id,revision,started,end] of JSON.parse(activeKey) as [string,number,number,number][]){prepareCamera(user,id,false,started,revision,end).catch(()=>{})}},[user,activeKey]);
 useEffect(()=>{let alive=true;(async()=>{for(const p of await listPhotos(user,nowRef.current)){const c=challenges.find(c=>c.id===p.challenge);if(alive&&c&&(c.revision||0)!==(p.revision||0)){await deletePhoto(p.id);await deleteLease(p.id);notifyOutbox();window.dispatchEvent(new Event('hunt-word-changed'))}}})().catch(()=>{});return()=>{alive=false}},[user,challenges]);
 async function send(p:SavedPhoto){setBusy(true);try{await savePhoto({...p,ready:true,blocked:false,error:undefined});notifyOutbox()}catch(error){setError(error instanceof Error?error.message:'Kunne ikke lagre bildet. Prøv igjen.')}finally{setBusy(false)}}
 return <>{error&&<p className="error" role="alert">{error}</p>}{photos.map(p=><section key={p.id} className="panel mt-3" aria-live="polite"><div className="flex gap-3 items-start"><CloudUpload size={22}/><div className="grow"><strong>{p.blocked?'Levering trenger oppfølging':p.ready?'Bildet venter på levering':'Bildet er lagret på enheten'}</strong><p className="muted">{p.title} · {(p.elapsed/1000).toFixed(3)} sekunder</p><p className="muted">{p.error||(p.ready?'Bildet og tiden er bevart. Vi prøver igjen når forbindelsen er tilbake. Hold appen åpen, eller åpne den igjen når du har nett.':'Trykk Lever bildet for å bekrefte innsendingen.')}</p><div className="actions"><button className="button" disabled={busy} onClick={()=>send(p)}>{p.ready?'Prøv igjen':'Lever bildet'}</button><button className="button" disabled={busy} onClick={async()=>{if(window.confirm('Fjerne dette lokale bildet fra køen? Lagre en kopi først hvis du vil beholde det.')){await clearAttempt(user,p.challenge);notifyOutbox()}}}>Fjern fra kø</button><button className="button" onClick={()=>{const url=URL.createObjectURL(p.photo),a=document.createElement('a');a.href=url;a.download='foto-jakt.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Lagre kopi</button></div></div></div></section>)}</>;
}
