'use client';
import {useCallback,useEffect,useState} from 'react';
type Decision={id:string;submission:string;kind:string;status:string;reason:string;appeal?:string;appealStatus?:string;resolution?:string};
export default function PlayerAppeal({submission,kind,onChange}:{submission:string;kind:'photo'|'bonus';onChange?:()=>unknown}){
 const [decision,setDecision]=useState<Decision|null>(null),[error,setError]=useState(''),[open,setOpen]=useState(false),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch('/api/appeals',{cache:'no-store'}),j=await r.json() as {decisions:Decision[];error?:string};if(!r.ok)throw Error(j.error);setDecision(j.decisions.find(d=>d.submission===submission&&d.kind===kind)||null);setError('')}catch(e){setError(e instanceof Error?e.message:'Klagestatus kunne ikke hentes.')}},[submission,kind]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 if(!decision&&!error)return null;
 return <div className="player-appeal">{error&&<p className="error" role="alert">{error}<button className="button" onClick={load}>Prøv igjen</button></p>}{decision&&<>{decision.status==='rejected'&&<p><strong>Avgjørelse:</strong> {decision.reason}</p>}{decision.appeal?<p role="status">{decision.appealStatus==='open'?'Klagen venter på en habil hoveddommer.':decision.appealStatus==='approved'?'Klagen er tatt til følge. Poengene er oppdatert.':decision.appealStatus==='withdrawn'?'Klagen er avsluttet fordi bonusvalget ble trukket tilbake.':'Klagen er avslått.'} {decision.resolution}</p>:decision.status==='rejected'&&(!open?<button className="button" onClick={()=>setOpen(true)}>Klag på avgjørelsen</button>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/appeals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision:decision.id,reason})}),j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error);setOpen(false);await load();await onChange?.()}catch(e){setError(e instanceof Error?e.message:'Klagen kunne ikke sendes.')}finally{setBusy(false)}}}><label className="field">Hvorfor bør avgjørelsen endres?<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="actions"><button className="primary" disabled={busy||!reason.trim()}>{busy?'Sender …':'Send klage til hoveddommer'}</button><button type="button" className="button" disabled={busy} onClick={()=>setOpen(false)}>Avbryt</button></div></form>)}</>}</div>;
}
