'use client';
import {TitleLabel} from './game-extras';
import {useState,useEffect,useRef} from 'react';
import {Trophy,ArrowUpRight} from 'lucide-react';
import {toast} from 'sonner';
import {LoadingBlock} from './loading-states';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function Scoreboard({data,onProfile}:{data:any,onProfile:(person:any)=>void}){
 const [open,setOpen]=useState(false),[season,setSeason]=useState(''),[scores,setScores]=useState<any>(data),[error,setError]=useState(''),[loading,setLoading]=useState(false),[group,setGroup]=useState(data.scoreboardGroup||'all'),[saving,setSaving]=useState(false);
 const pendingFilter=useRef<string|null>(null);
 useEffect(()=>{const saved=data.scoreboardGroup||'all';if(pendingFilter.current&&pendingFilter.current!==saved)return;pendingFilter.current=null;setGroup(saved)},[data.scoreboardGroup,data.user.id]);
 useEffect(()=>{if(!['all','my-groups','lightning'].includes(group)&&!data.groups?.some((g:any)=>g.id===group)){pendingFilter.current=null;setGroup('all')}},[group,data.groups]);
 useEffect(()=>{if(open&&(!season||season===data.season?.id)){setScores(data);setError('');setLoading(false)}},[open,season,data]);
 useEffect(()=>{if(!open||!season||season===data.season?.id)return;const controller=new AbortController();setLoading(true);setError('');async function refresh(){try{const r=await fetch('/api/hunt?season='+encodeURIComponent(season),{signal:controller.signal,cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);if(!controller.signal.aborted){setScores(j);setError('')}}catch(e:any){if(e.name!=='AbortError')setError(e.message)}finally{if(!controller.signal.aborted)setLoading(false)}}refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh()},15000);return()=>{controller.abort();clearInterval(timer)}},[open,season,data.season?.id]);
 async function changeGroup(value:string){const old=group;pendingFilter.current=value;setGroup(value);setSaving(true);try{const r=await fetch('/api/hunt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'leaderboard-filter',group:value})});const j:any=await r.json();if(!r.ok)throw Error(j.error);toast.success('Poengtavlefilteret er lagret')}catch(e:any){pendingFilter.current=null;setGroup(old);toast.error(e.message)}finally{setSaving(false)}}
 function filter(id:string){return <label className="scoreboard-filter" htmlFor={id}><span>Vis poeng for</span><select id={id} value={group} disabled={saving} onChange={e=>changeGroup(e.target.value)}><option value="all">Alle spillere i appen</option><option value="my-groups">Alle mine grupper</option><option value="lightning">⚡ Lynjakt</option>{(data.groups||[]).map((g:any)=><option key={g.id} value={g.id}>{g.name}</option>)}</select><small>Valget lagres på kontoen din.</small></label>}
 function board(source:any){return group==='all'?(source.leaderboard||[]):group==='my-groups'?(source.myGroupsLeaderboard||[]):group==='lightning'?(source.lightningBoard||[]):(source.groupLeaderboards?.[group]||[])}
 function rows(list:any[],compact=false){return <ol className={'scoreboard-list '+(compact?'scoreboard-compact':'')}>{list.map((m:any,i:number)=><li className="row" key={m.id}><span className="scoreboard-place">{i+1}</span><button className="scoreboard-person grow" onClick={()=>{setOpen(false);onProfile({id:m.id,name:m.name})}}><span className="scoreboard-name">{m.name}{m.id===data.user.id?' (deg)':''}</span><TitleLabel data={data} id={m.id}/>{!compact&&<small className="muted">{group==='lightning'?`${m.done} fullført`:`${m.wins} seire · ${m.done} fullført`}</small>}</button><strong className="score">{m.points} <small className="muted">p</small></strong></li>)}</ol>}
 const leaders=board(data).slice(0,5),groupName=group==='my-groups'?'Alle mine grupper':group==='lightning'?'⚡ Lynjakt':data.groups?.find((g:any)=>g.id===group)?.name;
 return <><section className="panel home-scoreboard"><div className="section-title !mt-0"><h2>Poengtavlen · topp 5</h2><Trophy size={20}/></div>{filter('home-scoreboard-group')}<p className="muted scoreboard-album">{data.season?.name||'Ingen album'} · {groupName||'Alle spillere'} · avsluttede jakter</p>{leaders.length?rows(leaders,true):<p className="muted">Poengene kommer når den første jakten er avsluttet.</p>}<button className="button w-full mt-3" onClick={()=>{setSeason(data.season?.id||'');setScores(data);setOpen(true)}}>Vis mer <ArrowUpRight size={16}/></button></section><Dialog open={open} onOpenChange={setOpen}><DialogContent className="!max-w-xl max-h-[85dvh] overflow-y-auto"><DialogTitle>Poengtavlen</DialogTitle><DialogDescription>{group==='all'?'Plasseringer blant alle spillerne i appen.':group==='my-groups'?'Felles plasseringer blant spillerne i alle gruppene dine. Hver spiller telles én gang.':group==='lightning'?'Lynjakt blant alle spillere: vinneren får 3 poeng, andre gyldige bilder gir 1 poeng.':'Plasseringer og poeng beregnet innen gruppen.'} Poeng fra avsluttede jakter.</DialogDescription>{filter('full-scoreboard-group')}<label className="field">Album<select value={season} onChange={e=>setSeason(e.target.value)}>{(data.seasons||[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}{s.end?' · avsluttet':''}</option>)}</select></label>{error&&<p className="error" role="alert">{error}</p>}{scores.season?.id!==season?(!error&&<LoadingBlock rows={5} label="Laster poeng"/>):board(scores).length?rows(board(scores)):<p className="muted">Ingen plasseringer ennå.</p>}</DialogContent></Dialog></>;
}
