'use client';
import {useState,useEffect} from 'react';
import {Trophy,ArrowUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function Scoreboard({data,onProfile}:{data:any,onProfile:(person:any)=>void}){
 const [open,setOpen]=useState(false),[season,setSeason]=useState(''),[scores,setScores]=useState<any>(data),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{if(open&&(!season||season===data.season?.id)){setScores(data);setError('');setLoading(false)}},[open,season,data]);
 useEffect(()=>{if(!open||!season||season===data.season?.id)return;const controller=new AbortController();setLoading(true);setError('');async function refresh(){try{const r=await fetch('/api/hunt?season='+encodeURIComponent(season),{signal:controller.signal,cache:'no-store'}),j:any=await r.json();if(!r.ok)throw Error(j.error);if(!controller.signal.aborted){setScores(j);setError('')}}catch(e:any){if(e.name!=='AbortError')setError(e.message)}finally{if(!controller.signal.aborted)setLoading(false)}}refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh()},15000);return()=>{controller.abort();clearInterval(timer)}},[open,season,data.season?.id]);

 function rows(source:any,compact=false){return <ol className={'scoreboard-list '+(compact?'scoreboard-compact':'')}>{(source.leaderboard||[]).map((m:any,i:number)=><li className="row" key={m.id}><span className="scoreboard-place">{i+1}</span><button className="scoreboard-person grow" onClick={()=>{setOpen(false);onProfile({id:m.id,name:m.name})}}><span className="scoreboard-name">{m.name}{m.id===data.user.id?' (deg)':''}</span>{!compact&&<small className="muted">{m.wins} seire · {m.done} fullført</small>}</button><strong className="score">{m.points} <small className="muted">p</small></strong></li>)}</ol>}
 const leaders={...data,leaderboard:(data.leaderboard||[]).slice(0,5)};
 return <><section className="panel home-scoreboard"><div className="section-title !mt-0"><h2>Poengtavlen · topp 5</h2><Trophy size={20}/></div><p className="muted scoreboard-album">{data.season?.name||'Ingen album'} · avsluttede jakter</p>{leaders.leaderboard.length?rows(leaders,true):<p className="muted">Poengene kommer når den første jakten er avsluttet.</p>}<button className="button w-full mt-3" onClick={()=>{setSeason(data.season?.id||'');setScores(data);setOpen(true)}}>Vis mer <ArrowUpRight size={16}/></button></section><Dialog open={open} onOpenChange={setOpen}><DialogContent className="!max-w-xl max-h-[85dvh] overflow-y-auto"><DialogTitle>Poengtavlen</DialogTitle><DialogDescription>Alle plasseringene blant dine venner og grupper. Poeng fra avsluttede jakter.</DialogDescription><label className="field">Album<select value={season} onChange={e=>setSeason(e.target.value)}>{(data.seasons||[]).map((s:any)=><option key={s.id} value={s.id}>{s.name}{s.end?' · avsluttet':''}</option>)}</select></label>{error?<p className="error" role="alert">{error}</p>:loading?<p className="muted">Laster poeng …</p>:scores.leaderboard?.length?rows(scores):<p className="muted">Ingen plasseringer ennå.</p>}</DialogContent></Dialog></>;
}
