'use client';
import {useState,useEffect,useRef} from 'react';
import {Share2,MessageCircle,Users} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
export default function SharePhoto({photo}:any){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(''),[rooms,setRooms]=useState<any[]|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),pending=useRef<{room:string,id:string}|null>(null);
 useEffect(()=>{if(!open)return;const abort=new AbortController();setRooms(null);setError('');fetch('/api/chat?summary=1',{cache:'no-store',signal:abort.signal}).then(async r=>{const j:any=await r.json();if(!r.ok)throw Error(j.error);if(!abort.signal.aborted)setRooms([j.publicRoom,...j.groups].filter(Boolean))}).catch(e=>{if(e.name!=='AbortError')setError('Kunne ikke hente chattene. Prøv igjen.')});return()=>abort.abort()},[open,retry]);
 async function share(room:any){if(busy)return;if(room.id==='public'&&!window.confirm('Bildet blir synlig for alle innloggede spillere i felleschatten. Vil du dele det?'))return;setBusy(room.id);setError('');if(pending.current?.room!==room.id)pending.current={room:room.id,id:crypto.randomUUID()};try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'send',...pending.current,photo:photo.id,body:''}),signal:AbortSignal.timeout(15000)}),j:any=await r.json();if(!r.ok)throw Error(j.error);pending.current=null;setOpen(false);window.dispatchEvent(new Event('chat-updated'));toast.success('Bildet er delt i '+room.name,{action:{label:'Åpne chat',onClick:()=>window.dispatchEvent(new CustomEvent('open-chat',{detail:{room:room.id,message:j.id}}))}})}catch(e:any){setError(e.name==='TimeoutError'||e.name==='TypeError'?'Ustabil forbindelse. Trykk samme chat for å prøve igjen.':e.message)}finally{setBusy('')}}
 return <><button className="button" type="button" onClick={()=>setOpen(true)}><Share2 size={17}/>Del til chat</button><Dialog open={open} onOpenChange={v=>{if(!busy)setOpen(v)}}><DialogContent className="!max-w-lg max-h-[85dvh] overflow-y-auto"><DialogTitle>Del bildet til {photo.name}</DialogTitle><DialogDescription>Velg en chat i Foto Jakt. Bare dine egne bilder kan deles. Nåværende og fremtidige medlemmer i chatten får se bildet. Slett delingsmeldingen for å trekke delingen tilbake. Jaktbilder kan deles når jakten er ferdig.</DialogDescription>{error&&<p className="error" role="alert">{error} <button className="button" onClick={()=>setRetry(n=>n+1)}>Prøv igjen</button></p>}{!rooms&&!error&&<p>Laster samtaler …</p>}<div className="chat-share-rooms">{rooms?.map(room=><button key={room.id} className="button" disabled={!!busy} onClick={()=>share(room)}>{room.kind==='friend'?<MessageCircle size={20}/>:<Users size={20}/>}<span>{room.name}<small>{busy===room.id?'Deler …':room.id==='public'?'Alle deltakere':room.kind==='friend'?'Vennechat':'Gruppechat'}</small></span></button>)}</div></DialogContent></Dialog></>;
}
