'use client';
import {useRef,useState} from 'react';
import {signaturePoint,validSignature,type SignatureData} from '@/lib/signature';
export function SignaturePreview({signature}:{signature:SignatureData}){
 return <svg viewBox="0 0 900 300" role="img" aria-label="Håndskrevet underskrift" className="signature-preview">{signature.map((stroke,i)=><polyline key={i} points={stroke.map(p=>`${p.x*900},${p.y*300}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>)}</svg>;
}
export default function SignaturePad({onChange,disabled=false}:{onChange:(value:SignatureData)=>void;disabled?:boolean}){
 const [strokes,setStrokes]=useState<SignatureData>([]),[drawing,setDrawing]=useState(false),active=useRef<number|null>(null),data=useRef<SignatureData>([]);
 function update(){const next=data.current.map(s=>s.map(p=>({...p})));setStrokes(next);onChange(active.current===null&&validSignature(next)?next:[]);}
 function finish(pointerId:number){if(active.current!==pointerId)return;active.current=null;setDrawing(false);update();}
 return <div className="signature-field"><p id="signature-help">Tegn din faktiske underskrift med finger, mus eller penn.</p><svg viewBox="0 0 900 300" className="signature-pad" preserveAspectRatio="none" role="img" aria-label="Signaturfelt – tegn underskriften din" aria-describedby="signature-help" onPointerDown={e=>{if(disabled||active.current!==null||!e.isPrimary||e.button!==0||data.current.length>=80)return;e.preventDefault();active.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);data.current.push([signaturePoint(e.clientX,e.clientY,e.currentTarget.getBoundingClientRect())]);setDrawing(true);update();}} onPointerMove={e=>{if(active.current!==e.pointerId)return;e.preventDefault();if(data.current.reduce((n,s)=>n+s.length,0)>=6000)return;const coalesced=e.nativeEvent.getCoalescedEvents?.();const events=coalesced?.length?coalesced:[e.nativeEvent];for(const p of events){if(data.current.reduce((n,s)=>n+s.length,0)>=6000)break;data.current.at(-1)!.push(signaturePoint(p.clientX,p.clientY,e.currentTarget.getBoundingClientRect()));}update();}} onPointerUp={e=>finish(e.pointerId)} onPointerCancel={e=>finish(e.pointerId)} onLostPointerCapture={e=>finish(e.pointerId)}>{strokes.map((stroke,i)=><polyline key={i} points={stroke.map(p=>`${p.x*900},${p.y*300}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>)}</svg><div className="actions"><button type="button" className="button" disabled={disabled||drawing||!strokes.length} onClick={()=>{data.current=[];active.current=null;setStrokes([]);onChange([]);}}>Tøm signaturen</button><small role="status">{drawing?'Tegner …':validSignature(strokes)?'Signaturen er klar.':'Underskriften må tegnes før du kan signere.'}</small></div></div>;
}
