'use client';
import {useState,useEffect,useCallback} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
import GroupShare from './group-link';
export default function Social({user,onProfile,onGroup,admin=false,adminAct,initialGroup}:any){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[results,setResults]=useState<any[]>([]),[name,setName]=useState(''),[report,setReport]=useState<any>(null),[reason,setReason]=useState(''),[selected,setSelected]=useState(''),[inviteQuery,setInviteQuery]=useState(''),[removeFriend,setRemoveFriend]=useState<any>(null);
 useEffect(()=>{if(initialGroup)setSelected(initialGroup);const joined=(e:Event)=>setSelected((e as CustomEvent).detail);window.addEventListener('group-link-joined',joined);return()=>window.removeEventListener('group-link-joined',joined)},[initialGroup]);
 useEffect(()=>setInviteQuery(''),[selected]);
 const refresh=useCallback(async(propagate=false)=>{try{const r=await fetch('/api/social');const j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j)}catch(e:any){if(propagate)throw e;toast.error(e.message)}},[]);
 useEffect(()=>{refresh();const t=setInterval(()=>refresh(),15000);const pull=(e:Event)=>(e as CustomEvent).detail.tasks.push(refresh(true));window.addEventListener('foto-jakt-refresh',pull);return()=>{clearInterval(t);window.removeEventListener('foto-jakt-refresh',pull)}},[refresh]);
 useEffect(()=>{if(q.trim().length<2){setResults([]);return}const controller=new AbortController();const t=setTimeout(async()=>{try{const r=await fetch('/api/social?q='+encodeURIComponent(q),{signal:controller.signal});const j:any=await r.json();if(!r.ok)throw Error(j.error);setResults(j.users)}catch(e:any){if(e.name!=='AbortError')toast.error(e.message)}},350);return()=>{clearTimeout(t);controller.abort()}},[q]);
 async function act(body:any,message='Lagret'){setBusy(true);try{const r=await fetch('/api/social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j:any=await r.json();if(!r.ok)throw Error(j.error);await refresh();toast.success(message);return true}catch(e:any){toast.error(e.message);return false}finally{setBusy(false)}}
 if(!data)return <p>Laster venner og grupper …</p>;
 const friends=data.friends.filter((f:any)=>f.status==='accepted'),incoming=data.friends.filter((f:any)=>f.status==='pending'&&f.requester!==user.id),outgoing=data.friends.filter((f:any)=>f.status==='pending'&&f.requester===user.id),group=data.groups.find((g:any)=>g.id===selected);
 const inviteTerm=inviteQuery.trim().toLocaleLowerCase('nb-NO').replace(/^@/,'');
 const inviteMatches=group&&inviteTerm.length>=2?friends.filter((p:any)=>!group.members.some((m:any)=>m.id===p.id)&&((p.name||'').toLocaleLowerCase('nb-NO').includes(inviteTerm)||(p.username||'').toLocaleLowerCase('nb-NO').includes(inviteTerm))):[];
 const person=(p:any)=><div className="social-person"><button className="profile-link friend-profile-link" aria-label={`Åpne profilen til ${p.name}`} onClick={()=>{setSelected('');onProfile?.(p)}}><FriendAvatar person={p}/><span className="friend-person-name"><strong>{p.name}</strong><small>@{p.username||'bruker'}</small></span></button>{p.id!==user.id&&<button className="button" onClick={()=>{setReport(p);setReason('')}}>Rapporter</button>}</div>;
 if(admin)return <section className="panel"><h2>Brukerrapporter</h2>{!data.reports.length?<p>Ingen åpne rapporter.</p>:data.reports.map((r:any)=><div className="row" key={r.id}><div className="grow"><strong>{r.name} · @{r.username}</strong><p className="whitespace-pre-wrap">{r.reason}</p><small>Fra {r.reporterName||'slettet konto'}</small><div className="actions"><button disabled={busy||r.status==='blocked'} className="button !text-red-700" onClick={async()=>{if(await adminAct({action:'member',id:r.target,status:'blocked'},'Brukeren er svartelistet'))refresh()}}>Svartelist bruker</button><button className="button" disabled={busy} onClick={()=>act({action:'resolve-report',id:r.id},'Rapporten er behandlet')}>Marker behandlet</button></div></div></div>)}</section>;
 return <div className="social-layout">
 <section className="panel"><h2>Mine venner ({friends.length})</h2>{friends.map((p:any)=><div className="social-row" key={p.id}>{person(p)}<button className="button" disabled={busy} onClick={()=>setRemoveFriend(p)}>Fjern venn</button></div>)}{!friends.length&&<p className="muted">Ingen venner ennå. Finn en venn med søket under.</p>}</section>

 <section className="panel"><h2>Finn venner</h2><label className="field"><span className="sr-only">Søk etter folk</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Navn eller brukernavn" maxLength={40}/></label>{q.trim().length>=2&&!results.length&&<p>Ingen treff.</p>}{results.map(p=>{const f=data.friends.find((f:any)=>f.id===p.id);return <div className="social-row" key={p.id}>{person(p)}<button className="button" disabled={busy||!!f} onClick={()=>act({action:'friend-request',user:p.id},'Venneforespørselen er sendt')}>{f?f.status==='accepted'?'Venner':'Forespørsel venter':'Legg til venn'}</button></div>})}</section>
 {(incoming.length>0||outgoing.length>0||data.invitations.length>0)&&<section className="panel"><h2>Forespørsler og invitasjoner</h2>{!incoming.length&&!outgoing.length&&!data.invitations.length&&<p>Ingen forespørsler akkurat nå.</p>}{incoming.map((p:any)=><div className="social-row" key={p.id}>{person(p)}<div className="actions"><button className="primary" disabled={busy} onClick={()=>act({action:'answer-friend',user:p.id,accept:true},'Dere er nå venner')}>Godta venn</button><button className="button" disabled={busy} onClick={()=>act({action:'answer-friend',user:p.id,accept:false},'Forespørselen er avslått')}>Avslå</button></div></div>)}{outgoing.map((p:any)=><div className="social-row" key={p.id}>{person(p)}<button className="button" disabled={busy} onClick={()=>act({action:'remove-friend',user:p.id},'Forespørselen er trukket tilbake')}>Trekk tilbake</button></div>)}{data.invitations.map((g:any)=><div className="social-row" key={g.id}><strong>{g.name}</strong><p>Invitert av {g.inviter}</p><div className="actions"><button className="primary" disabled={busy} onClick={()=>act({action:'answer-group',group:g.id,accept:true},'Du er med i gruppen')}>Bli med</button><button className="button" disabled={busy} onClick={()=>act({action:'answer-group',group:g.id,accept:false},'Invitasjonen er avslått')}>Avslå</button></div></div>)}</section>
 }
 <section className="panel"><h2>Mine grupper</h2>{data.groups.map((g:any)=><button key={g.id} className="row w-full text-left" onClick={()=>setSelected(g.id)}><span className="grow"><strong>{g.name}</strong><p>{g.members.length} medlemmer · {g.owner===user.id?'Du er eier':g.role==='admin'?'Administrator':'Medlem'}</p></span><span>Åpne</span></button>)}<details className="compact-details create-group-details"><summary>Opprett gruppe</summary><form onSubmit={async e=>{e.preventDefault();if(await act({action:'create-group',name},'Gruppen er opprettet'))setName('')}}><label className="field">Opprett en gruppe<input value={name} onChange={e=>setName(e.target.value)} maxLength={60} required placeholder="Venner på tur"/></label><button className="primary" disabled={busy||!name.trim()}>Opprett gruppe</button></form></details></section>
 <Dialog open={!!group} onOpenChange={o=>!o&&setSelected('')}><DialogContent className="!max-w-xl max-h-[90dvh] overflow-y-auto"><DialogTitle>{group?.name}</DialogTitle><DialogDescription>Eieren og gruppeadministratorer kan invitere og fjerne medlemmer. Kun eieren kan endre roller. Bilder deles etter egen innlevering eller når jakten er over.</DialogDescription>{group&&<><button className="primary" onClick={()=>{onGroup?.(group);setSelected('')}}>Se gruppens bilder</button>{group.members.map((p:any)=><div className="social-row" key={p.id}>{person(p)}{p.id===group.owner?<span className="badge">Gruppeeier</span>:(group.owner===user.id||(group.canManage&&p.role!=='admin'&&p.id!==user.id))&&<button className="button" disabled={busy} onClick={()=>act({action:'remove-group-member',group:group.id,user:p.id},'Medlemmet er fjernet fra gruppen')}>Fjern fra gruppen</button>}{p.id!==group.owner&&<div className="actions">{p.role==='admin'&&<span className="badge">Gruppeadministrator</span>}{group.owner===user.id&&<button className="button" disabled={busy} onClick={()=>act({action:'group-role',group:group.id,user:p.id,role:p.role==='admin'?'member':'admin'},p.role==='admin'?'Adminrollen er fjernet':'Gruppeadministrator er utnevnt')}>{p.role==='admin'?'Fjern adminrolle':'Gjør til administrator'}</button>}</div>}</div>)}{group.canManage?<><GroupShare group={group} onChange={()=>refresh()}/><h3>Inviter venner</h3><label className="field">Søk etter en venn<input type="search" value={inviteQuery} onChange={e=>setInviteQuery(e.target.value)} placeholder="Navn eller @brukernavn" maxLength={40} autoComplete="off"/></label><p className="muted" role="status">{inviteTerm.length<2?'Skriv minst 2 tegn for å finne venner du kan invitere.':inviteMatches.length?`${inviteMatches.length} treff`:'Ingen venner funnet. Personen kan allerede være med i gruppen.'}</p>{inviteMatches.slice(0,20).map((p:any)=>{const invited=group.invites.some((i:any)=>i.user===p.id);return <div className="social-row invite-result" key={p.id}><div className="invite-person"><strong>{p.name}</strong><small>@{p.username}</small></div><button className="button" disabled={busy} onClick={()=>act({action:invited?'cancel-invite':'invite-group',group:group.id,user:p.id},invited?'Invitasjonen er trukket tilbake':'Invitasjonen er sendt')}>{invited?'Trekk tilbake':'Inviter'}</button></div>})}<p className="muted">{inviteMatches.length>20?'Viser de første 20 treffene. Skriv mer for å snevre inn. ':''}Legg til personen som venn først. Vedkommende må godta invitasjonen.</p>{group.owner!==user.id&&<button className="button" disabled={busy} onClick={async()=>{if(await act({action:'leave-group',group:group.id},'Du har forlatt gruppen'))setSelected('')}}>Forlat gruppen</button>}</>:<button className="button" disabled={busy} onClick={async()=>{if(await act({action:'leave-group',group:group.id},'Du har forlatt gruppen'))setSelected('')}}>Forlat gruppen</button>}</>}</DialogContent></Dialog>
 <Dialog open={!!removeFriend} onOpenChange={o=>!o&&!busy&&setRemoveFriend(null)}><DialogContent><DialogTitle>Fjerne {removeFriend?.name} som venn?</DialogTitle><DialogDescription>Dere blir fjernet fra hverandres venneliste. Medlemskap i felles grupper beholdes. Bilder er fortsatt synlige hvis dere deler en gruppe.</DialogDescription><div className="actions"><button className="button" disabled={busy} onClick={()=>setRemoveFriend(null)}>Avbryt</button><button className="primary" disabled={busy} onClick={async()=>{if(await act({action:'remove-friend',user:removeFriend.id},'Vennskapet er fjernet'))setRemoveFriend(null)}}>{busy?'Fjerner …':'Fjern venn'}</button></div></DialogContent></Dialog>
 <Dialog open={!!report} onOpenChange={o=>!o&&setReport(null)}><DialogContent><DialogTitle>Rapporter {report?.name}</DialogTitle><DialogDescription>Rapporten sendes til administrator. Forklar hva som har skjedd.</DialogDescription><form onSubmit={async e=>{e.preventDefault();if(await act({action:'report-user',user:report.id,reason},'Rapporten er sendt'))setReport(null)}}><label className="field">Begrunnelse<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary" disabled={busy||!reason.trim()}>Send rapport</button></form></DialogContent></Dialog>
 </div>;
}

function FriendAvatar({person:p}:any){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[p.id,p.avatarVersion]);return <span className="avatar user-avatar friend-avatar">{p.avatarVersion&&!failed?<img src={'/api/avatar/'+encodeURIComponent(p.id)+'?v='+p.avatarVersion} alt="" loading="lazy" onError={()=>setFailed(true)}/>:String(p.name||'?').slice(0,1).toUpperCase()}</span>}
