export const ADMIN_AGREEMENT_VERSION='2026-10-08.2';
export const ADMIN_AGREEMENT_TEXT=`Taushetserklæring for Foto Jakt
Jeg bruker administratortilgangen bare til nødvendige driftsoppgaver og behandling av saker jeg har fått ansvar for. Jeg åpner ikke privat innhold av nysgjerrighet.
Jeg holder brukeropplysninger, bilder, meldinger, rapporter og sikkerhetsinformasjon fortrolig. Jeg kopierer, laster ned eller deler ikke opplysninger uten et konkret, autorisert behov. Jeg bruker ikke opplysningene privat eller til andre formål.
Jeg deler ikke innloggingen min. Jeg låser enheten, beskytter kontoen og melder straks mulig misbruk, feil tilgang eller datalekkasje til Andreas Danielsen på anddan2004@icloud.com.
Jeg følger instruksene for moderering, dokumenterer avgjørelser saklig og melder habilitetskonflikter. AI-resultater er ikke en garanti for at innhold bryter reglene.
Ved avsluttet tilgang skal jeg slette eller tilbakelevere eventuelle autoriserte lokale kopier etter instruks. Taushetsplikten fortsetter etter at tilgangen opphører.
Jeg vurderer aldri mine egne bilder eller klager på mine egne avgjørelser. Jeg trekker meg fra saker der personlige relasjoner eller andre interesser kan påvirke vurderingen, og overlater saken til en habil kollega. Jeg bruker ikke tilgangen til å påvirke konkurransen eller skaffe meg fordeler.
Fullt navn, håndskrevet signatur, bruker-ID, rolle, tidspunkt og erklæringsversjon registreres for å dokumentere aksept. E-post og postadresse kreves ikke. Bare jeg og eieren kan hente min signerte erklæring. Teamansvarlige ser signeringsstatus, dato og versjon. Tidligere signeringer beholdes mens rollen er aktiv, og slettes normalt 90 dager etter at rollen fjernes. Kontakt anddan2004@icloud.com for innsyn, retting eller sletting.
Ved å tegne min faktiske underskrift og velge «Signer og godta» bekrefter jeg at jeg har lest og akseptert erklæringen. Signaturen dokumenterer aksept fra innlogget konto. Den er ikke BankID-verifisert og bekrefter ikke identiteten på tilsvarende måte.`;
