import {cookies,headers} from 'next/headers';
import {env} from 'cloudflare:workers';
import {one,run,db,fail,str} from './server';
import {roleFor} from './staff';
const hex=(b:ArrayBuffer)=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
export const digest=async(s:string)=>hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
export const loginName=(s:any)=>str(s,40).normalize('NFKC').toLocaleLowerCase('nb-NO');
export async function pinHash(pin:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:100000},key,256))}
export function validatePin(pin:any){if(typeof pin!=='string'||!/^\d{6}$/.test(pin))fail('Velg en personlig PIN med 6 sifre.');return pin}
// Native apps may send the same login token as a bearer token. Browsers can't add this header cross-site without CORS.
export async function loginToken(){return (await headers()).get('authorization')?.match(/^Bearer ([A-Za-z0-9-]{20,200})$/)?.[1]||(await cookies()).get('hunt_login')?.value}
export async function currentUser(){const token=await loginToken();if(!token)return null;const m=await one('SELECT m.* FROM login_sessions s JOIN members m ON m.id=s.user WHERE s.token=? AND s.expires>?',await digest(token),Date.now());return m?{userId:m.id,email:m.email,fullName:m.name}:null}
export async function limit(req:Request,key:string,max=8){const now=Date.now();const id='auth:'+await digest(key);const result=await db().prepare('INSERT INTO attempts(id,count,until) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN until<=? THEN 1 ELSE count+1 END,until=CASE WHEN until<=? THEN ? ELSE until END RETURNING count').bind(id,now+900000,now,now,now+900000).first();if(result.count>max)fail('For mange forsøk. Prøv igjen om 15 minutter.',429)}
export async function session(user:string,admin=false,native=false){admin=await roleFor(user)!=='player';const now=Date.now(),token=crypto.randomUUID()+crypto.randomUUID();await run('INSERT INTO login_sessions(token,user,expires) VALUES (?,?,?)',await digest(token),user,now+90*86400000);const headers=new Headers({'Content-Type':'application/json','Cache-Control':'no-store'});headers.append('Set-Cookie',`hunt_login=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=7776000`);if(admin){const t=crypto.randomUUID();await run('INSERT INTO sessions(token,user,expires) VALUES (?,?,?)',await digest(t),user,now+28800000);headers.append('Set-Cookie',`hunt_admin=${t}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800`)}else headers.append('Set-Cookie','hunt_admin=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0');return new Response(JSON.stringify(native?{ok:true,token}:{ok:true}),{headers})}
export async function owner(){let o=await one('SELECT value FROM settings WHERE key=?','owner');if(!o){const existing=await one('SELECT id FROM members WHERE admin=1 ORDER BY joined LIMIT 1');await run('INSERT OR IGNORE INTO settings(key,value) VALUES (?,?)','owner',existing?.id||'administrator');o=await one('SELECT value FROM settings WHERE key=?','owner')}const now=Date.now();await run('INSERT INTO members(id,name,email,status,joined,approved,admin) VALUES (?,?,?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET status=?,admin=1,approved=COALESCE(approved,?)',o.value,'Andreas',String((env as any).ADMIN_EMAIL||''),'approved',now,now,'approved',now);return o.value}
