import {one,run} from './server';
// Dictionary text is fetched from UiB, never generated by the assessment model.
export function dictionaryExplanations(article:any):string[]{
 const result:string[]=[];
 function walk(nodes:any,depth=0){if(!Array.isArray(nodes)||depth>12)return;for(const node of nodes){if(node?.type_==='explanation'&&typeof node.content==='string'&&!node.content.includes('$')){const text=node.content.trim();if(text&&text.length<=400&&!result.includes(text))result.push(text)}walk(node?.elements,depth+1)}}
 walk(article?.body?.definitions);return result.slice(0,6);
}
export async function dictionaryForWord(word:string){
 const link='https://ordbokene.no/bm/search?q='+encodeURIComponent(word)+'&scope=ei';
 const key='word-dictionary:v1:'+word,now=Date.now(),cached=await one('SELECT value FROM settings WHERE key=?',key);
 if(cached){try{const entry=JSON.parse(cached.value);if(entry.expires>now)return entry.result}catch{}}
 const request=async(url:string)=>{const r=await fetch(url,{signal:AbortSignal.timeout(5000),headers:{Accept:'application/json'}});if(!r.ok)throw Error('dictionary-unavailable');return r.json() as Promise<any>};
 try{
  const index=await request('https://ord.uib.no/api/articles?w='+encodeURIComponent(word)+'&dict=bm&scope=e');
  const ids=(Array.isArray(index?.articles?.bm)?index.articles.bm:[]).filter((id:any)=>Number.isSafeInteger(id)&&id>0).slice(0,3);
  const articles=await Promise.all(ids.map((id:number)=>request('https://ord.uib.no/bm/article/'+id+'.json')));
  const definitions=[...new Set(articles.flatMap(dictionaryExplanations))].slice(0,6);
  const result={link,definitions,unavailable:false};
  await run('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,JSON.stringify({expires:now+7*86400000,result}));return result;
 }catch{return {link,definitions:[],unavailable:true}}
}
