import {sql} from 'drizzle-orm';
import {integer,sqliteTable,text,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const usageActivity=sqliteTable('usage_activity',{user:text('user').primaryKey(),lastSeen:integer('last_seen').notNull()});
export const usageDaily=sqliteTable('usage_daily',{day:text('day').notNull(),user:text('user').notNull(),event:text('event').notNull(),count:integer('count').notNull().default(0)},t=>[uniqueIndex('idx_usage_daily').on(t.day,t.user,t.event),index('idx_usage_day').on(t.day)]);
export const members=sqliteTable('members',{id:text('id').primaryKey(),name:text('name').notNull(),username:text('username').unique(),email:text('email').notNull(),status:text('status').notNull().default('pending'),joined:integer('joined').notNull(),approved:integer('approved'),admin:integer('admin').notNull().default(0)});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const sessions=sqliteTable('sessions',{token:text('token').primaryKey(),user:text('user').notNull(),expires:integer('expires').notNull()});
export const attempts=sqliteTable('attempts',{id:text('id').primaryKey(),count:integer('count').notNull(),until:integer('until').notNull()});
export const seasons=sqliteTable('seasons',{id:text('id').primaryKey(),name:text('name').notNull(),start:integer('start').notNull(),end:integer('end'),daily:integer('daily').notNull().default(0),firstDay:text('first_day'),lastDay:text('last_day')});
export const challenges=sqliteTable('challenges',{id:text('id').primaryKey(),season:text('season').notNull(),title:text('title').notNull(),details:text('details').notNull().default(''),start:integer('start'),end:integer('end'),duration:integer('duration').notNull(),created:integer('created').notNull(),revision:integer('revision').notNull().default(0),daily:integer('daily').notNull().default(0),day:text('day'),slot:integer('slot').notNull().default(0)},t=>[uniqueIndex('idx_daily_slot').on(t.day,t.slot).where(sql`${t.daily}=1`),index('idx_challenges_season_start').on(t.season,t.start)]);
export const submissions=sqliteTable('submissions',{id:text('id').primaryKey(),challenge:text('challenge').notNull(),user:text('user').notNull(),key:text('key').notNull(),submitted:integer('submitted').notNull(),elapsed:integer('elapsed').notNull(),valid:integer('valid').notNull().default(1),note:text('note').notNull().default(''),caption:text('caption').notNull().default('')},t=>[uniqueIndex('idx_submission_challenge_user').on(t.challenge,t.user)]);
export const captures=sqliteTable('captures',{token:text('token').primaryKey(),user:text('user').notNull(),challenge:text('challenge').notNull(),expires:integer('expires').notNull(),used:integer('used').notNull().default(0),taken:integer('taken'),issued:integer('issued'),revision:integer('revision').notNull().default(0)});
export const reactions=sqliteTable('reactions',{id:text('id').primaryKey(),submission:text('submission').notNull(),user:text('user').notNull(),emoji:text('emoji').notNull()},t=>[uniqueIndex('idx_reactions_unique').on(t.submission,t.user)]);
export const pushSubscriptions=sqliteTable('push_subscriptions',{id:text('id').primaryKey(),user:text('user').notNull(),endpoint:text('endpoint').notNull(),p256dh:text('p256dh').notNull(),auth:text('auth').notNull(),created:integer('created').notNull(),updated:integer('updated').notNull(),provider:text('provider').notNull().default('webpush')},t=>[uniqueIndex('idx_push_endpoint').on(t.endpoint),index('idx_push_user').on(t.user)]);
export const pushDeliveries=sqliteTable('push_deliveries',{id:text('id').primaryKey(),subscription:text('subscription').notNull(),challenge:text('challenge').notNull(),kind:text('kind').notNull(),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),nextAttempt:integer('next_attempt').notNull().default(0),created:integer('created').notNull(),sent:integer('sent'),lastStatus:integer('last_status')});

export const localAccounts=sqliteTable('local_accounts',{user:text('user').primaryKey(),login:text('login').notNull().unique(),salt:text('salt').notNull(),hash:text('hash').notNull()});
export const loginSessions=sqliteTable('login_sessions',{token:text('token').primaryKey(),user:text('user').notNull(),expires:integer('expires').notNull()},t=>[index('idx_login_user').on(t.user)]);

export const starts=sqliteTable('starts',{challenge:text('challenge').notNull(),user:text('user').notNull(),started:integer('started').notNull()},t=>[uniqueIndex('idx_starts_user_challenge').on(t.user,t.challenge)]);

export const comments=sqliteTable('comments',{id:text('id').primaryKey(),submission:text('submission').notNull(),user:text('user').notNull(),body:text('body').notNull(),parent_id:text('parent_id'),replyTo:text('reply_to'),deleted:integer('deleted').notNull().default(0),created:integer('created').notNull()},t=>[index('idx_comments_submission').on(t.submission,t.created)]);

export const avatars=sqliteTable('avatars',{user:text('user').primaryKey(),key:text('key').notNull(),updated:integer('updated').notNull()});

export const notificationPreferences=sqliteTable('notification_preferences',{user:text('user').primaryKey(),comments:integer('comments').notNull().default(0),reactions:integer('reactions').notNull().default(0),replies:integer('replies').notNull().default(0),friends:integer('friends').notNull().default(1),groups:integer('groups').notNull().default(1)});
export const socialPush=sqliteTable('social_push',{id:text('id').primaryKey(),subscription:text('subscription').notNull(),submission:text('submission').notNull(),actor:text('actor').notNull(),kind:text('kind').notNull(),source:text('source').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull(),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),nextAttempt:integer('next_attempt').notNull().default(0)},t=>[index('idx_social_pending').on(t.status,t.nextAttempt)]);

export const photoReports=sqliteTable('photo_reports',{submission:text('submission').primaryKey(),reporter:text('reporter').notNull(),reason:text('reason').notNull(),created:integer('created').notNull(),deadline:integer('deadline').notNull(),status:text('status').notNull().default('open'),threshold:integer('threshold').notNull(),applied:integer('applied').notNull().default(0)});
export const photoVoters=sqliteTable('photo_voters',{submission:text('submission').notNull(),user:text('user').notNull()},t=>[uniqueIndex('idx_photo_voter').on(t.submission,t.user)]);
export const photoVotes=sqliteTable('photo_votes',{submission:text('submission').notNull(),user:text('user').notNull(),choice:text('choice').notNull(),created:integer('created').notNull()},t=>[uniqueIndex('idx_photo_vote').on(t.submission,t.user)]);

export const groups=sqliteTable('groups',{id:text('id').primaryKey(),name:text('name').notNull(),owner:text('owner').notNull(),created:integer('created').notNull()});
export const groupMembers=sqliteTable('group_members',{groupId:text('group_id').notNull(),user:text('user').notNull(),role:text('role').notNull().default('member'),joined:integer('joined').notNull(),chatNotifications:integer('chat_notifications').notNull().default(1),readCreated:integer('read_created').notNull().default(0),readId:text('read_id').notNull().default('')},t=>[uniqueIndex('idx_group_member').on(t.groupId,t.user)]);
export const groupInvites=sqliteTable('group_invites',{groupId:text('group_id').notNull(),user:text('user').notNull(),inviter:text('inviter').notNull(),created:integer('created').notNull()},t=>[uniqueIndex('idx_group_invite').on(t.groupId,t.user)]);
export const friendships=sqliteTable('friendships',{a:text('a').notNull(),b:text('b').notNull(),requester:text('requester').notNull(),status:text('status').notNull().default('pending'),created:integer('created').notNull()},t=>[uniqueIndex('idx_friend_pair').on(t.a,t.b)]);
export const userReports=sqliteTable('user_reports',{id:text('id').primaryKey(),reporter:text('reporter').notNull(),target:text('target').notNull(),reason:text('reason').notNull(),created:integer('created').notNull(),resolved:integer('resolved').notNull().default(0)});

export const wordSuggestions=sqliteTable('word_suggestions',{id:text('id').primaryKey(),user:text('user').notNull(),word:text('word').notNull(),status:text('status').notNull().default('pending'),aiStatus:text('ai_status').notNull().default('pending'),aiReason:text('ai_reason').notNull().default(''),aiReviewed:integer('ai_reviewed'),created:integer('created').notNull()},t=>[index('idx_word_status').on(t.status),uniqueIndex('idx_word_suggestion').on(t.user,t.word)]);
export const favoritePolls=sqliteTable('favorite_polls',{id:text('id').primaryKey(),groupId:text('group_id').notNull(),season:text('season').notNull(),day:text('day').notNull(),opens:integer('opens').notNull(),closes:integer('closes').notNull(),settled:integer('settled').notNull().default(0)},t=>[uniqueIndex('idx_favorite_day_group').on(t.groupId,t.day)]);
export const favoriteCandidates=sqliteTable('favorite_candidates',{token:text('token').primaryKey(),poll:text('poll').notNull(),submission:text('submission').notNull(),winner:integer('winner').notNull().default(0)},t=>[uniqueIndex('idx_favorite_candidate').on(t.poll,t.submission)]);
export const favoriteVotes=sqliteTable('favorite_votes',{poll:text('poll').notNull(),user:text('user').notNull(),candidate:text('candidate').notNull(),created:integer('created').notNull()},t=>[uniqueIndex('idx_favorite_vote').on(t.poll,t.user),index('idx_favorite_vote_candidate').on(t.candidate)]);

export const featureSuggestions=sqliteTable('feature_suggestions',{id:text('id').primaryKey(),user:text('user').notNull(),title:text('title').notNull(),body:text('body').notNull(),status:text('status').notNull().default('new'),created:integer('created').notNull()},t=>[index('idx_feature_user_created').on(t.user,t.created)]);

export const huntChanges=sqliteTable('hunt_changes',{kind:text('kind').notNull().default('word-change'),poll:text('poll'),id:text('id').primaryKey(),challenge:text('challenge').notNull(),user:text('user').notNull(),revision:integer('revision').notNull(),created:integer('created').notNull()},t=>[index('idx_hunt_changes_user').on(t.user,t.created)]);
export const difficultyPolls=sqliteTable('difficulty_polls',{id:text('id').primaryKey(),challenge:text('challenge').notNull(),word:text('word').notNull(),revision:integer('revision').notNull(),actor:text('actor').notNull(),created:integer('created').notNull(),deadline:integer('deadline').notNull(),status:text('status').notNull().default('open'),settledAt:integer('settled_at')},t=>[uniqueIndex('idx_difficulty_open').on(t.challenge).where(sql`${t.status}='open'`)]);
export const difficultyVotes=sqliteTable('difficulty_votes',{poll:text('poll').notNull(),user:text('user').notNull(),choice:text('choice').notNull(),created:integer('created').notNull()},t=>[uniqueIndex('idx_difficulty_vote').on(t.poll,t.user)]);
export const chatMessages=sqliteTable('chat_messages',{id:text('id').primaryKey(),room:text('room').notNull(),user:text('user').notNull(),body:text('body').notNull(),created:integer('created').notNull(),replyTo:text('reply_to'),sharedPhoto:text('shared_photo'),updateTitle:text('update_title'),updateIcon:text('update_icon')},t=>[index('idx_chat_room_created').on(t.room,t.created,t.id)]);
export const chatAttachments=sqliteTable('chat_attachments',{id:text('id').primaryKey(),room:text('room').notNull(),user:text('user').notNull(),message:text('message'),key:text('key').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),digest:text('digest').notNull(),created:integer('created').notNull()},t=>[index('idx_chat_attachment_message').on(t.message)]);
export const chatReviews=sqliteTable('chat_reviews',{message:text('message').primaryKey(),status:text('status').notNull().default('pending'),reason:text('reason').notNull().default(''),categories:text('categories').notNull().default('[]'),lease:integer('lease').notNull().default(0),created:integer('created').notNull(),updated:integer('updated').notNull().default(0),reviewer:text('reviewer')},t=>[index('idx_chat_review_queue').on(t.status,t.lease)]);
export const chatReactions=sqliteTable('chat_reactions',{message:text('message').notNull(),user:text('user').notNull(),emoji:text('emoji').notNull()},t=>[uniqueIndex('idx_chat_reaction').on(t.message,t.user)]);
export const groupLinks=sqliteTable('group_links',{token:text('token').primaryKey(),groupId:text('group_id').notNull(),creator:text('creator').notNull(),created:integer('created').notNull()},t=>[uniqueIndex('idx_group_link').on(t.groupId)]);

export const chatPush=sqliteTable('chat_push',{id:text('id').primaryKey(),message:text('message').notNull(),subscription:text('subscription').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull(),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),nextAttempt:integer('next_attempt').notNull().default(0)},t=>[index('idx_chat_push_pending').on(t.status,t.nextAttempt)]);

export const invitationPush=sqliteTable('invitation_push',{id:text('id').primaryKey(),subscription:text('subscription').notNull(),recipient:text('recipient').notNull(),actor:text('actor').notNull(),kind:text('kind').notNull(),source:text('source').notNull(),created:integer('created').notNull(),expires:integer('expires').notNull(),status:text('status').notNull().default('pending'),attempts:integer('attempts').notNull().default(0),nextAttempt:integer('next_attempt').notNull().default(0)},t=>[index('idx_invitation_push_pending').on(t.status,t.nextAttempt)]);

export const gameHunts=sqliteTable('game_hunts',{challenge:text('challenge').primaryKey(),week:text('week').unique(),lightning:integer('lightning').notNull().default(0),bonus:text('bonus')});
export const bonusReviews=sqliteTable('bonus_reviews',{submission:text('submission').primaryKey(),status:text('status').notNull().default('pending'),reason:text('reason').notNull().default(''),lease:integer('lease').notNull().default(0),updated:integer('updated').notNull().default(0)});
export const gameAwards=sqliteTable('game_awards',{user:text('user').notNull(),award:text('award').notNull(),created:integer('created').notNull(),seen:integer('seen').notNull().default(0)},t=>[uniqueIndex('idx_game_awards').on(t.user,t.award)]);
