import {createAppeal} from '@/lib/judging';
import {identity,member,origin,one,all,run,db,wrap,json,fail,str} from '@/lib/server';
import {privacySettings,setPrivacy,PRIVACY_VERSION} from '@/lib/privacy';
export const dynamic='force-dynamic';
export const GET=wrap(async()=>{const u=await identity();const groups=await all('SELECT id,name FROM groups WHERE owner=?',u.userId);for(const g of groups)g.members=await all("SELECT m.id,m.name FROM group_members gm JOIN members m ON m.id=gm.user WHERE gm.group_id=? AND gm.user<>? AND m.status='approved' ORDER BY m.name",g.id,u.userId);return json({preferences:await privacySettings(u.userId),groups,devices:await all('SELECT id,provider,created,updated FROM push_subscriptions WHERE user=?',u.userId),version:PRIVACY_VERSION});});
export const POST=wrap(async(req:Request)=>{origin(req);const u=await identity(),b:any=await req.json();if(!b||typeof b!=='object'||Array.isArray(b))fail('Ugyldig personvernvalg.');if(b.action==='analytics'){if(typeof b.analytics!=='boolean')fail('Velg ja eller nei til statistikk.');const previous=await privacySettings(u.userId);await setPrivacy(u.userId,{analytics:b.analytics,pushPreview:previous.pushPreview});return json({ok:true,preferences:await privacySettings(u.userId)});}if(b.action==='preferences')return json({ok:true,preferences:await setPrivacy(u.userId,b)});
if(b.action==='transfer-group'){const group=str(b.group,100),target=str(b.user,100);if(target===u.userId)fail('Velg et annet medlem.');const result=await run("UPDATE groups SET owner=? WHERE id=? AND owner=? AND EXISTS(SELECT 1 FROM group_members gm JOIN members m ON m.id=gm.user WHERE gm.group_id=groups.id AND gm.user=? AND m.status='approved')",target,group,u.userId,target);if(!result.meta.changes)fail('Velg et godkjent medlem i din egen gruppe.',403);await run('DELETE FROM group_links WHERE group_id=?',group);return json({ok:true});}
if(b.action==='revoke-device'){const id=str(b.id,100);await db().batch(['push_deliveries','social_push','chat_push','invitation_push','review_push'].map(t=>db().prepare(`DELETE FROM ${t} WHERE subscription IN(SELECT id FROM push_subscriptions WHERE id=? AND user=?)`).bind(id,u.userId)).concat([db().prepare("DELETE FROM settings WHERE key='push_test:'||? AND EXISTS(SELECT 1 FROM push_subscriptions WHERE id=? AND user=?)").bind(id,id,u.userId),db().prepare('DELETE FROM push_subscriptions WHERE id=? AND user=?').bind(id,u.userId)]));return json({ok:true});}
if(b.action==='bonus-request'){
 const m=await member(),id=str(b.id,100),now=Date.now();
 const eligible="SELECT 1 FROM submissions s JOIN game_hunts g ON g.challenge=s.challenge WHERE s.id=? AND s.user=? AND s.valid=1 AND g.bonus IS NOT NULL";
 if(!await one(eligible,id,m.id))fail('Velg ditt eget gyldige bilde fra en jakt med bonusoppdrag.',403);
 await db().batch([
  db().prepare('INSERT OR IGNORE INTO settings(key,value) SELECT ?,? WHERE EXISTS('+eligible+')').bind('bonus-opt:'+id,JSON.stringify({user:m.id,version:PRIVACY_VERSION,created:now,purpose:'bonus'}),id,m.id),
  db().prepare("INSERT OR IGNORE INTO bonus_reviews(submission,status,reason,updated) SELECT ?,'manual','Venter på manuell bonusvurdering.',? WHERE EXISTS("+eligible+") AND EXISTS(SELECT 1 FROM settings WHERE key=?)").bind(id,now,id,m.id,'bonus-opt:'+id)
 ]);
 return json({ok:true,bonus:await one('SELECT * FROM bonus_reviews WHERE submission=?',id)});
}
if(b.action==='bonus-appeal'){const id=str(b.id,100),decision=await one("SELECT d.id FROM review_decisions d JOIN submissions s ON s.id=d.submission WHERE d.submission=? AND d.kind='bonus' AND d.current=1 AND s.user=?",id,u.userId);if(!decision)fail('Denne avgjørelsen kan ikke påklages.',409);return json(await createAppeal({decision:decision.id,reason:b.reason},u.userId));}
if(b.action==='bonus-withdraw'){const id=str(b.id,100);if(!await one('SELECT id FROM submissions WHERE id=? AND user=?',id,u.userId))fail('Bildet tilhører ikke deg.',403);await db().batch([db().prepare('DELETE FROM settings WHERE key=?').bind('bonus-opt:'+id),db().prepare('DELETE FROM bonus_reviews WHERE submission=?').bind(id),db().prepare("UPDATE review_appeals SET status='withdrawn',resolved=? WHERE decision IN(SELECT id FROM review_decisions WHERE submission=? AND kind='bonus') AND status='open'").bind(Date.now(),id),db().prepare("UPDATE review_decisions SET current=0 WHERE submission=? AND kind='bonus'").bind(id)]);return json({ok:true});}fail('Ukjent personvernvalg.');});
